#!/usr/bin/env python3
"""Capture the two cdb runs that document issue 5293's failure, and its NDEBUG path.

Run from this directory:

    python capture-cdb.py

Every command is echoed with subprocess.list2cmdline(argv), so the committed
capture states exactly what was executed rather than what someone typed into a
write-up. The DXC checkout root is taken from DXC_REPO (default: five levels up
from this file) and is rewritten to <repo> on the way out, which is this
workspace's convention and what scripts/check_paths.py enforces. Nothing else
in the captured text is altered.

cdb is launched with an argv list, so no shell re-quotes the -c script. (Note
the skill's warning about cdb: it is about invoking it *from PowerShell*, where
it silently produces nothing; a direct CreateProcess from Python is fine, and
routing this through cmd.exe instead breaks on the quoted cdb path.)

Two runs, because an assert arrives one way and NDEBUG behaves another:

  assert-stack   break on the LLVM assert exception (0xE0000001) and print the
                 stack, which is what identifies the failing analysis.
  ndebug-path    `gh` past every assert. Continuing past an assert runs the code
                 a build compiled with NDEBUG would have run, so this shows what
                 the shipped Release binaries actually do with the unchecked
                 value -- the thing the 2024-05-20 and 2026-08-10 comments are
                 about, without needing a Release build.
"""

import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = Path(os.environ.get("DXC_REPO") or HERE.parents[5]).resolve()
DXC = REPO / "build" / "Debug" / "bin" / "dxc.exe"
CDB = Path(os.environ.get(
    "DXC_CDB",
    r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"))

ARGS = ["-E", "main", "-T", "cs_6_6", "repro.hlsl", "-HV", "2021"]

RUNS = {
    "manual-case-assert-stack.txt": (
        'sxe -c "kn 25; q" e0000001; g; q',
        "break on the first LLVM assert exception and print the stack",
    ),
    "manual-case-ndebug-path.txt": (
        'sxe -c "gh" e0000001; g; .lastevent; q',
        "continue past every assert: what a NDEBUG/Release build runs instead",
    ),
}

# Keep the frames that say which analysis failed and drop the loader noise, the
# debugger banner and the DXIL dump. A full cdb transcript is ~200 lines of
# ModLoad.
DROP = re.compile(
    r"^(ModLoad|\*\*\*|   |>>>|\s*$|Microsoft \(R\)|Copyright|"
    r"CommandLine:|Symbol search|Executable search|Response|Deferred|"
    r"\+---|\| |dps @ssp|ExtensionRepository|UseExperimental|AllowNuget|"
    r"NonInteractive|AllowParallel|EnableRedirect|-- Configuring|----->)")

# The DXIL listing that follows a surviving compile is the point (it shows the
# NDEBUG path completing) but not its bulk. Cut it at the first line and say so.
DXIL_START = re.compile(r"^;\s*$")


def redact(text):
    """Rewrite this machine's checkout root to <repo>, both slash spellings."""
    for root in (str(REPO), str(REPO).replace("\\", "/")):
        text = text.replace(root, "<repo>")
        text = text.replace(root.replace("\\", "\\\\"), "<repo>")
    return text


def main():
    if not CDB.is_file():
        sys.exit(f"cdb not found at {CDB}; set DXC_CDB")
    if not DXC.is_file():
        sys.exit(f"dxc not found at {DXC}; set DXC_REPO")

    for name, (script, purpose) in RUNS.items():
        argv = [str(CDB), "-c", script, str(DXC)] + ARGS
        shown = subprocess.list2cmdline(argv)
        proc = subprocess.run(
            argv, cwd=HERE, capture_output=True, text=True, errors="replace")
        body_lines = []
        omitted = 0
        for line in (proc.stdout + proc.stderr).splitlines():
            line = line.rstrip()
            if omitted or DXIL_START.match(line):
                omitted += 1
                continue
            if DROP.match(line):
                continue
            body_lines.append(line)
        if omitted:
            body_lines.append(
                f"[{omitted} further lines: the DXIL listing this compile went "
                f"on to emit, omitted by capture-cdb.py]")
        body = "\n".join(body_lines)
        header = (
            f"# {purpose}\n"
            f"# generated by capture-cdb.py; checkout root rewritten to <repo>\n"
            f"# cdb exit: {proc.returncode}\n"
            f"$ {redact(shown)}\n\n")
        (HERE / name).write_text(redact(header + body) + "\n", encoding="utf-8")
        print(f"wrote {name} ({proc.returncode})")


if __name__ == "__main__":
    main()
