#!/usr/bin/env python3
"""Per-release matrix for issue 5293. Run from this directory:

    python measure-releases.py

`triage.py bisect` answers one question -- does the primary repro trip the symptom
predicate on each release -- and for this issue that answer is uninformative on its own,
for two reasons the matrix exists to cover:

1. Every catalogued release is a **Release** build, so the assert is compiled out and the
   predicate cannot see it. What a release *can* show is whether it carries the analysis
   at all, which control-outparam-presence.hlsl tests behaviourally through
   -Wparameter-usage.
2. Three releases answer `Unknown HLSL version: 2021` and never compile the repro at all.
   `bisect` scored them no-repro, because that string is not one of its invalid-probe
   markers. control-template.hlsl distinguishes "this release predates HLSL 2021
   templates" from "this release rejected something specific to the repro".

Every command is echoed with subprocess.list2cmdline, and exit statuses are read from the
Python that launched the process rather than from a shell variable. Paths are printed
relative to their root so the output is machine-independent.
"""

import json
import os
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
REPO = Path(os.environ.get("DXC_REPO") or HERE.parents[5]).resolve()
DB = Path(os.environ.get("DXC_TRIAGE_CACHE") or (SKILL / ".cache")) / "triage.db"

SHADERS = [
    ("control-template", "control-template.hlsl",
     "HLSL 2021 function templates work at all"),
    ("outparam-analysis", "control-outparam-presence.hlsl",
     "the out-param uninitialized analysis is present (-Wparameter-usage)"),
    ("repro", "repro.hlsl",
     "the issue description's example"),
    ("asobo-scalar-out", "repro-asobo-scalar-out.hlsl",
     "the 2026-08-10 function with a scalar out parameter"),
    ("release-crash", "repro-release-crash.hlsl",
     "the 32-local variant that crashes a Release build"),
    ("rc-no-template", "control-release-crash-no-template.hlsl",
     "control: same 32 locals, no template"),
    ("rc-inout", "control-release-crash-inout.hlsl",
     "control: same 32 locals, inout instead of out"),
]

ARGS = ["-E", "main", "-T", "cs_6_6", "{src}", "-HV", "2021"]
PARAM_USAGE = re.compile(r"-Wparameter-usage")
NO_HV2021 = re.compile(r"Unknown HLSL version")


def display(path):
    text = str(path)
    for root, token in ((str(SKILL), "<skill>"), (str(REPO), "<repo>")):
        text = text.replace(root, token)
    return text


def run(exe, src):
    argv = [str(exe)] + [a.format(src=src) for a in ARGS]
    proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                          errors="replace")
    return subprocess.list2cmdline(argv), proc


def compilers():
    """Ground truth first, then every stable release oldest-first."""
    out = []
    reg = SKILL / ".cache" / "compilers" / "main-debug.json"
    out.append(("main-debug", Path(json.loads(reg.read_text())["exe_path"])))
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, cached_path FROM releases "
        "WHERE prerelease = 0 AND bisectable = 1 AND cached_path IS NOT NULL "
        "ORDER BY build_date").fetchall()
    con.close()
    for row in rows:
        out.append((row["tag"], Path(row["cached_path"])))
    return out


def main():
    lines = [
        "# per-release matrix for issue 5293, generated by measure-releases.py",
        "# every command below was executed; exit statuses come from the "
        "launching process, not from a shell variable",
        "# HV2021: does this build accept -HV 2021 / templates at all",
        "# WPARAM: does it emit -Wparameter-usage, i.e. does it carry the "
        "out-param uninitialized analysis (1380cf88e, 2023-03-01)",
        "",
    ]
    table = []
    for tag, exe in compilers():
        if not exe.is_file():
            lines.append(f"## {tag}: MISSING {display(exe)}")
            continue
        ver = subprocess.run([str(exe), "--version"], capture_output=True,
                             text=True, errors="replace")
        lines.append(f"## {tag}")
        lines.append(f"   exe: {display(exe)}")
        lines.append(f"   --version: {ver.stdout.strip() or ver.stderr.strip()}")
        row = {"tag": tag}
        for name, src, purpose in SHADERS:
            shown, proc = run(exe, src)
            text = proc.stdout + proc.stderr
            code = proc.returncode & 0xFFFFFFFF
            lines.append(f"   $ {display(shown)}")
            lines.append(f"     [{name}] exit=0x{code:08X}  ({purpose})")
            first = next((ln.strip() for ln in text.splitlines() if ln.strip()),
                         "<no output>")
            lines.append(f"     first line: {first}")
            row[name] = code
            if name == "control-template":
                row["hv2021"] = not NO_HV2021.search(text) and code == 0
            if name == "outparam-analysis":
                row["wparam"] = bool(PARAM_USAGE.search(text))
        lines.append("")
        table.append(row)

    lines.append("summary")
    lines.append(f"{'build':<16}{'HV2021':<9}{'WPARAM':<9}"
                 f"{'repro':<13}{'asobo-scalar-out':<20}"
                 f"{'release-crash':<15}{'rc-no-tmpl':<13}{'rc-inout':<13}")
    for row in table:
        lines.append(
            f"{row['tag']:<16}"
            f"{('yes' if row.get('hv2021') else 'no'):<9}"
            f"{('yes' if row.get('wparam') else 'no'):<9}"
            f"{('0x%08X' % row['repro']):<13}"
            f"{('0x%08X' % row['asobo-scalar-out']):<20}"
            f"{('0x%08X' % row['release-crash']):<15}"
            f"{('0x%08X' % row['rc-no-template']):<13}"
            f"{('0x%08X' % row['rc-inout']):<13}")

    (HERE / "manual-case-release-matrix.txt").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines[-len(table) - 2:]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
