#!/usr/bin/env python3
"""Release history for #4619, with the reflection reader held fixed.

`triage.py bisect` MUST NOT be run on this issue. It resolves each tag to that
release's `dxc.exe`, and `dxc.exe` never calls ID3D12ShaderReflection at all --
so every release would fail to produce the harness's RESULT line, score
`no-repro`, and the tool would confidently report the exact opposite of the
truth. This is the #3237 / #2923 release-matrix pattern instead: one fixed
harness (`bin/refl4619.exe`), pointed at each release's own `dxcompiler.dll`
through DXC_REFLECT_DLL, so both the compile and the reflection come from the
release under test.

Per release it runs two cases:

  repro.hlsl        -T ms_6_5   the issue's own question
  control-compute   -T cs_6_5   the per-release instrument control

The control is what makes a clean mesh row meaningful. SKILL.md is explicit
that a feature-presence control must run on *every* probed release, not only on
ground truth (#2922): a release that returns 0,0,0 for a compute shader too
would be telling us its reflection is broken or its container is unreadable,
not that mesh support is missing.

Every command is echoed with subprocess.list2cmdline(argv), so the transcript
records what actually ran rather than a transcription of it (SKILL.md, #2922).
All output is passed through triage.redact_paths().

    python measure-history.py > manual-case-release-history.txt
"""

import os
import re
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))
sys.path.insert(0, SCRIPTS)

import triage  # noqa: E402

HARNESS = os.path.join(HERE, "bin", "refl4619.exe")

CASES = [
    ("repro", ["-T", "ms_6_5", "-E", "main", "repro.hlsl"]),
    ("control-compute", ["-T", "cs_6_5", "-E", "main", "control-compute.hlsl"]),
]

# Lines worth keeping per case: the RESULT line is the machine-readable answer,
# the SELFCHECK lines say whether the walk is trustworthy, and a diagnostic or
# WALK-INCOMPLETE marker is how a release that cannot express ms_6_5 announces
# itself. Anything else is noise in a 20-release table.
KEEP = re.compile(
    r"^(RESULT:|SELFCHECK:|refl4619:|PSV\.RuntimeInfo1\.MS1\.MeshOutputTopology|"
    r"PSV\.RuntimeInfoVersion|DXIL\.numthreads-metadata-tuple|"
    r"IDxcCompiler::Compile status|error:|warning:|.*: error| error [A-Z])"
)


def emit(text):
    sys.stdout.write(triage.redact_paths(text))


def releases():
    con = sqlite3.connect(triage.DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, build_date, prerelease, cached_path FROM releases "
        "WHERE cached_path IS NOT NULL AND prerelease = 0 "
        "ORDER BY build_date"
    ).fetchall()
    con.close()
    return rows


def main():
    emit("# refl4619 release matrix for issue 4619\n")
    emit("#\n")
    emit("# Reader held fixed (bin/refl4619.exe, built from refl4619.cpp);\n")
    emit("# DXC_REFLECT_DLL varied over each stable release's dxcompiler.dll,\n")
    emit("# which is what both compiles the shader and answers the reflection\n")
    emit("# calls. Generated by measure-history.py; do not hand-edit.\n")
    emit("#\n")
    emit("# Prereleases are excluded by policy (SKILL.md). The issue text names\n")
    emit("# none, so there is no release-policy.json opt-in.\n\n")

    if not os.path.exists(HARNESS):
        emit("FATAL: %s is missing; run build-refl4619.cmd first\n"
             % triage.redact_paths(HARNESS))
        return 1

    summary = []
    for r in releases():
        dll = os.path.join(os.path.dirname(r["cached_path"]), "dxcompiler.dll")
        emit("=" * 74 + "\n")
        emit("release %s  (build %s)\n" % (r["tag"], r["build_date"]))
        emit("dll: %s\n" % triage.redact_paths(dll))
        if not os.path.exists(dll):
            emit("SKIPPED: no dxcompiler.dll beside this release's dxc.exe\n\n")
            summary.append((r["tag"], r["build_date"], "no-dll", "no-dll"))
            continue

        env = dict(os.environ, DXC_REFLECT_DLL=dll)
        row = {}
        for name, args in CASES:
            argv = [HARNESS] + args
            emit("\n$ set DXC_REFLECT_DLL=%s\n" % triage.redact_paths(dll))
            emit("$ %s\n" % triage.redact_paths(subprocess.list2cmdline(argv)))
            p = subprocess.run(argv, cwd=HERE, env=env, capture_output=True,
                               text=True, timeout=300)
            out = (p.stdout or "") + (p.stderr or "")
            for line in out.splitlines():
                if KEEP.match(line.strip()) or KEEP.match(line):
                    emit("  " + line.strip() + "\n")
            emit("  [exit %d]\n" % p.returncode)

            m = re.search(r"GETTHREADGROUPSIZE=(\d+,\d+,\d+)", out)
            t = re.search(r"PSV-MESH-TOPOLOGY=(\d+)", out)
            row[name] = (m.group(1) if m else "-",
                         t.group(1) if t else "-",
                         p.returncode)
        emit("\n")
        summary.append((
            r["tag"], r["build_date"],
            "%s (exit %d)" % (row["repro"][0], row["repro"][2]),
            "%s (exit %d)" % (row["control-compute"][0],
                              row["control-compute"][2]),
        ))

    emit("=" * 74 + "\n")
    emit("SUMMARY -- ID3D12ShaderReflection::GetThreadGroupSize out-values\n")
    emit("%-16s %-12s %-24s %s\n" % ("release", "build", "ms_6_5 repro",
                                     "cs_6_5 control"))
    for tag, date, ms, cs in summary:
        emit("%-16s %-12s %-24s %s\n" % (tag, date, ms, cs))
    emit("\n")
    emit("A row of 0,0,0 for the mesh repro beside 32,2,1 for the compute\n")
    emit("control is the reported symptom. A row where BOTH are '-' is a\n")
    emit("release that could not run the case at all.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
