#!/usr/bin/env python3
"""The fate of #4619's resolution, captured from git and GitHub.

The interesting half of this triage is not "does it still reproduce" -- it is
what happened to the answer. Half of #4619 was fixed in 2022 by a PR that never
mentioned the issue, so nothing on the issue's timeline records it. This script
captures the evidence for that claim so it is on disk rather than in prose.

All GitHub access is read-only (`gh ... view` / `gh api` GET). Every command is
echoed with subprocess.list2cmdline(argv); output goes through
triage.redact_paths().

    python measure-resolution.py > manual-case-resolution-fate.txt
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))
sys.path.insert(0, SCRIPTS)

import triage  # noqa: E402

REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", "..", ".."))
FIX = "80fb4622a"
FILE = "lib/HLSL/DxilContainerReflection.cpp"


def emit(text):
    sys.stdout.write(triage.redact_paths(text))


def run(argv, cwd=REPO, note=None):
    emit("$ %s\n" % triage.redact_paths(subprocess.list2cmdline(argv)))
    p = subprocess.run(argv, cwd=cwd, capture_output=True, text=True,
                       timeout=300, shell=False)
    out = (p.stdout or "") + (p.stderr or "")
    emit(triage.redact_paths(out.rstrip() + "\n" if out.strip() else "(no output)\n"))
    emit("[exit %d]%s\n\n" % (p.returncode, ("  " + note) if note else ""))
    return p


def gh(args, note=None):
    exe = "gh.exe"
    return run([exe] + args, note=note)


def main():
    emit("# #4619: what happened to the resolution\n")
    emit("#\n")
    emit("# Generated by measure-resolution.py; do not hand-edit.\n")
    emit("# All GitHub calls are read-only.\n\n")

    emit("=" * 74 + "\n")
    emit("1. The commit that changed the behaviour the reporter measured.\n")
    emit("=" * 74 + "\n\n")

    run(["git", "--no-pager", "log", "-S", "IsMS()", "--oneline", "--date=short",
         "--format=%h %ad %s", "--", FILE],
        note="every commit that added or removed the token IsMS() in this file")

    run(["git", "--no-pager", "show", FIX, "--format=%H%n%an%n%ad%n%s", "--stat"])

    emit("=" * 74 + "\n")
    emit("2. Which releases contain it.\n")
    emit("=" * 74 + "\n\n")

    for tag in ("v1.7.2207", "v1.7.2212"):
        p = run(["git", "merge-base", "--is-ancestor", FIX, tag])
        emit("    -> %s %s %s\n\n" % (
            FIX, "IS IN" if p.returncode == 0 else "is NOT in", tag))

    run(["git", "--no-pager", "rev-list", "--count", "v1.7.2207..v1.7.2212"],
        note="commits in the window the release matrix brackets")
    run(["git", "--no-pager", "log", "--oneline", "v1.7.2207..v1.7.2212", "--",
         FILE],
        note="of those, the ones touching the reflection implementation")

    emit("=" * 74 + "\n")
    emit("3. The link that was never made.\n")
    emit("=" * 74 + "\n\n")

    gh(["pr", "view", "4745", "--repo", "microsoft/DirectXShaderCompiler",
        "--json", "number,title,state,mergedAt,body,closingIssuesReferences"],
       note="closingIssuesReferences is the machine-readable 'this PR closes X'")

    gh(["api",
        "search/issues?q=repo%3Amicrosoft%2FDirectXShaderCompiler+GetThreadGroupSize&per_page=20",
        "--jq",
        '.items[] | "\\(.number)  \\(.state)  \\(if .pull_request then "PR " else "iss" end)  \\(.title)"'],
       note="every issue or PR in the repo naming the accessor")

    gh(["api",
        "repos/microsoft/DirectXShaderCompiler/issues/4619/timeline?per_page=100",
        "--jq",
        '.[] | "\\(.created_at // .submitted_at)  \\(.event // "?")  \\(.actor.login // .user.login // "-")  \\(.label.name // .milestone.title // "")"'],
       note="the issue's whole timeline; note the absence of any cross-reference")

    gh(["api", "repos/microsoft/DirectXShaderCompiler/issues/4619/comments",
        "--jq", "length"],
       note="comment count")

    emit("=" * 74 + "\n")
    emit("Reading.\n")
    emit("=" * 74 + "\n\n")
    emit("PR #4745 fixed the GetThreadGroupSize half of #4619 and closes\n")
    emit("nothing. A repo-wide search for the accessor the reporter named\n")
    emit("returns exactly two things -- this issue and that PR -- with no\n")
    emit("edge between them. So the issue's own timeline shows no fix: it was\n")
    emit("labelled `enhancement` + `reflection` in 2024-01 and milestoned to\n")
    emit("Backlog in 2024-09, both well after the fix had shipped, and it\n")
    emit("still has zero comments.\n")
    emit("\n")
    emit("The second half -- output topology on the reflection API -- is not\n")
    emit("fixed, and the release matrix shows it never was. That half really\n")
    emit("is an open enhancement.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
