#!/usr/bin/env python3
"""Why `dxa -dumpreflection` cannot answer either half of #4619.

SKILL.md says to try `dxa -dumpreflection` before writing a host program for a
reflection question -- and, in the same breath, that "an absent field proves
nothing if it never calls the accessor". That is exactly the situation here, so
this generator captures both the dump and the source facts that explain it.

Every command is echoed with subprocess.list2cmdline(argv) rather than
transcribed (SKILL.md, #2922), and all output goes through
triage.redact_paths().

    python measure-dxa.py > manual-case-dxa-dumpreflection.txt
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))
sys.path.insert(0, SCRIPTS)

import triage  # noqa: E402

REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", "..", ".."))
BIN = os.path.join(REPO, "build", "Debug", "bin")
DXC = os.path.join(BIN, "dxc.exe")
DXA = os.path.join(BIN, "dxa.exe")
DUMPER = os.path.join(REPO, "lib", "DxilContainer", "D3DReflectionDumper.cpp")


def emit(text):
    sys.stdout.write(triage.redact_paths(text))


def run(argv):
    emit("$ %s\n" % triage.redact_paths(subprocess.list2cmdline(argv)))
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       timeout=300)
    emit(triage.redact_paths((p.stdout or "") + (p.stderr or "")))
    emit("[exit %d]\n\n" % p.returncode)
    return p


def main():
    emit("# #4619: what `dxa -dumpreflection` can and cannot say\n")
    emit("#\n")
    emit("# Generated by measure-dxa.py; do not hand-edit.\n\n")

    run([DXC, "--version"])
    run([DXC, "-T", "ms_6_5", "-E", "main", "repro.hlsl", "-Fo",
         "scratch-ms.dxil"])
    run([DXA, "-dumpreflection", "scratch-ms.dxil"])

    emit("-" * 74 + "\n")
    emit("Why the dump is silent on both questions.\n")
    emit("\n")
    emit("`dxa -dumpreflection` drives ID3D12ShaderReflection through DXC's\n")
    emit("own D3DReflectionDumper. An absent field in its output therefore\n")
    emit("means one of two very different things, and only reading the dumper\n")
    emit("tells you which: the accessor returned nothing, or the dumper never\n")
    emit("called it. Here it is the second, for both halves of the issue.\n\n")

    # grep the dumper rather than asserting what it contains.
    emit("$ %s\n" % triage.redact_paths(subprocess.list2cmdline(
        ["grep", "-n", "ThreadGroup|Topology|ShaderKind::Mesh", DUMPER])))
    with open(DUMPER, "r", encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    hits = 0
    for n, line in enumerate(lines, 1):
        if ("ThreadGroup" in line or "Topology" in line
                or "ShaderKind::Mesh" in line):
            emit("%5d: %s\n" % (n, line.rstrip()))
            hits += 1
    emit("[%d matching lines]\n\n" % hits)

    # Self-consistency: a generator that can return "nothing here" and
    # "nothing matched" through the same channel will eventually be believed
    # (SKILL.md, #2923). Say loudly if the search found nothing.
    if hits == 0:
        emit("measure-dxa: PARSE-WARNING: 0 lines matched in the dumper; the\n"
             "             source-side claim below is UNSUPPORTED by this run\n\n")

    tg = sum(1 for line in lines if "GetThreadGroupSize" in line)
    emit("GetThreadGroupSize call sites in D3DReflectionDumper.cpp: %d\n" % tg)
    emit("\n")
    emit("So: the dumper never calls GetThreadGroupSize at all, and prints\n")
    emit("GSOutputTopology only inside its `ShaderKind == Geometry` branch.\n")
    emit("Its Mesh branch prints one line, about PatchConstantParameters.\n")
    emit("That is why #4619 needs refl4619.cpp, which calls the accessors the\n")
    emit("reporter named, directly.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
