"""Generate manual-case-fidelity.txt for issue 4614.

Checks that repro.hlsl is byte-identical (modulo line endings) to:
  1. the fenced code block in the issue body, and
  2. the source stored behind the Compiler Explorer link a maintainer posted
     in the issue on 2024-02-14 (https://godbolt.org/z/7zW3febaj),
and that the arguments agree.

Point: establish reporter-instance fidelity mechanically rather than by eye,
per SKILL.md ("compare that quote mechanically against the matching capture").
The godbolt call is a read-only GET against a link that is already public in
the issue thread.

Run from this directory:  python gen-fidelity.py
"""
import hashlib
import json
import os
import re
import sys
import urllib.request

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SHORTLINK = "7zW3febaj"
API = "https://godbolt.org/api/shortlinkinfo/" + SHORTLINK


def norm(s):
    return s.replace("\r\n", "\n").strip("\n")


def sha(s):
    return hashlib.sha256(norm(s).encode("utf-8")).hexdigest()


def main():
    out = ["# issue 4614 -- repro fidelity check",
           "# generated by gen-fidelity.py; do not hand-edit", ""]

    mine = open(os.path.join(HERE, "repro.hlsl"), encoding="utf-8").read()

    issue = json.load(open(os.path.join(HERE, "issue.json"), encoding="utf-8"))
    # The fetched body uses CRLF, so normalise BEFORE matching the fence -- a
    # \n-only pattern silently finds zero blocks and manufactures a mismatch.
    body = issue["body"].replace("\r\n", "\n")
    blocks = re.findall(r"```[a-z]*\n(.*?)```", body, re.S)
    out.append("issue body fenced code blocks: %d" % len(blocks))
    if not blocks:
        raise SystemExit("no fenced block found in issue body -- fix the regex "
                         "rather than reporting a mismatch")
    body_src = blocks[0]

    out.append("$ GET " + API)
    d = json.load(urllib.request.urlopen(API))
    sess = d["sessions"][0]
    ce_src = sess["source"]
    ce_args = [(c.get("id"), c.get("options")) for c in sess.get("compilers", [])]

    out.append("")
    out.append("sha256 of each source, newline-normalised and outer-blank-stripped:")
    out.append("  repro.hlsl              %s" % sha(mine))
    out.append("  issue body code block   %s" % sha(body_src))
    out.append("  godbolt.org/z/%s   %s" % (SHORTLINK, sha(ce_src)))
    out.append("")
    out.append("repro.hlsl == issue body : %s" % (norm(mine) == norm(body_src)))
    out.append("repro.hlsl == CE source  : %s" % (norm(mine) == norm(ce_src)))
    out.append("")
    out.append("arguments:")
    out.append("  cmd.txt  : %s"
               % open(os.path.join(HERE, "cmd.txt"), encoding="utf-8").read().strip())
    out.append("  issue body says: -E main -T vs_6_0")
    for cid, opts in ce_args:
        out.append("  CE pane  : %s  %s" % (cid, opts))

    path = os.path.join(HERE, "manual-case-fidelity.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(out)) + "\n")
    print("wrote", triage.redact_paths(path))


if __name__ == "__main__":
    main()
