"""Generate manual-case-assert-stack.txt for issue 4614.

Two cases, both driven through cdb.exe against the ground-truth Debug dxc:

  A. the assert itself, with a stack, to confirm the failure is where #3016's
     stack said it was (SROA_Helper::RewriteBitCast in SROA_HLSL);
  B. the same run with the assert *continued past* (`gh` = "go handled"), which
     per SKILL.md emulates NDEBUG -- i.e. it runs the code a Release build with
     asserts compiled out would have run. That is what turns "assert" and "hang"
     into one measurement rather than two claims.

The command actually executed is printed via subprocess.list2cmdline, so the
transcript is generated rather than transcribed. Paths are normalised with
triage.redact_paths().

Run from this directory:  python gen-assert-stack.py
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
DXC = os.path.join(triage.REPO_ROOT, "build", "Debug", "bin", "dxc.exe")
ARGS = ["-T", "vs_6_0", "-E", "main", "repro.hlsl"]

CASES = [
    ("A. assert + stack (Debug ground truth)",
     'sxe -c "kn 14; gh" e0000001; g; q',
     120,
     "Where does it assert? #3016's 2020 stack named "
     "SROA_Helper::RewriteBitCast <- RewriteForScalarRepl <- DoScalarReplacement "
     "<- SROA_HLSL::performScalarRepl."),
    ("B. assert continued past -- NDEBUG emulation",
     'sxe -c "gh" e0000001; g; q',
     240,
     "`gh` continues past the assert, running what a Release build (asserts "
     "compiled out) would run. If the Release symptom is the reported hang, "
     "this run should not terminate."),
]


def main():
    out = []
    out.append("# issue 4614 -- assert stack and NDEBUG-emulated continuation")
    out.append("# generated by gen-assert-stack.py; do not hand-edit")
    out.append("# dxc: " + triage.redact_paths(DXC))
    ver = subprocess.run([DXC, "--version"], capture_output=True, text=True)
    out.append("# dxc --version: " + ver.stdout.strip())
    out.append("")

    for title, script, timeout, why in CASES:
        argv = [CDB, "-c", script, DXC] + ARGS
        out.append("=" * 72)
        out.append(title)
        out.append("why: " + why)
        out.append("$ " + triage.redact_paths(subprocess.list2cmdline(argv)))
        out.append("cwd: <triage>/data/issues/4614   timeout: %ds" % timeout)
        try:
            p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                               timeout=timeout)
            text = (p.stdout or "") + (p.stderr or "")
            out.append("[cdb exit] %d" % p.returncode)
            timed_out = False
        except subprocess.TimeoutExpired as e:
            text = ((e.stdout or b"").decode("utf-8", "replace")
                    + (e.stderr or b"").decode("utf-8", "replace"))
            out.append("[cdb exit] TIMEOUT after %ds -- did not terminate" % timeout)
            timed_out = True
        out.append("--- cdb output ---")
        out.append(triage.redact_paths(text.rstrip()))
        if timed_out:
            out.append("")
            out.append("(no further output: the process was still running when "
                       "the harness killed it)")
        out.append("")

    path = os.path.join(HERE, "manual-case-assert-stack.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", triage.redact_paths(path))


if __name__ == "__main__":
    main()
