"""Generate manual-case-release-matrix.txt for issue 4614.

Summarises every capture in this directory: which compiler, which signature
(hang vs internal failure vs clean), the exit status, and whether the run
emitted any diagnostic. The point is to show, per build, WHICH of the two
signatures of this one defect was observed -- which is what justifies the
composed any_of[timeout, internal_failure] predicate in match.json.

It also acts as an invalid-probe check: a release that rejected the shader
would show an `error:` line and a fast E_FAIL exit rather than a hang.

Reads only the committed capture files; runs no compiler.

Run from this directory:  python gen-release-matrix.py
"""
import glob
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

# release order as catalogued by triage.py (build date encoded in the asset)
ORDER = ["v1.4.1907", "v1.5.2010", "v1.6.2104", "v1.6.2106", "v1.6.2112",
         "v1.7.2207", "v1.7.2212", "v1.7.2212.1", "v1.7.2308", "v1.8.2403",
         "v1.8.2403.1", "v1.8.2403.2", "v1.8.2405", "v1.8.2407", "v1.8.2502",
         "v1.8.2505", "v1.8.2505.1", "v1.9.2602", "v1.9.2602.24", "v1.9.2607",
         "main-debug"]


def parse(path):
    meta, body = {}, []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("# ") and ":" in line and not body:
                k, _, v = line[2:].partition(":")
                meta[k.strip()] = v.strip()
            else:
                body.append(line)
    return meta, "".join(body)


def signature(meta, body):
    if meta.get("timed_out") == "1":
        return "HANG (no result in 60s)"
    try:
        rc = int(meta.get("exit", "0"))
    except ValueError:
        return "?"
    if rc == 0:
        return "clean (exit 0)"
    return "internal failure (0x%08X)" % (rc & 0xFFFFFFFF)


def has_diagnostic(body):
    """True only for a real compiler diagnostic (file:line:col: error: ...).

    A bare `"error:" in body` test is wrong here: dxc's crash banner is
    'Internal compiler error: LLVM Assert', which contains the substring and
    would report the asserting build as having diagnosed the shader.
    """
    return re.search(r"^.*?:\d+:\d+: error:", body, re.MULTILINE) is not None


def main():
    out = ["# issue 4614 -- signature per build",
           "# generated by gen-release-matrix.py from the committed captures;"
           " do not hand-edit",
           "# predicate: match.json = any_of[timeout, internal_failure]",
           ""]

    rows = []
    for name in ORDER:
        path = os.path.join(HERE, "out-%s.txt" % name)
        if not os.path.exists(path):
            continue
        meta, body = parse(path)
        diag = "yes" if has_diagnostic(body) else "no"
        rows.append((name, meta.get("verdict", "?"), signature(meta, body),
                     meta.get("exit", "?"), diag))

    w = max(len(r[0]) for r in rows)
    out.append("%-*s  %-8s  %-28s  %-12s  %s"
               % (w, "build", "verdict", "signature", "exit field",
                  "any 'error:' line?"))
    out.append("-" * (w + 70))
    for name, verdict, sig, rc, diag in rows:
        out.append("%-*s  %-8s  %-28s  %-12s  %s" % (w, name, verdict, sig, rc, diag))

    hangs = sum(1 for r in rows if r[2].startswith("HANG"))
    fails = sum(1 for r in rows if r[2].startswith("internal"))
    diags = sum(1 for r in rows if r[4] == "yes")
    out.append("")
    out.append("%d/%d builds hang; %d/%d fail internally; %d emit a compiler"
               " diagnostic." % (hangs, len(rows), fails, len(rows), diags))
    out.append("")
    out.append("Read this as the justification for the composed predicate:")
    out.append("  * a bare  internal_failure  predicate scores the %d hanging"
               " builds as CLEAN," % hangs)
    out.append("  * a bare  timeout           predicate scores the %d asserting"
               " build(s) as CLEAN." % fails)
    out.append("  Either alone reports this open, always-reproducing defect as"
               " fixed.")
    out.append("")
    out.append("%d builds emitted a diagnostic, so no probe was demoted or"
               " demotable as" % diags)
    out.append("invalid: nothing here was rejected before reaching the pass"
               " under test.")
    out.append("")
    out.append("CAVEAT on the hang rows: 60s is triage.py's TIMEOUT, not a"
               " proof of")
    out.append("non-termination. The unbounded claim rests on the source:"
               " under NDEBUG")
    out.append("the loop guard at ScalarReplAggregatesHLSL.cpp:2994 expands to"
               " `do {")
    out.append("(void)(local); } while (0)`, so nothing stops"
               " RewriteForScalarRepl's")
    out.append("`while (!V->use_empty())` re-selecting the same use forever.")

    out.append("")
    out.append("Controls (variant-*.txt), all --expect no-match:")
    for path in sorted(glob.glob(os.path.join(HERE, "variant-*.txt"))):
        meta, body = parse(path)
        label = os.path.basename(path)[len("variant-"):-len("-main-debug.txt")]
        out.append("  %-18s %-10s %s"
                   % (label, meta.get("verdict", "?"), signature(meta, body)))

    path = os.path.join(HERE, "manual-case-release-matrix.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(out)) + "\n")
    print("wrote", triage.redact_paths(path))


if __name__ == "__main__":
    main()
