"""Generate manual-case-hang-evidence.txt for issue 4614.

The 60s TIMEOUT in triage.py proves "no result in 60s", not "does not
terminate". This closes that gap for the newest stable release, v1.9.2607, by:

  1. letting it run far longer than the triage timeout, and
  2. sampling its stack twice while it runs, via a non-invasive cdb attach
     (`qd` = quit and detach), to show WHERE it is spending that time.

A slow compile and an infinite loop look identical from the outside; a stack
sample inside SROA_Helper::RewriteForScalarRepl does not.

Paths are normalised with triage.redact_paths(); every command is printed via
subprocess.list2cmdline rather than transcribed.

Run from this directory:  python gen-hang-evidence.py
"""
import os
import re
import subprocess
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
TAG = "v1.9.2607"
ARGS = ["-T", "vs_6_0", "-E", "main", "repro.hlsl"]
SAMPLE_AT = [30, 90]
TOTAL = 300


def release_exe(tag):
    c = triage.con()
    row = c.execute("SELECT cached_path FROM releases WHERE tag=?",
                    (tag,)).fetchone()
    return row[0]


def sample(pid, out):
    # `~*kn` = every thread. A plain `kn` after an attach shows cdb's own
    # injected break-in thread (ntdll!DbgUiRemoteBreakin), not the code that
    # is actually spinning -- which looks like a clean idle stack and says
    # nothing about the hang.
    argv = [CDB, "-p", str(pid), "-c", "~*kn 18; qd"]
    out.append("$ " + triage.redact_paths(subprocess.list2cmdline(argv)))
    p = subprocess.run(argv, capture_output=True, text=True, timeout=180)
    text = triage.redact_paths((p.stdout or "") + (p.stderr or ""))
    keep, on = [], False
    for line in text.splitlines():
        if re.match(r"^\s*\d+\s+Id:", line) or re.match(r"\s*#\s+Child-SP", line):
            on = True
        if on:
            if line.strip().startswith("quit:"):
                break
            keep.append(line)
    out.extend(keep if keep else ["(no frames captured)", text[-2000:]])


def main():
    exe = release_exe(TAG)
    out = ["# issue 4614 -- is the release-build symptom a hang or a slow compile?",
           "# generated by gen-hang-evidence.py; do not hand-edit",
           "# release: %s" % TAG,
           "# exe: %s" % triage.redact_paths(exe),
           ""]

    ver = subprocess.run([exe, "--version"], capture_output=True, text=True)
    out.append("$ dxc --version")
    out.append(ver.stdout.strip())
    out.append("")

    argv = [exe] + ARGS
    out.append("$ " + triage.redact_paths(subprocess.list2cmdline(argv)))
    out.append("(launched, not waited on; stack sampled at %s then killed at %ds)"
               % (", ".join("%ds" % s for s in SAMPLE_AT), TOTAL))
    out.append("")

    t0 = time.time()
    p = subprocess.Popen(argv, cwd=HERE,
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    try:
        for at in SAMPLE_AT:
            while time.time() - t0 < at and p.poll() is None:
                time.sleep(1)
            if p.poll() is not None:
                out.append("!! process exited after %.1fs with %s -- no hang"
                           % (time.time() - t0, p.returncode))
                break
            out.append("=" * 72)
            out.append("stack sample at t=%ds (pid %d, still running)"
                       % (at, p.pid))
            sample(p.pid, out)
            out.append("")
        else:
            while time.time() - t0 < TOTAL and p.poll() is None:
                time.sleep(2)
            elapsed = time.time() - t0
            out.append("=" * 72)
            if p.poll() is None:
                out.append("still running after %.0fs (%.0fx triage.py's 60s "
                           "TIMEOUT); killed by the harness." % (elapsed, elapsed / 60))
                out.append("no stdout/stderr was produced in that time.")
            else:
                out.append("exited after %.1fs with %s" % (elapsed, p.returncode))
    finally:
        if p.poll() is None:
            p.kill()
        p.wait()

    path = os.path.join(HERE, "manual-case-hang-evidence.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(out)) + "\n")
    print("wrote", triage.redact_paths(path))


if __name__ == "__main__":
    main()
