"""Generate manual-case-fix-ancestry.txt for issue 4614.

Establishes, mechanically and in both directions, which stable release first
contains 527d58e5a -- the commit that says "Fixes #3016" and on whose merge
#3016 was closed. SKILL.md: "Before naming a SHA, confirm it with
git merge-base --is-ancestor <sha> <tag>", and a negative result is only
meaningful if the command actually resolved its inputs.

So this runs the ancestry test against every stable tag in the bisect
sequence, and prints the raw exit status of each, rather than asserting a
boundary from `git tag --contains` output alone.

Run from this directory:  python gen-fix-ancestry.py
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

FIX = "527d58e5a"
TAGS = ["v1.4.1907", "v1.5.2010", "v1.6.2104", "v1.6.2106", "v1.6.2112",
        "v1.7.2207", "v1.7.2212", "v1.7.2212.1", "v1.7.2308", "v1.8.2403",
        "v1.8.2403.1", "v1.8.2403.2", "v1.8.2405", "v1.8.2407", "v1.8.2502",
        "v1.8.2505", "v1.8.2505.1", "v1.9.2602", "v1.9.2602.24", "v1.9.2607"]


def git(*args):
    p = subprocess.run(["git", "--no-pager"] + list(args), cwd=triage.REPO_ROOT,
                       capture_output=True, text=True)
    return p.returncode, (p.stdout or "").strip(), (p.stderr or "").strip()


def main():
    out = ["# issue 4614 -- which release first contains the #3016 fix?",
           "# generated by gen-fix-ancestry.py; do not hand-edit", ""]

    rc, sha, _ = git("rev-parse", FIX + "^{commit}")
    out.append("$ git rev-parse %s^{commit}   -> rc=%d" % (FIX, rc))
    out.append(sha)
    if rc != 0:
        raise SystemExit("commit did not resolve; do not report an ancestry "
                         "result from an unresolved ref")

    rc, subj, _ = git("log", "-1", "--format=%H %ad%n%s%n%b", "--date=iso", FIX)
    out.append("")
    out.append("$ git log -1 --format=... --date=iso %s" % FIX)
    out.append(subj)
    out.append("")

    rc, files, _ = git("show", "--name-only", "--format=", FIX)
    out.append("$ git show --name-only --format= %s" % FIX)
    out.append(files)
    out.append("")

    out.append("$ git merge-base --is-ancestor %s <tag>   (rc 0 = contained)"
               % FIX)
    first = None
    for tag in TAGS:
        rcv, _, errv = git("rev-parse", tag + "^{commit}")
        if rcv != 0:
            out.append("  %-14s tag did not resolve: %s" % (tag, errv))
            continue
        rc, _, _ = git("merge-base", "--is-ancestor", FIX, tag)
        contained = (rc == 0)
        if contained and first is None:
            first = tag
        out.append("  %-14s rc=%d  %s"
                   % (tag, rc, "contains it" if contained else "does NOT contain it"))

    out.append("")
    out.append("first stable release containing %s: %s" % (FIX, first))
    out.append("")
    out.append("Both directions are present above, which is what makes the")
    out.append("boundary meaningful: the releases before %s answer rc=1 and the"
               % first)
    out.append("releases from %s on answer rc=0, so the test discriminates" % first)
    out.append("rather than always returning the same value.")
    out.append("")
    out.append("Cross-check against this issue's probes: out-%s.txt scores"
               % first)
    out.append("`repro` (hang), as does every later release. The commit is in")
    out.append("the release; the defect in this repro is not fixed by it.")

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "manual-case-fix-ancestry.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(out)) + "\n")
    print("wrote", triage.redact_paths(path))


if __name__ == "__main__":
    main()
