"""Issue 4721 -- check that every quoted line in comment.md really is a quote.

A cross-model review of an earlier draft found two "verbatim" quotations that
were reconstructions: one had collapsed two capture lines into a single line
joined by a slash, and another did not appear in any capture as written
because Compiler Explorer colourises its diagnostics and the ANSI escapes sit
inside the text. Both read perfectly well. Neither was true.

So this checks mechanically rather than by eye: take every line inside a
fenced code block in comment.md, plus every inline-code span that looks like
compiler output rather than an identifier, and require it to appear in some
captured file in this directory. Shell prompts, ellipses and blank lines are
skipped; ANSI escapes are stripped from the haystack before comparing.

Run it after any edit to comment.md. It is deliberately picky: a false alarm
costs a moment, a false quotation costs the reader's trust in every other
number in the write-up.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "manual-case-quote-check.txt")
ANSI = re.compile(r"\x1b\[[0-9;]*m")

# Inline spans that are source identifiers, file names, flags or citations
# rather than compiler output. These are checked by reading the source, not by
# grepping captures, so exempt them rather than weakening the test.
INLINE_EXEMPT = re.compile(
    r"^(-|/|\.|[A-Za-z_][A-Za-z0-9_]*\.(cpp|h|td|hlsl|txt|json|md|exe)"
    r"|[A-Za-z_:<>]+$)")


def haystack():
    """Every captured output file in the issue directory, ANSI stripped.

    This script's own output is excluded. It lists the quotes it is checking,
    so leaving it in makes every quote match itself and the test can never
    fail.
    """
    blobs = {}
    for name in sorted(os.listdir(HERE)):
        if not name.endswith(".txt") or name == os.path.basename(OUT):
            continue
        with open(os.path.join(HERE, name), encoding="utf-8",
                  errors="replace") as f:
            blobs[name] = ANSI.sub("", f.read())
    return blobs


def quoted_lines(text):
    """Lines inside ``` fences, minus prompts and blanks."""
    out, inside = [], False
    for raw in text.splitlines():
        if raw.strip().startswith("```"):
            inside = not inside
            continue
        if not inside:
            continue
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("$ "):
            continue
        out.append(line)
    return out


def main():
    with open(os.path.join(HERE, "comment.md"), encoding="utf-8") as f:
        comment = f.read()
    blobs = haystack()

    checks = []
    for line in quoted_lines(comment):
        where = [n for n, b in blobs.items() if line in b]
        checks.append(("block", line, where))

    # Inline spans that contain a space and a colon, or start with a lowercase
    # word followed by a colon, look like diagnostics rather than identifiers.
    # Fenced blocks are removed first: a single-backtick scan over the whole
    # file pairs the ``` fences with each other and swallows entire blocks.
    prose = re.sub(r"```.*?```", "", comment, flags=re.S)
    for span in re.findall(r"`([^`\n]+)`", prose):
        if INLINE_EXEMPT.match(span) or ":" not in span or " " not in span:
            continue
        where = [n for n, b in blobs.items() if span in b]
        checks.append(("inline", span, where))

    missing = [c for c in checks if not c[2]]
    lines = [
        "Issue 4721 -- quotation check for comment.md",
        "",
        "Generated by check-quotes.py. Every line below was taken from a",
        "fenced block or an output-shaped inline span in comment.md and",
        "looked up in the captured .txt files in this directory.",
        "",
    ]
    for kind, line, where in checks:
        mark = "OK  " if where else "MISS"
        lines.append(f"[{mark}] ({kind}) {line}")
        if where:
            lines.append(f"         found in: {', '.join(where[:3])}"
                         + (" ..." if len(where) > 3 else ""))
    lines += [
        "",
        "FINDINGS",
        "",
        f"quotes-4721: quoted fragments checked={len(checks)} "
        f"{'PASS' if len(checks) >= 5 else 'PARSE-WARNING -- the extractor '
                                           'found almost nothing, which is '
                                           'more likely a bug than a short '
                                           'comment'}",
        f"quotes-4721: fragments not found in any capture={len(missing)} "
        f"{'PASS' if not missing else 'FAIL'}",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines[-4:]))
    for kind, line, _ in missing:
        print(f"  MISS ({kind}) {line}")


if __name__ == "__main__":
    main()
