"""Issue 4721 -- is a MSVC-style /fixit "accepted"? No: it is discarded.

The trap this guards against: dxc silently ignores unrecognised /-prefixed
arguments. `dxc /fixit shader.hlsl` exits 0, which reads exactly like success.
A clean exit is therefore worthless as evidence that a flag was honoured, and
concluding "so /fixit works" from it would be wrong.

The instrument here is byte identity of the compiled output, not the exit
code. Four compilations of the same shader:

  1. no extra flag                    <- the baseline
  2. /fixit                           <- the spelling under test
  3. /ZZZNONSENSE                     <- a flag that certainly does not exist
  4. -Zi -Qembed_debug                <- a flag that certainly IS honoured

If 1 == 2 == 3 the /-spellings changed nothing about the compilation. On its
own that could also mean the instrument is blind, so 4 is the self-test: a
genuinely honoured flag MUST produce a different hash. If 4 also matched the
baseline the measurement would be meaningless and the script says so.

5 is the dash spelling, which behaves differently in kind: it is parsed, and
rejected, and no object is produced at all. "Rejected" and "ignored" are both
failures to apply a fix-it, but only the first tells the user anything. 6-8
check the issue's other spellings and the `-Xclang` escape hatch, so the
claim "there is no way in" rests on captured output rather than on memory.
"""
import hashlib
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..",
                                                "scripts")))
import triage  # noqa: E402

SCRATCH = os.path.join(HERE, "scratch-spellings")
OUT = os.path.join(HERE, "manual-case-flag-spellings.txt")

CASES = [
    ("baseline", [], "no extra flag"),
    ("slash-fixit", ["/fixit"], "the spelling under test"),
    ("slash-nonsense", ["/ZZZNONSENSE"], "a flag that cannot exist"),
    ("honoured-flag", ["-Zi", "-Qembed_debug"], "self-test: IS honoured"),
    ("dash-fixit", ["-fixit"], "parsed and rejected, unlike the /-forms"),
    ("dash-fixit-eq", ["-fixit=hlsl"], "the issue's second ask"),
    ("dash-fixit-recompile", ["-fixit-recompile"], "the related cc1 spelling"),
    ("dash-xclang", ["-Xclang", "-fixit"], "the escape hatch that is absent"),
]


def sha256(path):
    if not os.path.isfile(path):
        return None
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def main():
    exe = triage.con().execute(
        "SELECT exe_path FROM compilers WHERE id='main-debug'").fetchone()[0]
    if os.path.isdir(SCRATCH):
        shutil.rmtree(SCRATCH)
    os.makedirs(SCRATCH)
    shutil.copy2(os.path.join(HERE, "control-fixed.hlsl"),
                 os.path.join(SCRATCH, "shader.hlsl"))

    # Does the driver's own help text know any of these spellings? A search
    # that finds nothing is only meaningful if the same search can find
    # something, so a token that IS documented is looked up alongside.
    hp = subprocess.run([exe, "-help"], cwd=SCRATCH, capture_output=True,
                        text=True, encoding="utf-8", errors="replace",
                        timeout=180)
    help_text = triage.redact_paths((hp.stdout or "") + (hp.stderr or ""))
    help_hits = {t: (t.lower() in help_text.lower())
                 for t in ("fixit", "fix-it", "Xclang", "Qembed_debug")}

    lines = [
        "Issue 4721 -- /fixit is not accepted, it is discarded.",
        "",
        "Generated by probe-flag-spellings.py. Subject: control-fixed.hlsl",
        "(copied to shader.hlsl), which compiles cleanly, so every case that",
        "is honoured at all produces an object file to compare.",
        "",
    ]
    results = {}
    for label, extra, why in CASES:
        obj = os.path.join(SCRATCH, f"{label}.dxo")
        argv = [exe, "-T", "ps_6_0", "-E", "main", "-HV", "2021"] + extra + \
               ["-Fo", obj, "shader.hlsl"]
        p = subprocess.run(argv, cwd=SCRATCH, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=180)
        text = triage.redact_paths((p.stdout or "") + (p.stderr or ""))
        digest = sha256(obj)
        results[label] = (p.returncode, digest)
        lines += [
            f"### {label}  ({why})",
            "$ " + triage.redact_paths(subprocess.list2cmdline(argv)),
            f"[exit] {p.returncode}",
            f"[object] {'not written' if digest is None else digest}",
            (text.strip() or "(no diagnostic output)"),
            "",
        ]

    lines += [
        "=" * 74,
        "### dxc -help",
        "$ " + triage.redact_paths(subprocess.list2cmdline([exe, "-help"])),
        f"[exit] {hp.returncode}",
        f"[lines] {len(help_text.splitlines())}",
    ] + [f"[contains {t!r}] {v}" for t, v in help_hits.items()] + [""]

    base = results["baseline"][1]
    same_slash = (results["slash-fixit"][1] == base and
                  results["slash-nonsense"][1] == base and base is not None)
    instrument = (results["honoured-flag"][1] is not None and
                  results["honoured-flag"][1] != base)
    dash_rejected = (results["dash-fixit"][0] != 0 and
                     results["dash-fixit"][1] is None)
    all_dash = [k for k in ("dash-fixit", "dash-fixit-eq",
                            "dash-fixit-recompile", "dash-xclang")]
    every_spelling_rejected = all(results[k][0] != 0 and
                                  results[k][1] is None for k in all_dash)

    selftest = [
        "",
        "FINDINGS",
        "",
        f"spellings-4721: /fixit and /ZZZNONSENSE both produce the baseline "
        f"object byte-for-byte={same_slash} "
        f"{'PASS' if same_slash else 'PARSE-WARNING'}",
        f"spellings-4721: instrument self-test, an honoured flag changes the "
        f"object={instrument} {'PASS' if instrument else 'FAIL -- the '
                                                          'comparison above '
                                                          'proves nothing'}",
        f"spellings-4721: the dash spelling is rejected and writes no "
        f"object={dash_rejected} "
        f"{'PASS' if dash_rejected else 'PARSE-WARNING'}",
        f"spellings-4721: every dash spelling the issue could use "
        f"({', '.join(all_dash)}) is rejected={every_spelling_rejected} "
        f"{'PASS' if every_spelling_rejected else 'PARSE-WARNING'}",
        f"spellings-4721: dxc -help documents none of fixit/fix-it/Xclang="
        f"{not any(help_hits[t] for t in ('fixit', 'fix-it', 'Xclang'))} "
        f"{'PASS' if not any(help_hits[t] for t in ('fixit', 'fix-it', 'Xclang')) else 'PARSE-WARNING'}",
        f"spellings-4721: help search self-test, a documented flag IS found="
        f"{help_hits['Qembed_debug']} "
        f"{'PASS' if help_hits['Qembed_debug'] else 'FAIL -- the help search '
                                                    'above proves nothing'}",
        "",
        "Read together: dxc has no /fixit. The /-form is dropped before it "
        "means anything, and its exit code 0 is the exit code of a compile "
        "that simply never saw the flag.",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines + selftest) + "\n")
    print("\n".join(selftest))
    shutil.rmtree(SCRATCH)


if __name__ == "__main__":
    main()
