"""Issue 4721 -- is the fix-it rewriter reachable in clang-for-HLSL?

The interesting question for a feature request is not "does it still repro"
but "how much of this already exists". DXC is a Clang fork, so clang's fix-it
machinery (FixItAction / FixItRewriter, driven by the cc1 flag `-fixit`) is in
the tree by inheritance. The local measurements show dxc.exe exposes neither
`-fixit` nor `-Xclang`, so there is no way to reach it from this repo's driver
-- but that is an argument about wiring, and wiring claims are worth checking
against a build where the same code IS wired up.

Compiler Explorer hosts `hlsl_clang_trunk`: llvm-project's clang in DXC driver
mode, which does have `-Xclang`. Four cases, run through triage.ce_compile so
the transport is the same one `triage.py godbolt` uses:

  1. repro.hlsl + -Xclang -fixit        does FixItAction run at all?
  2. control-generic-fixit.hlsl + same  a recoverable error whose fix-it clang
                                        can actually apply -- end to end
  3. CONTROL: case 2 without the flag   the FIX-IT lines must NOT appear, or
                                        they are not evidence the flag did
                                        anything
  4. CONTROL: dxc_trunk, same flags     the fork rejects the spelling outright

Case 3 is the load-bearing one. Every conclusion here rests on reading the
string "FIX-IT" out of a diagnostic stream, so a run that must not contain it
is what makes the runs that do contain it mean something.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..",
                                                "scripts")))
import triage  # noqa: E402

OUT = os.path.join(HERE, "manual-case-clang-fixit.txt")
BASE = "-T ps_6_0 -E main -HV 2021"
FIXIT = BASE + " -Xclang -fixit"

# Compiler Explorer returns colourised diagnostics. `triage.py godbolt` keeps
# the raw stream in its own verify file; here the escapes are stripped, so a
# line quoted out of this file into a comment is the line that is in this
# file. Only SGR sequences are removed -- no text is touched.
ANSI = re.compile(r"\x1b\[[0-9;]*m")

CASES = [
    ("clang-repro", "hlsl_clang_trunk", "repro.hlsl", FIXIT,
     "does the fix-it rewriter run on the issue's own repro?"),
    ("clang-applies", "hlsl_clang_trunk", "control-generic-fixit.hlsl", FIXIT,
     "a fix-it clang can actually apply, end to end"),
    ("clang-control", "hlsl_clang_trunk", "control-generic-fixit.hlsl", BASE,
     "CONTROL: same file, no -fixit -- must show no FIX-IT lines"),
    ("dxc-control", "dxc_trunk", "control-generic-fixit.hlsl", FIXIT,
     "CONTROL: the fork does not have the spelling at all"),
]

MARKER = "FIX-IT"


def main():
    lines = [
        "Issue 4721 -- reachability of clang's fix-it rewriter, measured on",
        "Compiler Explorer (Linux release builds).",
        "",
        "Generated by probe-clang-fixit.py. CE corroborates the local Debug",
        "build; it never overrules it. ANSI colour escapes are stripped so",
        "these lines can be quoted exactly as they appear here.",
        "",
    ]
    seen = {}
    for label, cid, src, args, why in CASES:
        with open(os.path.join(HERE, src), encoding="utf-8") as f:
            source = f.read()
        rc, text, crashed = triage.ce_compile(source, cid, args)
        text = ANSI.sub("", triage.redact_paths(text))
        seen[label] = MARKER in text
        lines += [
            "=" * 74,
            f"# case:     {label}   ({why})",
            f"# compiler: {cid}",
            f"# source:   {src}",
            f"# args:     {args}",
            f"# exit:     {rc}{'  CRASH' if crashed else ''}",
            f"# contains {MARKER!r}: {seen[label]}",
            "",
            text.strip() or "(no output)",
            "",
        ]

    discriminates = seen["clang-repro"] and not seen["clang-control"]
    findings = [
        "",
        "FINDINGS",
        "",
        f"clang-fixit-4721: -Xclang -fixit is honoured by hlsl_clang_trunk "
        f"(rewriter announces itself)={seen['clang-repro']} "
        f"{'PASS' if seen['clang-repro'] else 'PARSE-WARNING'}",
        f"clang-fixit-4721: control without the flag stays silent="
        f"{not seen['clang-control']} "
        f"{'PASS' if not seen['clang-control'] else 'FAIL -- the marker is '
                                                    'not evidence of the '
                                                    'flag'}",
        f"clang-fixit-4721: marker discriminates={discriminates} "
        f"{'PASS' if discriminates else 'FAIL'}",
        f"clang-fixit-4721: dxc_trunk given the same flags="
        f"{'rejects them' if not seen['dxc-control'] else 'UNEXPECTED'}",
        "",
        "The rewriter is not missing from the lineage. It is missing from",
        "this fork's driver surface.",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines + findings) + "\n")
    print("\n".join(findings))


if __name__ == "__main__":
    main()
