"""Issue 4721 -- release matrix for the three questions the issue asks.

Every row runs, against one compiler binary:

  (a) the requested flag                -T ps_6_0 -E main -HV 2021 -fixit repro.hlsl
  (b) the same compile without it       -T ps_6_0 -E main -HV 2021 repro.hlsl
  (c) a probe-validity control          -T ps_6_0 -E main -HV 2021 control-hlsl2021.hlsl
  (d) does the suggestion compile?      -T ps_6_0 -E main -HV 2021 control-fixed.hlsl
  (e) (only when (d) fails) the same with -Vd

(c) is what makes (b) interpretable. A release that predates HLSL 2021 cannot
express the repro at all, so "no fix-it hint was printed" says nothing about
whether it renders fix-it hints -- it says the input never reached Sema. Only
a release that compiles (c) is valid evidence about (b). `triage.py classify`
cannot make that distinction here, because the capture's FIRST feature-absence
marker is the `Unknown argument: '-fixit'` from line (a), which this issue's
own predicate quotes verbatim -- so the demotion is (correctly) suppressed and
an unprobeable release still scores a plain no-repro.

(c) was originally control-fixed.hlsl, and that was wrong: it failed on
v1.7.2207..v1.8.2407 for a reason unrelated to HLSL 2021 availability, which
would have mislabelled eight probeable releases as unprobeable. It is kept as
its own column (d) because what it actually measures is worth knowing --
whether the replacement dxc suggests is one the same dxc can compile.

(a) is run against a COPY of the repro in a scratch directory, and the copy is
hashed before and after. If any build ever did accept -fixit, it would rewrite
its input in place -- the probe would destroy its own evidence, and a later
reader would find a repro that no longer reproduces. The before/after hashes
are also the positive form of the finding: the file is untouched everywhere.

Commands are echoed with subprocess.list2cmdline, so the transcript is what
ran rather than an assertion about what ran.
"""
import hashlib
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..",
                                                "scripts")))
import triage  # noqa: E402

SCRATCH = os.path.join(HERE, "scratch-matrix")
OUT = os.path.join(HERE, "manual-case-release-matrix.txt")

HINT_DIAG = ("operands for short-circuiting logical binary operator must be "
             "scalar, for non-scalar types use 'and'")
HINT_TEXT = "and(a, b)"
FLAG_REJECTED = "Unknown argument: '-fixit'"


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def run(exe, args, cwd):
    argv = [exe] + args
    try:
        p = subprocess.run(argv, cwd=cwd, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=180)
        rc, text = p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired as e:
        rc, text = "TIMEOUT", (e.stdout or "") + (e.stderr or "")
    return rc, triage.redact_paths(text), triage.redact_paths(
        subprocess.list2cmdline(argv))


def compilers():
    """(label, exe) for every stable cached release, oldest first, then main.

    Prereleases are excluded: history boundaries are stable-release boundaries
    by policy, and this issue names no prerelease.
    """
    rows = triage.con().execute(
        "SELECT tag, build_date, cached_path, prerelease FROM releases "
        "WHERE cached_path IS NOT NULL ORDER BY build_date").fetchall()
    out, skipped = [], []
    for r in rows:
        if r["prerelease"]:
            skipped.append(r["tag"])
            continue
        out.append((r["tag"], r["cached_path"]))
    return out, skipped


def main():
    if os.path.isdir(SCRATCH):
        shutil.rmtree(SCRATCH)
    os.makedirs(SCRATCH)
    for f in ("repro.hlsl", "control-fixed.hlsl", "control-hlsl2021.hlsl"):
        shutil.copy2(os.path.join(HERE, f), os.path.join(SCRATCH, f))

    rows, skipped = compilers()
    gt = triage.con().execute(
        "SELECT exe_path FROM compilers WHERE id='main-debug'").fetchone()
    rows.append(("main-debug", gt["exe_path"]))

    lines = [
        "Issue 4721 -- does any shipped dxc accept -fixit, and since when has",
        "DXC printed the fix-it hint it will not apply?",
        "",
        "Generated by release-matrix.py. Every command below is echoed exactly",
        "as executed. Prereleases excluded: " + (", ".join(skipped) or "none"),
        "",
    ]
    table = []
    hint_seen = control_ok = sugg_ok = sugg_vd_fails = 0
    for tag, exe in rows:
        if not exe or not os.path.isfile(exe):
            table.append((tag, "MISSING", "-", "-", "-", "-", "-"))
            lines.append(f"### {tag}: binary not cached at the recorded path")
            continue
        before = sha256(os.path.join(SCRATCH, "repro.hlsl"))
        rc_a, txt_a, cmd_a = run(exe, ["-T", "ps_6_0", "-E", "main", "-HV",
                                       "2021", "-fixit", "repro.hlsl"],
                                 SCRATCH)
        after = sha256(os.path.join(SCRATCH, "repro.hlsl"))
        rc_b, txt_b, cmd_b = run(exe, ["-T", "ps_6_0", "-E", "main", "-HV",
                                       "2021", "repro.hlsl"], SCRATCH)
        rc_c, txt_c, cmd_c = run(exe, ["-T", "ps_6_0", "-E", "main", "-HV",
                                       "2021", "control-hlsl2021.hlsl"],
                                 SCRATCH)
        rc_d, txt_d, cmd_d = run(exe, ["-T", "ps_6_0", "-E", "main", "-HV",
                                       "2021", "control-fixed.hlsl"], SCRATCH)
        # When (d) fails, re-run it with validation disabled. "error:
        # validation errors" on its own is ambiguous between a codegen bug and
        # a validator/signing mismatch in a cached release; -Vd tells those
        # apart, and the answer is only interesting because it is captured.
        rc_e, txt_e, cmd_e = (None, "", "")
        if rc_d != 0:
            rc_e, txt_e, cmd_e = run(exe, ["-T", "ps_6_0", "-E", "main",
                                           "-HV", "2021", "-Vd",
                                           "control-fixed.hlsl"], SCRATCH)

        flag = "rejected" if FLAG_REJECTED in txt_a else "NOT-REJECTED"
        hint = "hint" if (HINT_DIAG in txt_b and HINT_TEXT in txt_b) else "-"
        ctrl = "probeable" if rc_c == 0 else "no-HLSL-2021"
        sugg = "compiles" if rc_d == 0 else "FAILS"
        rewrote = "unchanged" if before == after else "REWRITTEN"
        hint_seen += hint == "hint"
        control_ok += ctrl == "probeable"
        sugg_ok += sugg == "compiles"
        if rc_d != 0 and rc_e not in (0, None):
            sugg_vd_fails += 1
        table.append((tag, flag, hint, ctrl, sugg, rewrote, str(rc_a)))

        def head(txt, rc, n=2):
            if rc == 0:
                return "(compiled)"
            got = [ln for ln in txt.strip().splitlines() if ln.strip()][:n]
            return "\n".join(got) or "(no output)"

        lines += [
            f"### {tag}",
            f"$ {cmd_a}",
            f"[exit] {rc_a}",
            (txt_a.strip() or "(no output)"),
            f"[repro.hlsl sha256/16 before] {before}",
            f"[repro.hlsl sha256/16 after ] {after}",
            "",
            f"$ {cmd_b}",
            f"[exit] {rc_b}",
            (txt_b.strip() or "(no output)"),
            "",
            f"$ {cmd_c}   <- (c) probe-validity control",
            f"[exit] {rc_c}",
            head(txt_c, rc_c),
            "",
            f"$ {cmd_d}   <- (d) does dxc's own suggestion compile?",
            f"[exit] {rc_d}",
            head(txt_d, rc_d),
            "",
        ]
        if rc_e is not None:
            lines += [
                f"$ {cmd_e}   <- (e) same, validation disabled",
                f"[exit] {rc_e}",
                head(txt_e, rc_e),
                "",
            ]

    width = max(len(t[0]) for t in table)
    summary = ["", "SUMMARY", "",
               f"{'build'.ljust(width)}  -fixit        hint  (c) probeable "
               f"  (d) suggestion  repro.hlsl  exit(a)",
               f"{'-' * width}  ------------  ----  --------------"
               f"  --------------  ----------  -------"]
    for tag, flag, hint, ctrl, sugg, rewrote, rc in table:
        summary.append(f"{tag.ljust(width)}  {flag.ljust(12)}  "
                       f"{hint.ljust(4)}  {ctrl.ljust(14)}  {sugg.ljust(14)}  "
                       f"{rewrote.ljust(10)}  {rc}")

    # Self-test. A reader must be able to tell "the instrument found nothing"
    # from "the instrument is broken", and both look like an empty column.
    selftest = []
    selftest.append(f"matrix-4721: rows={len(table)} "
                    f"{'PASS' if len(table) >= 10 else 'PARSE-WARNING'}")
    selftest.append(f"matrix-4721: builds that accept -HV 2021 (c)="
                    f"{control_ok} "
                    f"{'PASS' if control_ok else 'PARSE-WARNING'}")
    selftest.append(f"matrix-4721: builds that printed the fix-it hint="
                    f"{hint_seen} "
                    f"{'PASS' if hint_seen else 'PARSE-WARNING'}")
    selftest.append(f"matrix-4721: builds that compile the suggestion (d)="
                    f"{sugg_ok} "
                    f"{'PASS' if sugg_ok else 'PARSE-WARNING'}")
    selftest.append(f"matrix-4721: builds where (d) still fails with "
                    f"validation disabled (e)={sugg_vd_fails} -- these are "
                    f"the compiler refusing its own output, not a validator "
                    f"or signing mismatch")
    selftest.append("matrix-4721: read hint=- ONLY on a (c)=probeable row as "
                    "a real absence; hint=- with (c)=no-HLSL-2021 is an "
                    "unprobeable build, not evidence")
    selftest.append("matrix-4721: the same caveat applies to (d): on the four "
                    "no-HLSL-2021 rows it FAILS for the same argument-parsing "
                    "reason, not because of the suggested replacement")
    disagree = sum(1 for t in table if (t[3] == "probeable") != (t[4] ==
                                                                "compiles"))
    selftest.append(f"matrix-4721: rows where (c) and (d) disagree={disagree} "
                    f"{'PASS' if disagree else 'PARSE-WARNING'} -- the reason "
                    "they are separate columns; (d) is not a statement about "
                    "HLSL 2021 availability")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines + summary + [""] + selftest) + "\n")
    print("\n".join(summary + [""] + selftest))
    shutil.rmtree(SCRATCH)


if __name__ == "__main__":
    main()
