"""#3362: signature-packing matrix across stages and packing strategies.

Writes manual-case-configurations.txt.  Every command is echoed with
subprocess.list2cmdline(argv), so the transcript is exactly what ran rather than
a transcription of it.  The compiler, the spelling of the packing flag and the output filename all come
from environment variables, so the same script can be pointed at a release
build -- v1.4.1907 rejects `-pack-optimized` and wants `-pack_optimized`.

    set DXC=<repo>\\build\\Debug\\bin\\dxc.exe
    python run-matrix.py

    set DXC=<cache>\\compilers\\releases\\v1.4.1907\\dxc.exe
    set PACK3362=-pack_optimized
    set OUT3362=manual-case-v1.4.1907-underscore.txt
    python run-matrix.py
"""

import os
import re
import subprocess
import sys

DXC = os.environ.get("DXC", r"<repo>\build\Debug\bin\dxc.exe")
PACK = os.environ.get("PACK3362", "-pack-optimized")
OUT = os.environ.get("OUT3362", "manual-case-configurations.txt")
HERE = os.path.dirname(os.path.abspath(__file__))
# <repo>/.github/skills/dxc-issue-triage/data/issues/3362 -> <repo>
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(SKILL_DIR)))

CASES = [
    ("repro.hlsl        DS  optimized", "-T ds_6_0 -E DSMain " + PACK),
    ("repro.hlsl        DS  default  ", "-T ds_6_0 -E DSMain"),
    ("repro.hlsl        PS  optimized", "-T ps_6_0 -E PSMain " + PACK),
    ("repro.hlsl        PS  default  ", "-T ps_6_0 -E PSMain"),
    ("control-subset-ps.hlsl DS  optimized", "-T ds_6_0 -E DSMain " + PACK),
    ("control-subset-ps.hlsl PS  optimized", "-T ps_6_0 -E PSMain " + PACK),
    ("control-subset-ps.hlsl PS  default  ", "-T ps_6_0 -E PSMain"),
    ("control-pipeline.hlsl VS  optimized", "-T vs_6_0 -E VSMain " + PACK),
    ("control-pipeline.hlsl HS  optimized", "-T hs_6_0 -E HSMain " + PACK),
    ("control-pipeline.hlsl DS  optimized", "-T ds_6_0 -E DSMain " + PACK),
    ("control-pipeline.hlsl PS  optimized", "-T ps_6_0 -E PSMain " + PACK),
]

# Releases before ~v1.5 print "Patch Constant signature signature:" -- the
# duplicated word is in the reporter's own 2021 attachment, and a header regex
# that misses it silently drops the patch-constant table from the transcript.
SIG_HEAD = re.compile(r"^;\s*(Input|Output|Patch Constant)( signature)? signature:")


def signature_tables(text):
    """Keep only the leading comment block's signature tables."""
    out, emit = [], False
    for line in text.splitlines():
        if SIG_HEAD.match(line):
            emit = True
            out.append(line)
            continue
        if emit:
            if not line.startswith(";"):
                emit = False
                continue
            if line.strip() == ";":
                if out and out[-1].strip() == ";":
                    emit = False
                    continue
            out.append(line)
    return "\n".join(out)


def display(path):
    for base, token in ((REPO, "<repo>"),):
        if base and base in path:
            return path.replace(base, token)
    return path


def main():
    chunks = [
        "# #3362 signature-packing matrix -- generated by run-matrix.py",
        "# compiler: %s" % display(DXC),
        "# packing flag spelling: %s" % PACK,
        "",
    ]
    version = subprocess.run([DXC, "--version"], capture_output=True, text=True)
    chunks.append("$ " + subprocess.list2cmdline([display(DXC), "--version"]))
    chunks.append(version.stdout.strip() + version.stderr.strip())
    chunks.append("")
    for name, flags in CASES:
        src = name.split()[0]
        argv = [DXC] + flags.split() + ["-Qstrip_debug", "-Qstrip_reflect", src]
        p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        shown = [display(DXC)] + flags.split() + \
            ["-Qstrip_debug", "-Qstrip_reflect", src]
        chunks.append("=" * 78)
        chunks.append("## " + name)
        chunks.append("$ " + subprocess.list2cmdline(shown))
        chunks.append("[exit] %d" % p.returncode)
        tables = signature_tables(p.stdout)
        if not tables:
            chunks.append("MATRIX-3362: PARSE-WARNING: 0 signature tables found")
            chunks.append(p.stdout.strip())
            chunks.append(p.stderr.strip())
        else:
            # Self-consistency: a hull or domain shader that reports no
            # patch-constant table means the reader lost it, not that the
            # shader has none.  Say so loudly rather than letting a silent
            # omission read as evidence.
            if (" HS " in name or " DS " in name) \
                    and "Patch Constant" not in tables:
                chunks.append("MATRIX-3362: PARSE-WARNING: no patch-constant "
                              "table parsed for a tessellation stage")
            chunks.append(tables)
        chunks.append("")
    text = "\n".join(chunks) + "\n"
    with open(os.path.join(HERE, OUT), "w", encoding="utf-8") as f:
        f.write(text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
