"""Per-release matrix for issue 4501.

Question this answers, which `bisect` alone cannot: the four oldest stable
releases cannot run the repro's `-fspv-debug=vulkan-with-source` command, so they
are unmeasurable under `match.json`. Were they unmeasurable because the
NonSemantic.Shader.DebugInfo.100 instruction set did not exist in them yet, or
because something unrelated in the repro was rejected? The discriminator is to
run *every* debug-info mode each release offers and record which extended
instruction set it imports, plus whether `DebugBuildIdentifier` /
`DebugStoragePath` appear anywhere in any of them.

It also serves as the per-release positive control the skill requires: every
release must produce SPIR-V in at least one mode, or the binary is not working
and its silence proves nothing.

Reads the release table for `cached_path` (both the downloaded cache and the
test-seeded trees), echoes every command with `subprocess.list2cmdline`, and
writes `manual-case-release-matrix.txt`.

    python measure-releases.py

Every path is emitted through `display_path`, so the committed output is
machine-independent.
"""
import os
import re
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
REPO = os.path.abspath(os.path.join(SKILL, "..", "..", ".."))
CACHE = os.environ.get("DXC_TRIAGE_CACHE") or os.path.join(SKILL, ".cache")
DB = os.path.join(CACHE, "triage.db")

MODES = [
    ("vulkan-with-source", ["-fspv-debug=vulkan-with-source"]),
    ("vulkan", ["-fspv-debug=vulkan"]),
    ("rich-with-source", ["-fspv-debug=rich-with-source"]),
    ("rich", ["-fspv-debug=rich"]),
    ("line", ["-fspv-debug=line"]),
    ("Zi", ["-Zi"]),
]
BASE = ["-T", "ps_6_0", "-E", "main", "-spirv"]
SHADER = "repro.hlsl"
WANTED = ("DebugBuildIdentifier", "DebugStoragePath")


def display_path(path):
    """Machine-independent spelling, matching triage.py's display_exe tokens."""
    p = os.path.abspath(path)
    for base, token in ((CACHE, "<cache>"), (SKILL + os.sep + "data", "<triage>"),
                        (REPO, "<repo>")):
        try:
            rel = os.path.relpath(p, base)
        except ValueError:
            continue
        if not rel.startswith(os.pardir):
            return f"{token}/" + rel.replace(os.sep, "/")
    return p.replace(os.sep, "/")


def run(exe, args, out):
    argv = [exe] + args
    out.append("$ dxc " + subprocess.list2cmdline(args))
    try:
        p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                           timeout=300, errors="replace")
        rc, text = p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired:
        rc, text = None, "<TIMEOUT>"
    out.append(f"[exit] {rc if rc is None else hex(rc & 0xFFFFFFFF)}")
    return rc, text


def summarise(text):
    """One line describing what the module contains, or why there is none.

    Careful: "no extended instruction set imported" is NOT the same as "no
    SPIR-V produced" -- `-fspv-debug=line` and `-Zi` emit a perfectly good
    module with OpLine and no OpExtInstImport at all. Conflating the two is the
    #2923 broken-reader trap: the harness returns "nothing here" and "nothing
    matched" through the same channel, and both arms then look clean.
    """
    imports = re.findall(r'OpExtInstImport\s+"([^"]+)"', text)
    dbg = sorted(set(re.findall(r"OpExtInst\s+%\w+\s+%\w+\s+(Debug\w+)", text)))
    produced_spirv = "; SPIR-V" in text and "OpCapability" in text
    if not produced_spirv:
        first = next((ln.strip() for ln in text.splitlines()
                      if ln.strip() and not ln.startswith(("---", "$", "["))), "")
        return f"no SPIR-V produced: {first[:110]}"
    return (f"SPIR-V produced; imports={imports or ['(none)']} "
            f"debug-instructions={len(dbg)} kinds"
            + (f" ({','.join(dbg)})" if dbg else ""))


def main():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, build_date, prerelease, cached_path FROM releases "
        "WHERE cached_path IS NOT NULL ORDER BY build_date").fetchall()

    out = []
    out.append("# Issue 4501 -- per-release debug-info mode matrix")
    out.append("# generated by measure-releases.py; re-run it to re-derive this file")
    out.append(f"# shader: {SHADER}")
    out.append("#")
    out.append("# For each release: which -fspv-debug modes it accepts, which extended")
    out.append("# instruction set the resulting module imports, and whether")
    out.append("# DebugBuildIdentifier / DebugStoragePath appear ANYWHERE in any mode.")
    out.append("")

    summary = []
    seen_any_wanted = False
    for r in rows:
        exe = r["cached_path"]
        if not exe or not os.path.isfile(exe):
            continue
        tag = r["tag"]
        kind = "prerelease" if r["prerelease"] else "stable"
        out.append("=" * 78)
        out.append(f"== {tag}  ({r['build_date']}, {kind})")
        out.append(f"== exe: {display_path(exe)}")
        rc, ver = run(exe, ["--version"], out)
        out.append((ver or "").strip())
        out.append("")

        modes_ok, wanted_here, sets_here = [], [], []
        for name, flags in MODES:
            rc, text = run(exe, BASE + flags + [SHADER], out)
            out.append("   " + summarise(text))
            if rc == 0:
                modes_ok.append(name)
            for s in re.findall(r'OpExtInstImport\s+"([^"]+)"', text):
                if s not in sets_here:
                    sets_here.append(s)
            for w in WANTED:
                if w in text:
                    wanted_here.append(f"{w}@{name}")
                    seen_any_wanted = True
            out.append("")

        # Does this release accept -Fd together with -spirv?
        rc, text = run(exe, BASE + ["-fspv-debug=vulkan-with-source", "-Fd",
                                    "spirv-pdb" + os.sep, "-Fo", "out.spv",
                                    SHADER], out)
        fd = "rejected" if rc not in (0, None) else "accepted"
        first = next((ln.strip() for ln in text.splitlines()
                      if ln.strip() and not ln.startswith(("---", "$", "["))), "")
        out.append(f"   -Fd with -spirv: {fd}: {first[:110]}")
        out.append("")
        if os.path.isfile(os.path.join(HERE, "out.spv")):
            os.remove(os.path.join(HERE, "out.spv"))

        summary.append((tag, kind, modes_ok, wanted_here, fd, sets_here))

    out.append("=" * 78)
    out.append("SUMMARY")
    out.append(f"{'release':<16}{'kind':<12}{'-Fd+spirv':<11}"
               f"{'debug extinst sets emitted':<56}requested-instructions")
    for tag, kind, modes_ok, wanted_here, fd, sets_here in summary:
        out.append(f"{tag:<16}{kind:<12}{fd:<11}"
                   f"{','.join(sets_here) or '(none)':<56}"
                   f"{','.join(wanted_here) or 'none'}")
    out.append("")
    out.append(f"{'release':<16}accepted -fspv-debug modes")
    for tag, kind, modes_ok, wanted_here, fd, sets_here in summary:
        out.append(f"{tag:<16}{','.join(modes_ok) or '(none)'}")
    out.append("")
    # Self-consistency: a matrix that parsed nothing must say so loudly rather
    # than returning a clean-looking absence (SKILL.md, #2923).
    parsed = sum(1 for _, _, m, _, _, _ in summary if m)
    out.append(f"SELFTEST-4501: releases producing SPIR-V in >=1 mode: "
               f"{parsed}/{len(summary)}")
    out.append(f"SELFTEST-4501: releases parsed: {len(summary)} "
               f"({'PASS' if len(summary) >= 15 and parsed >= 15 else 'PARSE-WARNING'})")
    out.append(f"RESULT-4501: requested instructions seen anywhere: "
               f"{'YES' if seen_any_wanted else 'NO'}")

    path = os.path.join(HERE, "manual-case-release-matrix.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {display_path(path)}")
    print(out[-3])
    print(out[-2])
    print(out[-1])


if __name__ == "__main__":
    sys.exit(main())
