"""Manual release-history matrix for issue #5423.

Runs each cached release's dxr.exe against repro.hlsl with the reporter's exact
command (`-D float4=0 -E PSMain repro.hlsl`) and records whether the `float4` token
was substituted (bug fixed / -D honored) or left verbatim (bug present / -D ignored),
or whether the rewrite errored out instead.

Every release binary here was already downloaded by a prior batch (issue #4273) under
.cache/rw4273/<tag>/dxr.exe -- no new download, no build. Generated, not hand-run: this
script prints the exact argv it executes (subprocess.list2cmdline) into the capture.
"""
import subprocess
import sys
from pathlib import Path

ISSUE_DIR = Path(__file__).resolve().parent
SKILL_DIR = ISSUE_DIR.parents[2]
RW_CACHE = SKILL_DIR / ".cache" / "rw4273"
REPRO = ISSUE_DIR / "repro.hlsl"


def tokenise(text):
    """Machine-independent spelling, matching triage.py's <cache>/<repo> convention.

    Cache-root replacement runs first since .cache/ lives under the repo root and
    would otherwise be partially rewritten by the repo-root substitution.
    """
    cache_dir = str(SKILL_DIR / ".cache")
    repo_root = str(SKILL_DIR.parents[2])
    for base in (cache_dir, repo_root):
        token = "<cache>" if base == cache_dir else "<repo>"
        text = text.replace(base.replace("/", "\\"), token)
        text = text.replace(base.replace("\\", "/"), token)
    return text.replace("\\", "/")

RELEASES = [
    "v1.4.1907", "v1.5.2010", "v1.6.2104", "v1.6.2106", "v1.6.2112",
    "v1.7.2207", "v1.7.2212", "v1.7.2212.1", "v1.7.2308",
    "v1.8.2403", "v1.8.2403.1", "v1.8.2403.2", "v1.8.2405", "v1.8.2407",
    "v1.8.2502", "v1.8.2505", "v1.8.2505.1",
    "v1.9.2602", "v1.9.2602.24", "v1.9.2607",
]


def run(exe, args):
    argv = [str(exe)] + args
    proc = subprocess.run(argv, capture_output=True, text=True, cwd=ISSUE_DIR)
    return argv, proc


def classify(stdout, stderr, exit_code):
    combined = stdout + stderr
    if exit_code != 0:
        return "error"
    if "float4 position" in combined or "float4 color" in combined or "float4 PSMain" in combined:
        return "ignored (-D not applied, bug present)"
    if "0 position" in combined or "0 color" in combined:
        return "applied (-D honored, bug fixed)"
    return "unrecognised output shape"


def main():
    out_lines = []
    out_lines.append("# generated by manual-case-release-history.py")
    out_lines.append("# repro: repro.hlsl, cmd: -D float4=0 -E PSMain repro.hlsl (dxr.exe)")
    out_lines.append("")
    for tag in RELEASES:
        exe = RW_CACHE / tag / "dxr.exe"
        if not exe.exists():
            out_lines.append(f"{tag}: NO dxr.exe in cache, skipped")
            continue
        ver_argv, ver_proc = run(exe, ["--version"])
        version = (ver_proc.stdout or ver_proc.stderr).strip().splitlines()[0] if (ver_proc.stdout or ver_proc.stderr) else "<no output>"
        argv, proc = run(exe, ["-D", "float4=0", "-E", "PSMain", "repro.hlsl"])
        verdict = classify(proc.stdout, proc.stderr, proc.returncode)
        out_lines.append(f"## {tag}")
        out_lines.append(f"version: {version}")
        out_lines.append(f"$ {subprocess.list2cmdline(argv)}")
        out_lines.append(f"[exit] {proc.returncode}")
        out_lines.append("--- stdout ---")
        out_lines.append(proc.stdout.rstrip())
        out_lines.append("--- stderr ---")
        out_lines.append(proc.stderr.rstrip())
        out_lines.append(f"[verdict] {verdict}")
        out_lines.append("")
        print(f"{tag}: exit={proc.returncode} -> {verdict}")

    (ISSUE_DIR / "manual-case-release-history.txt").write_text(
        tokenise("\n".join(out_lines)), encoding="utf-8")


if __name__ == "__main__":
    main()
