"""Per-release control matrix for issue #3414.

`bisect` probes only the primary repro. SKILL.md requires the feature-presence
control to run on *every* probed release, not just on ground truth, and this
issue additionally needs the reporter's own working variant measured on the
releases where the repro reproduces -- that pair is what makes the predicate a
measurement of the reported distinction rather than of "any raytracing shader".

Writes manual-case-release-matrix.txt.  Every command is printed exactly as
executed (subprocess.list2cmdline of the real argv), so the file can be
re-derived rather than trusted.  Compiler paths come from the triage database,
never from a hardcoded machine path; they are printed with the repository root
redacted to <repo>.
"""
import json
import os
import re
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
REPO_ROOT = os.path.abspath(os.path.join(SKILL_DIR, "..", "..", ".."))
DB = os.path.join(os.environ.get("DXC_TRIAGE_CACHE", os.path.join(SKILL_DIR, ".cache")),
                  "triage.db")

SHADERS = ["repro.hlsl", "control-workaround.hlsl",
           "control-increment-after-trace.hlsl", "control-hello.hlsl"]
ARGS = ["-T", "lib_6_3"]

TRACE_RE = re.compile(r"call void @dx\.op\.traceRay[^\n]*?(%struct\.Payload\* [^)]*)\)")
DEFINE_RE = re.compile(r"define void @[^\n]*?\((%struct\.Payload\*[^,]*),")


def redact(p):
    return p.replace(REPO_ROOT, "<repo>")


def compilers():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    out = []
    row = con.execute("SELECT exe_path FROM compilers WHERE id='main-debug'").fetchone()
    out.append(("main-debug", row["exe_path"]))
    for r in con.execute("SELECT tag, cached_path FROM releases "
                         "WHERE bisectable=1 AND cached_path IS NOT NULL "
                         "ORDER BY build_date"):
        out.append((r["tag"], r["cached_path"]))
    con.close()
    return out


def score(text):
    """Score the issue's own match.json against captured output."""
    pats = [c["value"] for c in json.load(open(os.path.join(HERE, "match.json"),
                                              encoding="utf-8"))["value"]]
    return all(re.search(p, text, re.MULTILINE) for p in pats)


def main():
    lines = []
    w = lines.append
    w("# Per-release control matrix for #3414 -- generated by measure-controls.py")
    w("# 'payload param' is the entry function's inout payload parameter;")
    w("# 'traceRay arg' is the payload operand of the dx.op.traceRay call.")
    w("# They are the SAME value exactly when the symptom is present.")
    w("")
    for tag, exe in compilers():
        w(f"=== {tag}  ({redact(exe)}) ===")
        for shader in SHADERS:
            argv = [exe] + ARGS + [shader]
            w("$ " + subprocess.list2cmdline([redact(exe)] + ARGS + [shader]))
            p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                               errors="replace", timeout=300)
            text = (p.stdout or "") + (p.stderr or "")
            trace = TRACE_RE.search(text)
            defn = DEFINE_RE.search(text)
            if not trace:
                w(f"  exit={p.returncode:<4} NO dx.op.traceRay IN OUTPUT -- "
                  f"first line: {text.strip().splitlines()[0] if text.strip() else '(empty)'}")
            else:
                w(f"  exit={p.returncode:<4} payload param [{defn.group(1) if defn else 'n/a'}]"
                  f"  traceRay arg [{trace.group(1)}]")
            w(f"  #3414 predicate: {'MATCH (symptom present)' if score(text) else 'no-match'}")
        w("")
    out = os.path.join(HERE, "manual-case-release-matrix.txt")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"written: {redact(out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
