"""Capture the Debug-build assert chain for issue 4648 through cdb.

Written as a script rather than a transcribed command line because a transcribed
command is an assertion about what happened that nobody checks.
`subprocess.list2cmdline(argv)` prints exactly what was executed, and everything
written out is passed through `triage.redact_paths()`, so no machine-local
absolute path reaches the committed capture.

Two things about the incantation matter:

* the assert arrives as a C++ exception (exit 0xE0000001), not as a trap, so the
  debugger must break on the exception itself: `sxe -c "kb N; gh" e0000001`;
* `gh` ("go handled") continues past the assert, which emulates what an NDEBUG
  build would have done. That is how a Debug binary can show the *Release*
  failure mode the reporter saw without building Release.

Usage (from this directory):
    python capture-assert-stack.py > manual-case-assert-stack.txt
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "scripts"))
import triage  # noqa: E402

DXC = os.path.join(triage.REPO_ROOT, "build", "Debug", "bin", "dxc.exe")
CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"

CASES = [
    ("repro.hlsl", "unsigned int16_t at global scope -- the issue body"),
    ("case-user-typedef.hlsl",
     "unsigned applied to a plain user typedef of int -- no 16-bit type involved"),
]

# A full cdb dump is noise: module loads, symbol paths and the extension gallery
# banner say nothing about the defect. Keep the assert text, the source location
# it names, the exception announcements, and the stack frames.
HEADLINE = re.compile(
    r"^(?:Error: assert\(|File:|Func:)"
    r"|^\S*[/\\][\w./\\+-]+\.(?:h|cpp)\(\d+\)$"
    r"|^\(\w+\.\w+\): .*- code [0-9a-f]{8}")
FRAME = re.compile(r":\s+(\w+![\w:<>~,\s*&]+\+0x[0-9a-f]+)\s*$")


def emit(line):
    stripped = line.rstrip()
    if not stripped:
        return None
    m = FRAME.search(stripped)
    if m:
        # Drop the raw addresses; only the symbol carries meaning, and the
        # addresses differ on every run, which would make the file look unstable.
        return "    " + m.group(1)
    if HEADLINE.search(stripped):
        return stripped
    return None


def run(shader, frames):
    argv = [CDB, "-c", 'sxe -c "kb %d; gh" e0000001; g; q' % frames,
            DXC, "-T", "vs_6_2", "-enable-16bit-types", shader]
    print("$ " + triage.redact_paths(subprocess.list2cmdline(argv)))
    p = subprocess.run(argv, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", cwd=HERE)
    text = triage.redact_paths(p.stdout + p.stderr)
    for line in text.splitlines():
        out = emit(line)
        if out is not None:
            print(out)
    print("[exit] 0x%08X" % (p.returncode & 0xFFFFFFFF))


def main():
    print("# issue 4648 -- Debug-build assert chain, and the access violation past it")
    print("# generated by capture-assert-stack.py, committed beside this file")
    print("# dxc: %s" % triage.display_exe(DXC))
    version = subprocess.run([DXC, "--version"], capture_output=True, text=True)
    print("# dxc --version: %s" % version.stdout.strip())
    print("# cdb breaks on the 0xE0000001 assert exception and `gh`s past it, which")
    print("# emulates NDEBUG: the trailing 0xC0000005 is the Release-build symptom.")
    print("# Trimmed to asserts, source locations, exception announcements and frames.")
    print()
    for shader, why in CASES:
        print("=" * 72)
        print("# case: %s" % shader)
        print("# %s" % why)
        print("=" * 72)
        run(shader, 8)
        print()


if __name__ == "__main__":
    main()
