#!/usr/bin/env python3
"""Compiler Explorer control matrix for #3726's Clang pane.

SKILL.md step 7: a Clang error is not evidence until a trivial control with the same
flags shows the difference does not survive. Clang's DXIL backend is incomplete, so it
fails on plenty of inputs that have nothing to do with this issue.

Runs each (source, compiler) pair through CE's compile API with IDENTICAL arguments and
prints the exact request it made plus the full response, so the table below can be
re-derived rather than trusted:

    python make-clang-control.py > manual-case-clang-control.txt

Paths come from __file__; no machine-specific path is baked in. Every source published
here comes from a public GitHub issue in a public repo.
"""
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CE = "https://godbolt.org"
ARGS = "-T cs_6_0 -E main"
COMPILERS = ["dxc_trunk", "hlsl_clang_trunk"]
SOURCES = ["control-cs-trivial.hlsl", "repro-cs.hlsl"]

# CE strips comment-only lines by default, which is exactly where DXC puts its
# resource-binding table. Keep the output faithful. Mirrors CE_FILTERS in triage.py.
FILTERS = {"execute": False, "intel": False, "demangle": False, "labels": False,
           "directives": False, "commentOnly": False, "trim": False, "binary": False}


def compile_on_ce(source_text, compiler, args):
    payload = {
        "source": source_text, "lang": "hlsl", "compiler": compiler,
        "options": {
            "userArguments": args,
            "compilerOptions": {"skipAsm": False, "executorRequest": False},
            "filters": dict(FILTERS), "tools": [], "libraries": [],
        },
        "allowStoreCodeDebug": True,
    }
    req = urllib.request.Request(
        f"{CE}/api/compiler/{compiler}/compile", data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=90) as r:
        res = json.loads(r.read().decode())
    text = "\n".join(x.get("text", "") for stream in ("stdout", "stderr")
                     for x in res.get(stream, []))
    asm = "\n".join(x.get("text", "") for x in res.get("asm", [])
                    if isinstance(x, dict))
    return res.get("code"), (text + "\n" + asm).strip()


def main():
    print("# #3726 -- Compiler Explorer control matrix for the Clang pane")
    print("#")
    print("# Generated by make-clang-control.py. Both sources get the SAME arguments on")
    print(f"# both compilers: {ARGS!r}. CE runs Linux Release builds.")
    print()
    summary = []
    for src in SOURCES:
        source_text = open(os.path.join(HERE, src), encoding="utf-8").read()
        for cid in COMPILERS:
            print("=" * 78)
            print(f"POST {CE}/api/compiler/{cid}/compile")
            print(f"  source          = {src}  ({len(source_text)} bytes, read from disk)")
            print(f"  userArguments   = {ARGS}")
            print("-" * 78)
            rc, out = compile_on_ce(source_text, cid, ARGS)
            print(f"[exit] {rc}")
            print(out if out else "(no output)")
            print()
            # Only real diagnostics. Both compilers embed the whole source in
            # module metadata (dxc in !dx.source.contents), so a bare substring
            # search for "error" matches this file's own prose, echoed back --
            # the same trap SKILL.md records for godbolt-note.txt. Require the
            # "error:" spelling and skip metadata lines.
            diags = [ln.strip() for ln in out.splitlines()
                     if "error:" in ln and not ln.lstrip().startswith("!")]
            summary.append((src, cid, rc, len(diags), diags[0] if diags else ""))
    print("=" * 78)
    print("SUMMARY")
    print(f"{'source':<26} {'compiler':<20} {'exit':>5} {'diags':>6}  first error line")
    for src, cid, rc, n, first in summary:
        print(f"{src:<26} {cid:<20} {str(rc):>5} {n:>6}  {first[:66]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
