#!/usr/bin/env python3
"""Source-level corroboration for #3726: where is `a0 = r0;` diagnosed?

An output observation says a diagnostic appeared; it does not say which layer produced
it, and in DXC the printed form is actively misleading (the DXIL back end maps LLVM debug
locations back to source, so its errors also print `file:line:col: error:`). This script
asks the tree instead, and echoes every command so the file can be re-derived rather than
trusted:

    python make-sema-absence.py > manual-case-sema-absence.txt

Repo root is derived from __file__; nothing machine-specific is baked in. Each ABSENCE
check is paired with a known-positive on the same file with the same tool, because a
search that silently matches nothing looks identical to a clean result.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, *([".."] * 6)))

CHECKS = [
    ("POSITIVE CONTROL: Sema's HLSL diagnostics exist and this search finds them.",
     ["git", "grep", "-c", "err_hlsl", "--",
      "tools/clang/include/clang/Basic/DiagnosticSemaKinds.td"]),
    ("ABSENCE: every Sema diagnostic whose name mentions a resource. None is about\n"
     "assigning one. (err_hlsl_invalid_resource_type_on_intrinsic is about intrinsic\n"
     "arguments; the ..._resource_heap... one is about `auto` on a descriptor heap.)",
     ["git", "grep", "-n", "-i", "^def err.*resource", "--",
      "tools/clang/include/clang/Basic/DiagnosticSemaKinds.td"]),
    ("ABSENCE: no front-end *source* file mentions the message DXC actually prints,\n"
     "so it is not being routed through the front end from elsewhere. Scoped to the\n"
     "front end's own sources and headers: the same search over all of tools/clang/\n"
     "matches ~30 files, every one of them a FileCheck test asserting the back end.",
     ["git", "grep", "-l", "local resource not guaranteed", "--",
      "tools/clang/lib/", "tools/clang/include/"]),
    ("POSITIVE CONTROL for the search above: the same tool, over the same path scope,\n"
     "does find a diagnostic message the front end really does own -- so a clean\n"
     "result there means absent, not unsearched.",
     ["git", "grep", "-l", "cannot %0 from resource containing", "--",
      "tools/clang/lib/", "tools/clang/include/"]),
    ("PRESENCE: the message text lives in the DXIL back end.",
     ["git", "grep", "-n", "local resource not guaranteed", "--", "lib/"]),
    ("PRESENCE: so does the misleading first line, and its call sites -- note the\n"
     "'Most likely storing to output parameter' fallback comment.",
     ["git", "grep", "-n", "exported library functions cannot have resource",
      "--", "lib/"]),
    ("PRESENCE: the pass that reports it. LegalizeResourceUseHelper is driven by\n"
     "DxilLowerCreateHandleForLib, which runs long after code generation.",
     ["git", "grep", "-n", "class LegalizeResourceUseHelper", "--", "lib/"]),
    ("PRESENCE: the fallback that produces the library-export wording, reached for a\n"
     "store into an `out` resource parameter of a non-library shader.",
     ["git", "grep", "-n", "-A2", "Most likely storing to output parameter",
      "--", "lib/"]),
]


def run(argv):
    print("$ " + subprocess.list2cmdline(argv))
    p = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True)
    out = (p.stdout + p.stderr).rstrip()
    print(out if out else "(no output)")
    print(f"[exit] {p.returncode}"
          + ("   <-- git grep exits 1 when it finds nothing"
             if p.returncode == 1 else ""))


def main():
    print("# #3726 -- which layer owns the diagnostic, read from the source tree")
    print("# Generated by make-sema-absence.py. Run from a checkout of the commit under")
    print("# test (13730886e); repo root is derived from this file's location.")
    for title, argv in CHECKS:
        print()
        print("=" * 78)
        for ln in title.splitlines():
            print("# " + ln)
        print("-" * 78)
        run(argv)
    return 0


if __name__ == "__main__":
    sys.exit(main())
