"""Validator evidence for issue 4540.

The maintainer's 2024-10-01 comment says the validator and the DXIL spec contradict each
other. That is a separate ask from the codegen defect and needs its own measurement, because
"the validator accepts this" is unfalsifiable on its own -- a validator that was never asked
also accepts everything.

So this runs a control PAIR on every cached build, each build using its own dxc.exe (and
therefore the dxil.dll shipped beside it):

  repro.hlsl              -- the i1 groupshared module. Question: accepted?
  control-no-static.hlsl  -- the i32 groupshared module. Must be accepted.
  control-tgsm-overflow.hlsl -- 64KB of groupshared, over the 32768-byte budget. Must be
                             REJECTED (ValidationRule::SmMaxTGSMSizeOnEntry). This is the
                             clause that proves the validator's *groupshared* rules really
                             run on modules of this shape on that build.

`-Fo` is what makes dxc validate and sign the container, so the exit status of these
invocations is the validator's answer. The reported !dx.valver comes from the same module.

Every command is echoed with subprocess.list2cmdline(argv). Output is passed through
triage.redact_paths(). Containers are written to a scratch directory that is removed again.

Usage (from the skill root):
    python data/issues/4540/make-validator-case.py > data/issues/4540/manual-case-validator.txt
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
sys.path.insert(0, str(SKILL / "scripts"))
import triage  # noqa: E402

SCRATCH = HERE / "scratch-validator"
ARGS = ["-T", "cs_6_0", "-E", "main"]

CASES = [
    ("repro", "repro.hlsl", "?", "the i1 groupshared module -- the question"),
    ("no-static", "control-no-static.hlsl", "accept",
     "the i32 groupshared module -- must be accepted"),
    ("tgsm-overflow", "control-tgsm-overflow.hlsl", "reject",
     "64KB groupshared -- must be rejected, proving groupshared rules run"),
]

VALVER = re.compile(r"!dx\.valver = !\{!(\d+)\}")
MDNODE = re.compile(r"^!(\d+) = !\{i32 (\d+), i32 (\d+)\}", re.MULTILINE)


def valver_of(exe, shader):
    """Read !dx.valver out of the disassembly the same binary produces."""
    proc = subprocess.run([str(exe)] + ARGS + [shader], cwd=str(HERE),
                          capture_output=True, text=True, errors="replace", timeout=300)
    text = proc.stdout + proc.stderr
    m = VALVER.search(text)
    if not m:
        return "<no !dx.valver>"
    want = m.group(1)
    for node, major, minor in MDNODE.findall(text):
        if node == want:
            return f"{major}.{minor}"
    return "<valver node unresolved>"


def main():
    rows = triage.con().execute(
        "SELECT tag, prerelease, cached_path FROM releases "
        "WHERE cached_path IS NOT NULL ORDER BY build_date"
    ).fetchall()
    builds = [(r["tag"], "prerelease" if r["prerelease"] else "stable", r["cached_path"])
              for r in rows]
    builds.append(("main-debug", "ground-truth", triage.resolve_compiler("main-debug")))

    if SCRATCH.exists():
        shutil.rmtree(SCRATCH)
    SCRATCH.mkdir()

    out = []
    out.append("Issue 4540 -- DXIL validation of the i1 groupshared module")
    out.append("generated by make-validator-case.py; every command below was executed as shown")
    out.append("")
    for label, shader, expect, why in CASES:
        out.append(f"  {shader:<27} expect {expect:<7} {why}")
    out.append("")
    out.append("`-Fo` makes dxc validate and sign the container, so the exit status IS the")
    out.append("validator's answer. Each release validates with the dxil.dll beside its dxc.exe.")
    out.append("")

    summary = []
    try:
        for tag, kind, exe in builds:
            out.append("=" * 78)
            out.append(f"### {tag}  ({kind})   validator version (from !dx.valver): "
                       f"{valver_of(exe, 'repro.hlsl')}")
            row = {"tag": tag}
            for label, shader, expect, _why in CASES:
                fo = SCRATCH / f"{tag}-{label}.dxil"
                argv = [str(exe)] + ARGS + [shader, "-Fo", str(fo)]
                proc = subprocess.run(argv, cwd=str(HERE), capture_output=True, text=True,
                                      errors="replace", timeout=300)
                text = (proc.stdout + proc.stderr).strip()
                code = proc.returncode & 0xFFFFFFFF
                accepted = proc.returncode == 0
                verdict = "ACCEPTED" if accepted else "REJECTED"
                ok = "" if expect == "?" else (
                    "  <== AS REQUIRED" if (accepted == (expect == "accept"))
                    else "  <== CONTROL VIOLATED")
                out.append(f"$ {subprocess.list2cmdline(argv)}")
                out.append(f"  exit=0x{code:08X}  {verdict}{ok}")
                for ln in [l for l in text.splitlines() if l.strip()][:4]:
                    out.append(f"  | {ln}")
                row[label] = verdict
            out.append("")
            summary.append(row)
    finally:
        shutil.rmtree(SCRATCH, ignore_errors=True)

    out.append("=" * 78)
    out.append("SUMMARY")
    out.append("")
    hdr = f"{'build':<16} {'repro (i1 TGSM)':<17} {'no-static (i32)':<17} {'tgsm-overflow':<15}"
    out.append(hdr)
    out.append("-" * len(hdr))
    for r in summary:
        out.append(f"{r['tag']:<16} {r['repro']:<17} {r['no-static']:<17} "
                   f"{r['tgsm-overflow']:<15}")
    out.append("")
    n = len(summary)
    acc = sum(1 for r in summary if r["repro"] == "ACCEPTED")
    ctl = sum(1 for r in summary if r["tgsm-overflow"] == "REJECTED")
    out.append(f"builds measured                                  : {n}")
    out.append(f"i1 groupshared module accepted by the validator  : {acc}/{n}")
    out.append(f"groupshared-rule control correctly rejected      : {ctl}/{n}")
    out.append("")
    out.append("The second line is what makes the first line mean something: on these builds")
    out.append("the validator does police groupshared memory, and it still does not object to")
    out.append("an i1-typed groupshared global. docs/DXIL.rst:240 defines memory accesses for")
    out.append("groupshared memory as i32/f32/f64 only.")

    sys.stdout.write(triage.redact_paths("\n".join(out)) + "\n")


if __name__ == "__main__":
    main()
