"""Per-release control matrix for issue 4540.

`triage.py bisect` scores the repro on every release, but `run --shader` retargets only the
registered ground-truth compiler, so the *control* is measured on main only. That leaves the
central hazard of a wrong-code predicate unaddressed on 20 of 21 builds: a predicate that
matches everything is indistinguishable from a bug that reproduces everywhere.

This holds the two shaders fixed and varies the compiler, running BOTH on each release's own
dxc.exe with identical arguments, and prints for each build:

  * the release's own --version string, so the row proves which binary answered;
  * SELFTEST: whether a groupshared (addrspace(3)) global of any integer type was emitted at
    all -- the instrument reading. If this fails, that release is unmeasurable under the
    predicate, not fixed, and a disassembler formatting change cannot masquerade as a
    behaviour change;
  * the verbatim `addrspace(3) global ...` line from the repro (expected: i1) and from the
    control (expected: i32).

Every command is echoed with subprocess.list2cmdline(argv), i.e. exactly what was executed.
Output is passed through triage.redact_paths() before printing.

Usage (from the skill root):
    python data/issues/4540/make-release-matrix.py > data/issues/4540/manual-case-release-matrix.txt
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
sys.path.insert(0, str(SKILL / "scripts"))
import triage  # noqa: E402

ARGS = ["-T", "cs_6_0", "-E", "main"]
SHADERS = [("repro", "repro.hlsl"), ("control", "control-no-static.hlsl")]

GS_GLOBAL = re.compile(r"^.*addrspace\(3\)\s+global\s+\S+.*$", re.MULTILINE)
SELFTEST = re.compile(r"addrspace\(3\)\s+global\s+i\d+\b")
ENTRY = re.compile(r"define void @main\(\)")
DEFECT = re.compile(r"addrspace\(3\)\s+global\s+i1\b")
IDENT = re.compile(r"^!0 = !\{!\"(.+?)\"\}", re.MULTILINE)


def run(exe, shader):
    argv = [str(exe)] + ARGS + [shader]
    proc = subprocess.run(
        argv, cwd=str(HERE), capture_output=True, text=True, errors="replace", timeout=300
    )
    return subprocess.list2cmdline(argv), proc.returncode, proc.stdout + proc.stderr


def version_of(exe):
    try:
        proc = subprocess.run(
            [str(exe), "--version"], capture_output=True, text=True, errors="replace", timeout=120
        )
        return (proc.stdout + proc.stderr).strip().splitlines()[0]
    except Exception as exc:  # pragma: no cover - diagnostic path
        return f"<--version failed: {exc}>"


def main():
    db = triage.con()
    rows = db.execute(
        "SELECT tag, prerelease, cached_path, build_date FROM releases "
        "WHERE cached_path IS NOT NULL ORDER BY build_date"
    ).fetchall()

    builds = [(r["tag"], "prerelease" if r["prerelease"] else "stable", r["cached_path"])
              for r in rows]
    comp = triage.resolve_compiler("main-debug")
    builds.append(("main-debug", "ground-truth", comp))

    lines = []
    lines.append("Issue 4540 -- per-release control matrix")
    lines.append("generated by make-release-matrix.py; every command below was executed as shown")
    lines.append("")
    lines.append("repro.hlsl          : `static groupshared uint storeTile;`")
    lines.append("control-no-static.hlsl : same file, the token `static` removed. The issue")
    lines.append("                      itself names this as the correct configuration.")
    lines.append("SELFTEST pass = the build emitted a groupshared global of SOME integer type,")
    lines.append("                i.e. the module was really produced and read on that build.")
    lines.append("IDENT = the !llvm.ident string the build wrote into the very module the")
    lines.append("        predicate scores. Releases before ~v1.6 reject `--version`, so this")
    lines.append("        -- not a separate invocation -- is what proves which binary answered.")
    lines.append("")

    summary = []
    for tag, kind, exe in builds:
        lines.append("=" * 78)
        lines.append(f"### {tag}  ({kind})")
        lines.append(f"$ {subprocess.list2cmdline([str(exe), '--version'])}")
        lines.append(f"  {version_of(exe)}")
        row = {"tag": tag, "kind": kind}
        for name, shader in SHADERS:
            cmdline, code, out = run(exe, shader)
            gs = GS_GLOBAL.search(out)
            gs_line = gs.group(0).strip() if gs else "<no addrspace(3) global emitted>"
            st = "pass" if (SELFTEST.search(out) and ENTRY.search(out)) else "FAIL"
            ident = IDENT.search(out)
            ident_s = ident.group(1) if ident else "<no !llvm.ident in module>"
            lines.append(f"$ {cmdline}")
            lines.append(f"  exit=0x{code & 0xFFFFFFFF:08X} SELFTEST={st} IDENT={ident_s}")
            lines.append(f"  {gs_line}")
            if not gs:
                lines.append("  ---- first 12 lines of output ----")
                for ln in out.splitlines()[:12]:
                    lines.append(f"  | {ln}")
            row[name] = {
                "exit": code,
                "selftest": st,
                "line": gs_line,
                "ident": ident_s,
                "defect": bool(DEFECT.search(out)),
            }
        lines.append("")
        summary.append(row)

    lines.append("=" * 78)
    lines.append("SUMMARY")
    lines.append("")
    hdr = (f"{'build':<16} {'repro i1?':<10} {'repro selftest':<15} {'control i1?':<12} "
           f"{'control selftest':<17} {'IDENT (from the scored module)'}")
    lines.append(hdr)
    lines.append("-" * len(hdr))
    for row in summary:
        lines.append(
            f"{row['tag']:<16} "
            f"{('YES' if row['repro']['defect'] else 'no'):<10} "
            f"{row['repro']['selftest']:<15} "
            f"{('YES' if row['control']['defect'] else 'no'):<12} "
            f"{row['control']['selftest']:<17} "
            f"{row['repro']['ident']}"
        )
    lines.append("")
    n = len(summary)
    repro_yes = sum(1 for r in summary if r["repro"]["defect"])
    ctrl_yes = sum(1 for r in summary if r["control"]["defect"])
    st_ok = sum(1 for r in summary
                if r["repro"]["selftest"] == "pass" and r["control"]["selftest"] == "pass")
    idents = {r["repro"]["ident"] for r in summary}
    lines.append(f"builds measured                        : {n}")
    lines.append(f"repro emits an i1 groupshared global   : {repro_yes}/{n}")
    lines.append(f"control emits an i1 groupshared global : {ctrl_yes}/{n}")
    lines.append(f"both selftests pass                    : {st_ok}/{n}")
    lines.append(f"distinct IDENT strings                 : {len(idents)}/{n}")
    lines.append("")
    lines.append("A control that scored the same as the repro on every build would mean the")
    lines.append("predicate measures nothing. It does not.")

    sys.stdout.write(triage.redact_paths("\n".join(lines)) + "\n")


if __name__ == "__main__":
    main()
