"""Attribute issue 4540's i1 groupshared global to a specific optimizer pass, by measurement.

TWO WRONG TURNS ARE RECORDED HERE ON PURPOSE, because each produced a confident wrong answer
before it was caught.

  1. Source reading alone points at lib/Transforms/IPO/GlobalOpt.cpp:1595
     (TryToShrinkGlobalToBoolean). It builds exactly this shape -- a new i1 global with
     InternalLinkage, the ORIGINAL address space preserved, and each load rewritten to a
     zext/select -- but a shape match is a hypothesis, not an attribution.

  2. The first attempt to test it drove `dxc -Oconfig=<pass list>`. That option is declared in
     `spirv_Group` (include/dxc/Support/HLSLOptions.td:443, "a comma-separated list of
     SPIRV-Tools passes"), so on a DXIL compile it is **silently ignored**. Every run returned
     the default pipeline's answer, so a leave-one-out sweep over all 116 passes reported that
     removing NOTHING mattered -- including -globalopt. The "control" for that sweep was
     "replay the full list, expect the default result", which could not catch it, because its
     expected value was identical to the null result. A control whose expected value equals
     the default is not a control. Section 1 re-runs it so the ignoring is visible rather than
     asserted.

The instrument that does work is `dxopt`, which runs a named pass list over a bitcode module
and whose null-pass control produces a DIFFERENT answer from the pass under test.

Every command is echoed with subprocess.list2cmdline(argv); output goes through
triage.redact_paths().

Usage (from the skill root):
    python data/issues/4540/make-pass-attribution.py \
        > data/issues/4540/manual-case-pass-attribution.txt
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
sys.path.insert(0, str(SKILL / "scripts"))
import triage  # noqa: E402

SCRATCH = HERE / "scratch-passes"
ARGS = ["-T", "cs_6_0", "-E", "main"]
SHADER = "repro.hlsl"
GS = re.compile(r"^.*addrspace\(3\)\s+global\s+(\S+).*$", re.MULTILINE)
LOWERED = re.compile(r"@dx\.op\.barrier")

BIN = Path(triage.resolve_compiler("main-debug")).parent
DXC = BIN / "dxc.exe"
DXOPT = BIN / "dxopt.exe"


def run(argv, echo=None):
    argv = [str(a) for a in argv]
    proc = subprocess.run(argv, cwd=str(HERE), capture_output=True,
                          text=True, errors="replace", timeout=600)
    return (echo or subprocess.list2cmdline(argv),
            proc.returncode, proc.stdout + proc.stderr)


def gstype(text):
    m = GS.search(text)
    return m.group(1) if m else "<none>"


def disasm(bc):
    _c, _rc, text = run([DXC, "-dumpbin", bc])
    return text


def main():
    if SCRATCH.exists():
        shutil.rmtree(SCRATCH)
    SCRATCH.mkdir()
    out = []
    try:
        out.append("Issue 4540 -- which pass turns the groupshared global into i1")
        out.append("generated by make-pass-attribution.py; every command below was executed "
                   "as shown")
        out.append("")

        out.append("#" * 78)
        out.append("# 1. WHY THE OBVIOUS INSTRUMENT (-Oconfig) MEASURES NOTHING")
        out.append("#" * 78)
        out.append("")
        cmd, code, text = run([DXC] + ARGS + ["-fcgl", SHADER])
        out.append(f"$ {cmd}")
        out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}  groupshared global = {gstype(text)}"
                   f"   lowered DXIL present: {bool(LOWERED.search(text))}")
        cmd, code, text = run([DXC] + ARGS + [SHADER])
        out.append(f"$ {cmd}")
        out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}  groupshared global = {gstype(text)}"
                   f"   lowered DXIL present: {bool(LOWERED.search(text))}")
        cmd, code, text = run([DXC] + ARGS + ["-Oconfig=-opt-fn-passes,-opt-mod-passes",
                                              SHADER])
        out.append(f"$ {cmd}")
        out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}  groupshared global = {gstype(text)}"
                   f"   lowered DXIL present: {bool(LOWERED.search(text))}")
        out.append("  ^ an EMPTY pass list still produced fully lowered DXIL identical to the")
        out.append("    default, so -Oconfig is ignored on a DXIL compile and every")
        out.append("    -Oconfig measurement is void.")
        out.append("")

        out.append("#" * 78)
        out.append("# 2. dxopt: a pass runner whose null control differs from its test")
        out.append("#" * 78)
        out.append("")
        hl = SCRATCH / "hl.bc"
        cmd, code, text = run([DXC] + ARGS + [SHADER, "-fcgl", "-Fo", hl])
        out.append(f"$ {cmd}")
        out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}   (front-end module, before any pass)")
        d = disasm(hl)
        out.append(f"  input module groupshared global = {gstype(d)}"
                   f"   lowered DXIL present: {bool(LOWERED.search(d))}")
        out.append("")

        results = {}
        for label, passes in [("CONTROL-no-passes", []), ("globalopt-alone", ["-globalopt"])]:
            bc = SCRATCH / f"{label}.bc"
            cmd, code, text = run([DXOPT, f"-o={bc}", hl, "-opt-mod-passes"] + passes)
            d = disasm(bc) if code == 0 else ""
            ty = gstype(d) if code == 0 else "<dxopt failed>"
            results[label] = ty
            out.append(f"$ {cmd}")
            out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}  groupshared global = {ty}")
        out.append("")
        out.append(f"  null control -> {results['CONTROL-no-passes']} ; "
                   f"-globalopt -> {results['globalopt-alone']}")
        out.append("  The two differ, so this instrument can tell the two states apart --")
        out.append("  which is exactly what the -Oconfig 'control' in section 1 could not do.")
        out.append("")

        out.append("#" * 78)
        out.append("# 3. is -globalopt NECESSARY, or would another pass do it too?")
        out.append("#" * 78)
        out.append("")
        cmd, code, dump = run([DXC] + ARGS + ["-Odump", SHADER])
        passes = [ln.strip() for ln in dump.splitlines() if ln.strip().startswith("-")]
        out.append(f"$ {cmd}")
        out.append(f"  {len(passes)} passes in the default pipeline; '-globalopt' occurs "
                   f"{sum(1 for p in passes if p == '-globalopt')} time(s)")
        for label, plist in [
            ("full-pipeline", passes),
            ("full-pipeline-minus-globalopt", [p for p in passes if p != "-globalopt"]),
        ]:
            bc = SCRATCH / f"{label}.bc"
            cmd, code, text = run([DXOPT, f"-o={bc}", hl] + plist,
                                  echo=f"dxopt -o=<{label}.bc> <hl.bc> "
                                       f"<{len(plist)} passes: {label}>")
            d = disasm(bc) if code == 0 else ""
            ty = gstype(d) if code == 0 else "<dxopt failed>"
            out.append(f"$ {cmd}")
            out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}  groupshared global = {ty}"
                       f"   lowered DXIL present: {bool(LOWERED.search(d))}")
        out.append("")

        out.append("=" * 78)
        out.append("The load rewrite is the other half of the signature. In")
        out.append("control-static-readback.hlsl the two stored values are 0 and 2, and the")
        out.append("load comes back as `%9 = select i1 %8, i32 2, i32 0` -- the non-IsOneZero")
        out.append("arm of TryToShrinkGlobalToBoolean, which reconstructs the original value")
        out.append("at each use. So the shrink is value-preserving for a single thread; what")
        out.append("it does not preserve is a groupshared OBJECT of a type docs/DXIL.rst:240")
        out.append("defines for groupshared memory.")
    finally:
        shutil.rmtree(SCRATCH, ignore_errors=True)

    sys.stdout.write(triage.redact_paths("\n".join(out)) + "\n")


if __name__ == "__main__":
    main()
