"""Control the CE transformation for issue 4540.

`godbolt-source.hlsl` folds repro.hlsl and control-no-static.hlsl into one file behind a
`#ifdef NO_STATIC` guard, because Compiler Explorer gives every pane one shared source. A
transformed repro is a different program until someone shows it is not, and the transformation
has to be run on the KNOWN-GOOD arm as well -- otherwise a guard that accidentally disabled
the construct would look like a clean control.

So this compares four compiles, with the CE argument set (`-Zi -Qembed_debug`, which CE
appends to every DXC pane and which can change what is emitted):

    repro.hlsl                          vs  godbolt-source.hlsl
    control-no-static.hlsl              vs  godbolt-source.hlsl -DNO_STATIC

and reports the groupshared global line from each. The pairs must agree.

Every command is echoed with subprocess.list2cmdline(argv); output goes through
triage.redact_paths().

Usage (from the skill root):
    python data/issues/4540/make-godbolt-transform-case.py \
        > data/issues/4540/manual-case-godbolt-transform.txt
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
sys.path.insert(0, str(SKILL / "scripts"))
import triage  # noqa: E402

DXC = Path(triage.resolve_compiler("main-debug"))
BASE = ["-T", "cs_6_0", "-E", "main"]
CE_EXTRA = ["-Zi", "-Qembed_debug"]
GS = re.compile(r"^.*addrspace\(3\)\s+global\s+\S+.*$", re.MULTILINE)

PAIRS = [
    ("static kept",
     ["repro.hlsl"],
     ["godbolt-source.hlsl"]),
    ("static removed (the known-good arm)",
     ["control-no-static.hlsl"],
     ["godbolt-source.hlsl", "-DNO_STATIC"]),
]


def compile_(extra):
    argv = [str(DXC)] + BASE + CE_EXTRA + extra
    proc = subprocess.run(argv, cwd=str(HERE), capture_output=True, text=True,
                          errors="replace", timeout=300)
    text = proc.stdout + proc.stderr
    m = GS.search(text)
    return (subprocess.list2cmdline(argv), proc.returncode,
            m.group(0).strip() if m else "<no addrspace(3) global emitted>")


def main():
    out = ["Issue 4540 -- control for the Compiler Explorer source transformation",
           "generated by make-godbolt-transform-case.py; every command below was executed "
           "as shown",
           "",
           "CE appends -Zi -Qembed_debug -Fc - to DXC panes, so those flags are used here too.",
           ""]
    agree = 0
    for label, orig, folded in PAIRS:
        out.append("=" * 78)
        out.append(f"### {label}")
        rows = []
        for extra in (orig, folded):
            cmd, code, line = compile_(extra)
            out.append(f"$ {cmd}")
            out.append(f"  exit=0x{code & 0xFFFFFFFF:08X}")
            out.append(f"  {line}")
            rows.append(line)
        same = rows[0] == rows[1]
        agree += 1 if same else 0
        out.append(f"  -> untransformed and folded forms agree: "
                   f"{'YES' if same else 'NO  <== TRANSFORMATION IS THE SUBJECT, NOT THE BUG'}")
        out.append("")
    out.append("=" * 78)
    out.append(f"pairs in agreement: {agree}/{len(PAIRS)}")
    out.append("")
    out.append("Both arms are checked on purpose. Confirming only the reproducing arm would")
    out.append("miss a guard that silently disabled the construct in the control.")
    sys.stdout.write(triage.redact_paths("\n".join(out)) + "\n")


if __name__ == "__main__":
    main()
