"""#4723: prove the depfile flags are PARSED under -P, and that exit 0 is mute.

Two things have to be nailed down before "no depfile appeared" means anything,
and neither is visible in the scored captures:

1. **dxc silently ignores unknown `/`-style flags.** `/ZZZNONSENSE` exits 0 and
   prints nothing. So a clean exit is not evidence that `-MF` was understood --
   or that it was not.

2. **The distinguishing observation is the failure mode, not the success.**
   Point `-MF` at a directory that does not exist. In compile mode dxc
   complains, which can only happen if it parsed the flag and tried to open the
   file. Under `-P` the identical argument produces silence, so the flag was
   accepted by the option table and then never reached anything that opens a
   file. That is a routing gap, not an unrecognised option.

The third case is the contrast that makes it a bug rather than a documentation
oversight: `-P -Fo` DOES produce "warning: compiler option ... ignored with
Preprocess". dxc already has the machinery to tell a user that an output flag
does nothing in this mode. The `-M` family was left off that list.

Exit statuses are captured in Python. `%ERRORLEVEL%` expands when the line is
parsed, so a cmd one-liner reports the *previous* command's status -- that trap
produced several minutes of confidently wrong readings while exploring this
issue, and it is why nothing here shells out through cmd.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, *([os.pardir] * 6)))
sys.path.insert(0, os.path.join(REPO, ".github", "skills", "dxc-issue-triage",
                                "scripts"))
import triage  # noqa: E402

DXC = os.environ.get("DXC_EXE") or os.path.join(REPO, "build", "Debug", "bin",
                                                "dxc.exe")
REPORT = os.path.join(HERE, "manual-case-flag-parse-proof.txt")

CASES = [
    ("-MF is parsed in compile mode: an unwritable target is diagnosed",
     ["-T", "ps_6_0", "-E", "main", "-MF", "no-such-dir/dep.d",
      "repro.hlsl"]),
    ("the same -MF under -P: identical argument, no diagnostic at all",
     ["-T", "ps_6_0", "-E", "main", "-P", "-Fi", "parse-proof.i",
      "-MF", "no-such-dir/dep.d", "repro.hlsl"]),
    ("control: an unknown /-style flag is accepted silently and exits 0",
     ["-T", "ps_6_0", "-E", "main", "-P", "-Fi", "parse-proof.i",
      "/ZZZNONSENSE", "repro.hlsl"]),
    ("contrast: -Fo under -P IS diagnosed as ignored -- the list exists",
     ["-T", "ps_6_0", "-E", "main", "-P", "-Fi", "parse-proof.i",
      "-Fo", "parse-proof.dxo", "repro.hlsl"]),
    ("the flags are real and documented: dxc -help",
     ["-help"]),
]


def run(args):
    p = subprocess.run([DXC] + args, cwd=HERE, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    return p.returncode & 0xFFFFFFFF, triage.redact_paths(
        (p.stdout or "") + (p.stderr or ""))


def main():
    out = [
        "#4723 -- are the depfile flags parsed under -P, and does exit 0 mean "
        "anything?",
        "",
        "Generated by manual-cases.py. Commands are echoed exactly as they",
        "were executed; exit statuses come from Python, not from",
        "%ERRORLEVEL%, which a single cmd line expands at parse time and so",
        "reports the previous command's status.",
        "",
        "dxc: " + triage.display_exe(DXC),
    ]
    rc, ver = run(["--version"])
    out += ["version: " + " ".join(ver.split()), ""]

    for title, args in CASES:
        rc, text = run(args)
        out.append("=== " + title)
        out.append("$ dxc " + subprocess.list2cmdline(args))
        out.append(f"exit=0x{rc:08X}")
        body = text.splitlines()
        if args == ["-help"]:
            body = [ln for ln in body
                    if ln.lstrip().startswith(("-M", "/M", "-P", "/P",
                                               "-Fi", "/Fi"))]
            out.append("(-help output, filtered to the flags in question)")
        if any(ln.strip() for ln in body):
            out += ["| " + ln for ln in body[:14]]
        else:
            out.append("| (no output)")
        out.append("")

    out += [
        "READING",
        "",
        "Case 1 vs case 2 is the whole point. The -MF argument is character",
        "for character the same in both; only -P differs. Compile mode tries",
        "to open the file and says so when it cannot. -P mode says nothing,",
        "which means the option table accepted -MF and nothing downstream",
        "ever asked for it. Case 3 shows why that silence cannot be read as",
        "'-MF was rejected': dxc accepts /ZZZNONSENSE just as quietly, and",
        "exits 0. Case 4 shows dxc already warns about OTHER output flags",
        "that do nothing under -P (-Fo), so the silence for -M/-MD/-MF is an",
        "omission from that list rather than a deliberate design.",
    ]
    with open(REPORT, "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(out)) + "\n")
    for name in ("parse-proof.i", "parse-proof.dxo"):
        p = os.path.join(HERE, name)
        if os.path.isfile(p):
            os.remove(p)
    print("wrote " + os.path.basename(REPORT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
