"""Issue-local release matrix for issue #4888's secondary (SPIR-V) signature.

`bisect` cannot be used for this: the reported crash needs `-spirv` added to a
compute-shader restatement of the repro (variant-cs-array.hlsl), which is a
different command line from cmd.txt's primary probe (`-T ps_6_6 -E PSMain
repro.hlsl`, no -spirv). Per SKILL.md ("Per-release controls currently need an
issue-local matrix"), this script holds the command fixed and varies each
stable release's dxc.exe, querying triage.db's `releases` table for each
cached executable so the paths are not hand-transcribed.

Run from the issue directory:
    python measure-spirv-history.py
Writes manual-case-spirv-crash-history.txt next to this script.
"""
import subprocess
import sqlite3
import os
import sys

SKILL_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
DB_PATH = os.path.join(SKILL_ROOT, ".cache", "triage.db")
ISSUE_DIR = os.path.dirname(os.path.abspath(__file__))

# Reuse triage.py's own path-tokenising helpers rather than re-deriving the
# redaction logic: a committed capture must not bake in this machine's
# checkout path (see check_paths.py / SKILL.md's redaction guidance).
sys.path.insert(0, os.path.join(SKILL_ROOT, "scripts"))
from triage import display_exe, redact_paths  # noqa: E402

# Stable releases only (bisectable=1), oldest to newest. v1.4.1907 and v1.5.2010
# are omitted: the primary bisect (out-v1.4.1907.txt / out-v1.5.2010.txt) already
# established that both reject `-T ps_6_6`/`cs_6_6` as an invalid profile, so
# they cannot reach either signature under test -- rerunning them here would
# only reproduce that same invalid-probe, not answer this question.
STABLE_TAGS_FROM = "v1.6.2104"

ARGS = ["-T", "cs_6_6", "-E", "main", "-Od", "-Vd", "-spirv", "variant-cs-array.hlsl"]


def classify(exit_code: int) -> str:
    unsigned = exit_code & 0xFFFFFFFF
    crash_hresults = {0xC0000005, 0xC00000FD, 0x80000003, 0x80AA0018,
                      0x80AA001B, 0x80AA001C, 0x80AA001D,
                      0xE0000001, 0xE0000002, 0xE0000003}
    if unsigned in crash_hresults:
        return "internal_failure"
    return "clean-or-diagnosed"


def main():
    con = sqlite3.connect(DB_PATH)
    rows = con.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE bisectable=1 AND cached_path IS NOT NULL AND build_date >= '2021-04-20' "
        "ORDER BY build_date"
    ).fetchall()
    con.close()

    out_lines = [
        "# manual-case-spirv-crash-history.txt -- generated by measure-spirv-history.py",
        "# Command held fixed, release dxc.exe varied. See match-crash.json.",
        "# cmd (relative to variant-cs-array.hlsl): " + subprocess.list2cmdline(ARGS),
        "",
    ]
    for tag, build_date, cached_path in rows:
        if not os.path.exists(cached_path):
            out_lines.append(f"{tag} ({build_date}): SKIPPED -- cached_path does not exist: {cached_path}")
            continue
        ver = subprocess.run([cached_path, "--version"], cwd=ISSUE_DIR,
                              capture_output=True, text=True, timeout=60)
        version_line = ver.stdout.strip().splitlines()[0] if ver.stdout.strip() else "(no --version output)"
        argv = [cached_path] + ARGS
        proc = subprocess.run(argv, cwd=ISSUE_DIR, capture_output=True, text=True, timeout=60)
        verdict = classify(proc.returncode)
        out_lines.append(f"=== {tag} ({build_date}) ===")
        out_lines.append(f"version: {version_line}")
        out_lines.append(f"$ {display_exe(cached_path)} {subprocess.list2cmdline(ARGS)}")
        out_lines.append(f"exit: {proc.returncode} (0x{proc.returncode & 0xFFFFFFFF:08X})  verdict: {verdict}")
        out_lines.append("--- stdout ---")
        out_lines.append(proc.stdout.strip())
        out_lines.append("--- stderr ---")
        out_lines.append(proc.stderr.strip())
        out_lines.append("")

    text = "\n".join(out_lines) + "\n"
    text = redact_paths(text)
    out_path = os.path.join(ISSUE_DIR, "manual-case-spirv-crash-history.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(text)


if __name__ == "__main__":
    sys.exit(main())
