"""PDB cross-check for issue 3531.

Everything else in this directory scores dxc's disassembly of the module it just compiled.
PIX, which is where this issue came from, reads the *PDB*.  If the PDB carried debug info the
disassembly does not, the whole verdict would be measuring the wrong artifact.

So: compile once with -Zi -Qembed_debug -Fo, then disassemble the resulting container with
`dxc -dumpbin`, and compare which variables each output names.  Writes
manual-case-pdb-crosscheck.txt.  Every command is echoed with subprocess.list2cmdline, and the
comparison prints a loud marker if it parsed nothing, so "no debug info anywhere" cannot be
confused with "this script found nothing".

Intermediate binaries are written to dbgdir/, which is gitignored; the directory is created
here because git cannot track an empty one.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
REPO = SKILL.parents[2]
OUTDIR = HERE / "dbgdir"

NAMED = re.compile(r'!DI(?:Local|Global)Variable\([^\n]*name: "([^"]+)"')


def redact(text: str) -> str:
    return text.replace(str(SKILL / ".cache"), "<cache>").replace(str(REPO), "<repo>")


def exe() -> str:
    reg = json.loads((SKILL / ".cache" / "compilers" / "main-debug.json").read_text())
    return reg["exe_path"]


def run(argv, lines):
    lines.append("$ " + redact(subprocess.list2cmdline(["dxc"] + argv[1:])))
    lines.append("[exe] " + redact(argv[0]))
    proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
    out = (proc.stdout or "") + (proc.stderr or "")
    lines.append(f"[exit] {proc.returncode} (0x{proc.returncode & 0xFFFFFFFF:08X})")
    return out


def main() -> int:
    OUTDIR.mkdir(exist_ok=True)
    dxc = exe()
    lines = []

    lines.append("### compile with -Zi -Qembed_debug, straight to disassembly on stdout")
    direct = run(
        [dxc, "-T", "cs_6_6", "-E", "DynamicResources", "-Zi", "-Qembed_debug", "repro.hlsl"],
        lines,
    )
    direct_names = sorted(set(NAMED.findall(direct)))
    lines.append(f"[named variables] {direct_names}")
    lines.append("")

    lines.append("### the same compile written to a container, then disassembled from it")
    run(
        [
            dxc, "-T", "cs_6_6", "-E", "DynamicResources", "-Zi", "-Qembed_debug",
            "-Fo", "dbgdir/repro.dxil", "repro.hlsl",
        ],
        lines,
    )
    dumped = run([dxc, "-dumpbin", "dbgdir/repro.dxil"], lines)
    dumped_names = sorted(set(NAMED.findall(dumped)))
    lines.append(f"[named variables] {dumped_names}")
    for ln in dumped.splitlines():
        if "DILocalVariable" in ln or "DIGlobalVariable" in ln or "ILDB" in ln:
            lines.append("  " + redact(ln.strip())[:200])
    lines.append("")

    target = "DynamicallyIndexedDynamicBuffer"
    header = [
        "# PDB / container cross-check for issue 3531",
        "# generated by pdb-crosscheck.py, which echoes every command it runs",
        "",
    ]
    if not direct_names and not dumped_names:
        header.append(
            "DXC-3531: PARSE-WARNING: 0 debug variables parsed from either output --"
            " this cross-check proved nothing"
        )
    else:
        header.append(f"stdout disassembly names   : {direct_names}")
        header.append(f"container disassembly names: {dumped_names}")
        header.append(
            f"{target!r} present in stdout disassembly   : {target in direct_names}"
        )
        header.append(
            f"{target!r} present in container disassembly: {target in dumped_names}"
        )
    header.append("")

    (HERE / "manual-case-pdb-crosscheck.txt").write_text(
        "\n".join(header + lines), encoding="utf-8"
    )
    print("\n".join(header))
    return 0


if __name__ == "__main__":
    sys.exit(main())
