"""Per-release control matrix for issue 3531.

`bisect` probes only repro.hlsl. Two questions it cannot answer on its own:

  1. feature presence -- did this release reject the repro because it predates SM 6.6
     dynamic resources, or because of something unrelated in my repro?
  2. instrument validity -- on THIS release, can the debug-info emitter name a local
     called DynamicallyIndexedDynamicBuffer at all?  The finding is an absence, so a
     release whose debug-info emitter is simply different would look like a reproduction
     for free.  control-name-selftest.hlsl declares that same name at that same line as an
     ordinary `uint`; if the release emits a DILocalVariable for it, the absence measured
     on the resource version is meaningful on that release.

Run from the issue directory.  Writes manual-case-release-controls.txt, echoing every
command with subprocess.list2cmdline so the transcript cannot drift from what was run.
"""

import json
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parents[2]
DB = SKILL / ".cache" / "triage.db"
REPO = SKILL.parents[2]


def ground_truth_exe() -> Path:
    """Take the ground-truth compiler from the registry, never from a hardcoded path."""
    reg = json.loads((SKILL / ".cache" / "compilers" / "main-debug.json").read_text())
    return Path(reg["exe_path"])

ARGS = ["-T", "cs_6_6", "-E", "DynamicResources", "-Zi", "-Qembed_debug"]
CASES = [
    ("heap-feature", "control-heap.hlsl"),
    ("name-selftest", "control-name-selftest.hlsl"),
]

DILOCAL_NAMED = re.compile(r'!DILocalVariable\([^\n]*name: "DynamicallyIndexedDynamicBuffer"')
DIANY_NAMED = re.compile(r'!DI(?:Local|Global)Variable\([^\n]*name: "DynamicallyIndexedDynamicBuffer"')
HEAP_OP = re.compile(r"@dx\.op\.createHandleFromHeap")


def redact(text: str) -> str:
    text = text.replace(str(SKILL / ".cache"), "<cache>")
    text = text.replace(str(REPO), "<repo>")
    return text


def compilers():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, cached_path FROM releases WHERE prerelease=0 AND cached_path IS NOT NULL"
        " ORDER BY build_date"
    ).fetchall()
    con.close()
    out = [(r["tag"], Path(r["cached_path"])) for r in rows]
    out.append(("main-debug", ground_truth_exe()))
    return out


def main() -> int:
    lines = []
    summary = []
    parsed = 0
    for tag, exe in compilers():
        if not exe.exists():
            lines.append(f"### {tag}: MISSING EXECUTABLE {redact(str(exe))}\n")
            summary.append((tag, "missing", "missing"))
            continue
        verdicts = {}
        for label, shader in CASES:
            argv = [str(exe)] + ARGS + [shader]
            proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
            out = (proc.stdout or "") + (proc.stderr or "")
            parsed += 1
            if label == "heap-feature":
                verdict = (
                    "feature-present"
                    if proc.returncode == 0 and HEAP_OP.search(out)
                    else "feature-absent-or-rejected"
                )
            else:
                verdict = (
                    "names-the-local"
                    if proc.returncode == 0 and DILOCAL_NAMED.search(out)
                    else "does-not-name-the-local"
                )
            verdicts[label] = verdict
            lines.append(f"### {tag} / {label} ({shader})")
            lines.append("$ " + redact(subprocess.list2cmdline(["dxc"] + ARGS + [shader])))
            lines.append("[exe] " + redact(str(exe)))
            lines.append(f"[exit] {proc.returncode} (0x{proc.returncode & 0xFFFFFFFF:08X})")
            lines.append(f"[verdict] {verdict}")
            interesting = [
                ln
                for ln in out.splitlines()
                if "DILocalVariable" in ln
                or "DIGlobalVariable" in ln
                or "error:" in ln
                or "warning:" in ln
            ]
            if interesting:
                lines.append("[selected output]")
                lines.extend("  " + redact(ln.strip())[:200] for ln in interesting)
            else:
                lines.append("[selected output] none")
            lines.append("")
        summary.append((tag, verdicts["heap-feature"], verdicts["name-selftest"]))

    header = [
        "# per-release control matrix for issue 3531",
        "# generated by release-controls.py, which echoes every command it runs",
        f"# args: {subprocess.list2cmdline(ARGS)}",
        "#",
        "# heap-feature   : does this release support SM 6.6 ResourceDescriptorHeap at all?",
        "# name-selftest  : can this release emit a DILocalVariable named",
        "#                  DynamicallyIndexedDynamicBuffer when the local is a plain uint?",
        "#                  If yes, the absence measured on the resource version is a real",
        "#                  absence on this release and not a quirk of its debug-info format.",
        "",
        "## summary",
        "",
        f"{'release':<16}{'heap-feature':<28}{'name-selftest'}",
    ]
    for tag, a, b in summary:
        header.append(f"{tag:<16}{a:<28}{b}")

    # self-consistency: a matrix that parsed nothing must say so loudly rather than
    # reporting a uniform clean result (SKILL.md: a harness that can return "nothing here"
    # and "nothing matched" through the same channel will eventually be believed).
    named = sum(1 for _, _, b in summary if b == "names-the-local")
    header.append("")
    if parsed == 0 or named == 0:
        header.append(
            f"DXC-3531: PARSE-WARNING: {parsed} run(s) inspected, {named} release(s) named the"
            " local in the self-test -- the instrument proved nothing"
        )
    else:
        header.append(
            f"DXC-3531: self-test OK: {named} of {len(summary)} release(s) emit"
            ' !DILocalVariable(name: "DynamicallyIndexedDynamicBuffer") for a plain uint local'
        )
    header.append("")

    (HERE / "manual-case-release-controls.txt").write_text(
        "\n".join(header + lines), encoding="utf-8"
    )
    print("\n".join(header))
    return 0


if __name__ == "__main__":
    sys.exit(main())
