"""Cross-compiler probe: does the successor front end (Clang) share the defect?

Step 7 of the skill asks whether the successor compiler has already answered the
issue. The Compiler Explorer link carries a `hlsl_clang_trunk` pane, and that
pane compiles this repro *successfully* -- which is the interesting case, and
also the one that needs the most care, because two things differ at once:

  1. Clang lays the matrix out **column-major** here; it does not appear to act
     on `#pragma pack_matrix(row_major)`. So Clang's offset *sequence* cannot be
     compared against DXC's row-major sequence directly -- they are answers to
     different questions. This script measures that rather than assuming it, by
     compiling both `minimal-matrix.hlsl` (with the pragma) and
     `minimal-matrix-colmajor.hlsl` (without) on both compilers. If Clang emits
     the same offsets for both, the pragma is not in play and the honest
     comparison is Clang vs DXC's *column-major* variant.

  2. The skill's rule -- "a Clang error is not evidence until you have a
     control" -- has a converse worth honouring: a Clang *success* is not
     evidence either until the pane is shown to be doing the work. TRIVIAL below
     is that control: a 16-bit compute shader with no matrix anywhere. It must
     compile and emit an f16 access, otherwise `-enable-16bit-types` is being
     dropped and every f16 offset in this file is meaningless.

The control is inline rather than a checked-in `.hlsl` so that it cannot be
mistaken for another repro shape needing its own capture.

Reproduce:  python <repo>/.github/skills/dxc-issue-triage/data/issues/4492/ce-clang-probe.py
Writes:     manual-case-clang-comparison.txt   (network: godbolt.org)
"""
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SKILL_DIR)))
OUT = os.path.join(HERE, "manual-case-clang-comparison.txt")

# Reuse triage.py's own CE transport so this probe cannot drift from the link
# in godbolt.txt: same endpoint, same filters (CE's default comment stripping
# would delete DXC's Buffer Definitions table), same response flattening.
_spec = importlib.util.spec_from_file_location(
    "triage_mod", os.path.join(SKILL_DIR, "scripts", "triage.py"))
triage = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(triage)

ARGS = "-T cs_6_2 -E testStructuredBufferMatrixLoad2 -enable-16bit-types"
TRIVIAL_ARGS = "-T cs_6_2 -E main -enable-16bit-types"

# Control: 16-bit compute, no matrix. Proves the pane compiles and that
# -enable-16bit-types survives, so an f16 offset list means something.
TRIVIAL = """RWStructuredBuffer<float16_t> result : register(u0);
StructuredBuffer<float16_t> src : register(t1);

[numthreads(1, 1, 1)]
void main()
{
    result[0] = src[0] + (float16_t)1.0;
}
"""

ACCESS = re.compile(
    r"@dx\.op\.rawBuffer(Load|Store)\.f16\(i32 \d+, %dx\.types\.Handle %[\w.]+, "
    r"i32 [^,]+, i32 (\d+).*?i8 (\d+), i32 (\d+)\)")

# The reference layouts, derived from the source and the type, not from any
# compiler's output. `a[0].xy` then `a[3].zw` of a 4x4 half matrix:
#   row-major    element [r][c] at byte 2*(4r + c)
#   column-major element [r][c] at byte 2*(4c + r)
CORRECT = {"row_major": [0, 2, 28, 30], "column_major": [0, 8, 22, 30]}
ELEMENT_BYTES = 32


def rel(path):
    try:
        return "<repo>/" + os.path.relpath(path, REPO_ROOT).replace("\\", "/")
    except ValueError:
        return path


def observe(text):
    return [(k, int(o), int(m), int(a)) for k, o, m, a in ACCESS.findall(text)]


def span(accesses):
    hi = 0
    for _, off, mask, _a in accesses:
        hi = max(hi, off + 2 * bin(mask).count("1"))
    return hi


def main():
    cases = [
        ("TRIVIAL (control)", None, TRIVIAL, TRIVIAL_ARGS),
        ("minimal-matrix.hlsl", "minimal-matrix.hlsl", None, ARGS),
        ("minimal-matrix-colmajor.hlsl", "minimal-matrix-colmajor.hlsl",
         None, ARGS),
    ]
    compilers = ["dxc_trunk", "hlsl_clang_trunk"]

    out = []

    def w(line=""):
        out.append(line)
        print(line)

    w("Compiler Explorer cross-compiler probe for #4492")
    w("Generated by " + rel(os.path.abspath(__file__)))
    w("=" * 78)
    w()
    w("Question: DXC scales structured-buffer matrix element indices by 4 bytes")
    w("instead of the 2-byte size of a 16-bit scalar. Does the successor front")
    w("end (Clang, where HLSL support is being rebuilt) do the same?")
    w()
    w("Compilers: " + ", ".join(compilers) + "  (Compiler Explorer, Linux Release)")
    w("Arguments: " + ARGS)
    w()
    w("Reference offsets for `a[0].xy` then `a[3].zw` of a 4x4 half matrix,")
    w("derived from the type -- not from any compiler:")
    for k, v in CORRECT.items():
        w(f"  {k:<13} {v}   (element is {ELEMENT_BYTES} bytes)")
    w()

    results = {}
    for label, fname, inline, args in cases:
        src = inline
        if fname:
            path = os.path.join(HERE, fname)
            with open(path, encoding="utf-8") as f:
                src = f.read()
            w(f"--- {label}   ({rel(path)})")
        else:
            w(f"--- {label}   (inline in this script)")
        for comp in compilers:
            rc, text, crashed = triage.ce_compile(src, comp, args)
            acc = observe(text)
            offs = [o for _k, o, _m, _a in acc]
            aligns = sorted({a for _k, _o, _m, a in acc})
            note = ""
            if not acc:
                note = "  4492-PROBE-WARNING: no f16 access found"
            w(f"      {comp:<18} exit={rc} crash={crashed} "
              f"f16 offsets={offs or '(none)'} align={aligns or '(none)'} "
              f"span={span(acc)}{note}")
            results[(label, comp)] = (rc, offs, aligns, span(acc))
        w()

    w("=" * 78)
    w("Self-tests -- if any of these fails, nothing below it is measurement.")
    w()
    ok = True
    for comp in compilers:
        rc, offs, aligns, _s = results[("TRIVIAL (control)", comp)]
        good = rc == 0 and offs and aligns == [2]
        ok &= good
        w(f"  [{'PASS' if good else 'FAIL'}] {comp}: control compiles, emits an "
          f"f16 access at alignment 2 (exit={rc}, offsets={offs}, align={aligns})")
    w()
    w("  The control has no matrix, so both compilers must handle it. It fixes")
    w("  the meaning of an empty offset list below: absence of f16 accesses")
    w("  would be a dropped -enable-16bit-types, not a compiler difference.")
    w()

    w("=" * 78)
    w("Reading")
    w()
    pragma_same = (results[("minimal-matrix.hlsl", "hlsl_clang_trunk")][1] ==
                   results[("minimal-matrix-colmajor.hlsl",
                            "hlsl_clang_trunk")][1])
    w(f"  Clang emits the same offsets with and without "
      f"`#pragma pack_matrix(row_major)`: {pragma_same}")
    if pragma_same:
        w("  -> the pragma is not acted on, so Clang answers the column-major")
        w("     question. Compare Clang against DXC's *colmajor* row only.")
    w()
    for label in ("minimal-matrix.hlsl", "minimal-matrix-colmajor.hlsl"):
        want = CORRECT["row_major" if label == "minimal-matrix.hlsl"
                       else "column_major"]
        w(f"  {label}")
        for comp in compilers:
            _rc, offs, _a, sp = results[(label, comp)]
            verdict = "matches the type layout" if offs == want else \
                "does NOT match this layout"
            doubled = offs == [x * 2 for x in want]
            w(f"    {comp:<18} {offs}  {verdict}"
              f"{'; exactly 2x the correct offsets' if doubled else ''}")
            w(f"    {'':<18} highest byte touched = {sp} "
              f"({'inside' if sp <= ELEMENT_BYTES else 'PAST THE END OF'} "
              f"the {ELEMENT_BYTES}-byte element)")
        w()

    clang_cm = results[("minimal-matrix-colmajor.hlsl", "hlsl_clang_trunk")][1]
    dxc_cm = results[("minimal-matrix-colmajor.hlsl", "dxc_trunk")][1]
    w("  Apples-to-apples (both column-major, same source file):")
    w(f"    Clang {clang_cm}   DXC {dxc_cm}")
    if clang_cm == CORRECT["column_major"] and dxc_cm == [x * 2 for x in clang_cm]:
        w("    -> Clang is correct; DXC is exactly double. The successor front")
        w("       end does not share the defect.")
    w()
    w("Caveat: Compiler Explorer's oldest DXC is 1.6.2112, which is already")
    w("inside the range where the reporter's shader reproduces, so the link")
    w("cannot show the v1.6.2104 boundary. It corroborates today's behaviour.")
    if not ok:
        w()
        w("4492-PROBE-WARNING: a self-test failed; treat this file as unusable.")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("\nwrote " + rel(OUT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
