"""#4492: is the reporter's attached DXIL the same instance we reproduce?

The issue attaches `3-mat.dxil.asm`, produced by the reporter in 2022-06 from
"latest main", targeting cs_6_5 (`!dx.shaderModel = !{!"cs", i32 6, i32 5}`).
That is a quotation of compiler output, so it can be checked mechanically
instead of eyeballed: compile the same attached shader at the same profile with
each nearby release and compare.

Two comparisons, because they answer different things:

  offsets  -- the `rawBufferLoad.f16` elementOffset/mask sequence. This is the
              defect itself, and it is what must match.
  body     -- the full `define void @...` block, whitespace-normalised. A
              mismatch here is not a finding on its own (the reporter's build
              is a 2022 main snapshot, not any release), but an exact match is
              strong evidence the very same codegen path is being exercised.

Self-consistency: if either side yields zero loads the row says
4492-PARSE-WARNING rather than reporting a vacuous "equal" on two empty lists.

Run:  python compare-attachment.py
Writes: manual-case-attachment-fidelity.txt
"""

import os
import re
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SKILL_DIR)))
DB = os.path.join(SKILL_DIR, ".cache", "triage.db")
GROUND_TRUTH = os.path.join(REPO_ROOT, "build", "Debug", "bin", "dxc.exe")

ATTACHMENT = os.path.join(HERE, "attachment", "3-mat.dxil.asm")

# The reporter's own configuration, read off the attachment: cs_6_5 and
# "Use native low precision".
ARGS = ["-T", "cs_6_5", "-E", "testStructuredBufferMatrixLoad2",
        "-enable-16bit-types"]
SHADER = "repro.hlsl"

# Releases bracketing the 2022-06-01 filing date, plus ground truth.
NEARBY = ["v1.6.2112", "v1.7.2207", "v1.7.2212"]

LOAD = re.compile(
    r"@dx\.op\.rawBufferLoad\.f16\(i32 \d+, %dx\.types\.Handle %[\w.]+, "
    r"i32 [^,]+, i32 (\d+), i8 (\d+)")
BODY = re.compile(r"^define void @[\s\S]*?^\}", re.MULTILINE)


def rel(path):
    try:
        return "<repo>/" + os.path.relpath(path, REPO_ROOT).replace("\\", "/")
    except ValueError:
        return path


def loads(text):
    return [(int(o), int(m)) for o, m in LOAD.findall(text)]


def body(text):
    m = BODY.search(text)
    if not m:
        return None
    # Normalise only whitespace runs; SSA numbering and operands are compared.
    return "\n".join(re.sub(r"[ \t]+", " ", ln.rstrip())
                     for ln in m.group(0).splitlines())


def exes():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, cached_path FROM releases WHERE cached_path IS NOT NULL"
    ).fetchall()
    con.close()
    by_tag = {r["tag"]: r["cached_path"] for r in rows}
    out = [(t, by_tag[t]) for t in NEARBY if t in by_tag]
    out.append(("main-debug", GROUND_TRUTH))
    return out


def main():
    with open(ATTACHMENT, encoding="utf-8") as f:
        ref_text = f.read()
    ref_loads = loads(ref_text)
    ref_body = body(ref_text)

    out = []
    w = out.append
    w("#4492 reporter-attachment fidelity check")
    w("")
    w("Generated by compare-attachment.py (committed beside this file).")
    w(f"reference: {rel(ATTACHMENT)}")
    w("           the reporter's own DXIL disassembly, attached to the issue in")
    w("           dxc-float16_t4x4-example.zip, produced 2022-06 from 'latest main'.")
    w(f"shader:    {SHADER} (byte-identical to the attached 1-mat.hlsl)")
    w(f"args:      {subprocess.list2cmdline(ARGS)}   (the profile the attachment names)")
    w("")
    w(f"reference f16 load offsets/masks ({len(ref_loads)} loads):")
    w("  " + " ".join(f"{o}/m{m}" for o, m in ref_loads))
    w("")
    if not ref_loads:
        w("4492-PARSE-WARNING: no loads parsed from the attachment; the reader,")
        w("not the evidence, is what changed. Every comparison below is vacuous.")

    warnings = 0 if ref_loads else 1
    for tag, exe in exes():
        if not os.path.exists(exe):
            w(f"## {tag}: SKIPPED, no executable at {rel(exe)}")
            continue
        argv = [exe] + ARGS + [SHADER]
        p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                           timeout=180)
        text = (p.stdout or "") + (p.stderr or "")
        got_loads = loads(text)
        got_body = body(text)
        w(f"## {tag}")
        w(f"$ {subprocess.list2cmdline([rel(argv[0])] + argv[1:])}")
        w(f"  exit={p.returncode}")
        w(f"  f16 loads ({len(got_loads)}): "
          + (" ".join(f"{o}/m{m}" for o, m in got_loads) or "(none)"))
        if p.returncode == 0 and not got_loads:
            w("  4492-PARSE-WARNING: exit 0 but 0 loads parsed.")
            warnings += 1
        w(f"  offsets identical to attachment: "
          f"{'YES' if got_loads and got_loads == ref_loads else 'no'}")
        w(f"  entry-function body identical to attachment: "
          f"{'YES' if got_body and ref_body and got_body == ref_body else 'no'}")
        w("")

    w(f"4492-PARSE-WARNINGS: {warnings}")
    text = "\n".join(out) + "\n"
    dest = os.path.join(HERE, "manual-case-attachment-fidelity.txt")
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(text)
    print(f"wrote {rel(dest)}")
    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
