"""Release-history matrix for issue 4722.

`triage.py bisect` drives one predicate over one repro. This issue has two faces
-- a silent dropped-orientation and a spurious rejection -- and the decisive
evidence for the silent one is a *comparison between two shaders*, which no
single-shader predicate can express. So the full history is measured here, with
each release's own dxc.exe running the whole set.

Every row carries its own controls, which is the point: a release that cannot
compile an HLSL 2021 template has not measured anything, and a release whose
concrete row_major/column_major pair does not differ has a broken instrument
rather than a clean result. Both are printed per release rather than assumed
from ground truth.

  python measure_history.py > manual-case-release-history.txt

Reads the catalogued stable releases from the triage database (read-only
SELECT). Prereleases are excluded: the issue names none.
"""

import hashlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, os.pardir, os.pardir, os.pardir, "scripts"))
import triage                                                    # noqa: E402

ARGS = ["-T", "ps_6_0", "-E", "main", "-HV", "2021"]

FEATURE = "control-feature-templates.hlsl"
SILENT = [("tmpl-row", "repro.hlsl"),
          ("tmpl-col", "control-template-column-major.hlsl"),
          ("conc-row", "control-nontemplate-row-major.hlsl"),
          ("conc-col", "control-nontemplate-column-major.hlsl")]
LOUD = [("qual-tmpl", "repro-explicit-qualifier.hlsl"),
        ("qual-conc", "control-explicit-qualifier-nontemplate.hlsl")]

ORIENT = re.compile(r"^;\s*(row_major|column_major) float4x4 M;", re.MULTILINE)
REJECT = "error: 'row_major' can only be used with a matrix type"


def builds():
    rows = triage.con().execute(
        "SELECT tag, build_date, cached_path FROM releases"
        " WHERE prerelease=0 AND cached_path IS NOT NULL"
        " ORDER BY build_date").fetchall()
    out = [(r["tag"], r["build_date"], r["cached_path"]) for r in rows]
    gt = triage.con().execute(
        "SELECT exe_path FROM compilers WHERE id='main-debug'").fetchone()
    if gt:
        out.append(("main-debug", "(ground truth)", gt["exe_path"]))
    return out


def compile_one(exe, source, extra=()):
    argv = [exe] + ARGS + list(extra) + [source]
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def hashed(exe, source):
    out = "history-tmp.dxo"
    abs_out = os.path.join(HERE, out)
    if os.path.exists(abs_out):
        os.remove(abs_out)
    code, text = compile_one(exe, source, ("-Fo", out))
    digest = None
    if os.path.exists(abs_out):
        with open(abs_out, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        os.remove(abs_out)
    _, disasm = compile_one(exe, source)
    m = ORIENT.search(disasm)
    return code, (m.group(1) if m else None), digest


def main():
    print("# issue 4722 -- release matrix, both faces, with per-release controls")
    print("# every release runs its OWN dxc.exe over the same six sources")
    print("# generated by measure_history.py; commands are echoed below")
    print()
    print("$ " + subprocess.list2cmdline(["dxc"] + ARGS + [FEATURE]))
    for _, src in SILENT + LOUD:
        print("$ " + subprocess.list2cmdline(["dxc"] + ARGS + ["-Fo", "history-tmp.dxo", src]))
    print()

    head = ("%-14s %-12s %-4s | %-12s %-12s | %-9s %-9s | %-9s %-9s | %s"
            % ("release", "build date", "2021", "tmpl-row", "tmpl-col",
               "conc-row", "conc-col", "qual-tmpl", "qual-conc", "verdict"))
    print(head)
    print("-" * len(head))

    for tag, date, exe in builds():
        ver = subprocess.run([exe, "--version"], capture_output=True, text=True)
        feat_code, feat_text = compile_one(exe, FEATURE)
        can2021 = "yes" if feat_code == 0 else "NO"

        cells, orient, digest = {}, {}, {}
        for name, src in SILENT:
            code, o, d = hashed(exe, src)
            orient[name], digest[name] = o, d
            cells[name] = o if o else ("exit=%s" % code)
        for name, src in LOUD:
            code, text = compile_one(exe, src)
            cells[name] = "REJECTED" if REJECT in text else (
                "ok" if code == 0 else "exit=%s" % code)

        if feat_code != 0:
            verdict = "INVALID PROBE -- no HLSL 2021 templates: %s" % (
                feat_text.strip().splitlines()[-1] if feat_text.strip() else "no output")
        elif not (digest["conc-row"] and digest["conc-col"]):
            verdict = "INVALID PROBE -- concrete controls did not compile"
        elif digest["conc-row"] == digest["conc-col"]:
            verdict = "INSTRUMENT BROKEN -- concrete row/col are identical here"
        elif not (digest["tmpl-row"] and digest["tmpl-col"]):
            verdict = "INVALID PROBE -- template cases did not compile"
        elif digest["tmpl-row"] == digest["tmpl-col"]:
            verdict = "REPRO -- template row==col byte-identical"
        else:
            verdict = "no-repro -- template row and col differ"

        print("%-14s %-12s %-4s | %-12s %-12s | %-9s %-9s | %-9s %-9s | %s"
              % (tag, date, can2021, cells["tmpl-row"], cells["tmpl-col"],
                 cells["conc-row"], cells["conc-col"],
                 cells["qual-tmpl"], cells["qual-conc"], verdict))
        sys.stdout.flush()
        _ = ver

    print()
    print("Columns: 2021 = does control-feature-templates.hlsl compile at all.")
    print("  tmpl-row / tmpl-col = orientation emitted for the template-dependent")
    print("    matrix when row-major / column-major is requested via #pragma pack_matrix.")
    print("  conc-row / conc-col = the same pair with the template removed; these are")
    print("    the per-release instrument self-test and must differ.")
    print("  qual-tmpl / qual-conc = does `row_major matrix<...>` written directly on the")
    print("    member compile (`ok`) or hit the 'can only be used with a matrix type'")
    print("    diagnostic (`REJECTED`), with and without the template.")


if __name__ == "__main__":
    buf = []

    class Tee:
        def write(self, s):
            buf.append(s)

        def flush(self):
            pass

    real = sys.stdout
    sys.stdout = Tee()
    try:
        main()
    finally:
        sys.stdout = real
    real.write(triage.redact_paths("".join(buf)))
