#!/usr/bin/env python3
"""Per-release instrument self-test and control matrix for DXC issue 4486.

`bisect` answers "did the repro reproduce on release X". It cannot answer the
two questions this issue actually needs, because the symptom is a codegen
*shape* read out of a disassembler:

  1. Was the instrument working on release X?  The predicate reads `dxc -spirv`
     disassembly. A release that stopped printing a module, or printed it
     somewhere else, fails the predicate's anchor clause and would look exactly
     like a fix. Every row here records the anchor separately from the
     behaviour, so an instrument change cannot masquerade as a behaviour change.

  2. Does the predicate still *discriminate* on release X?  A predicate that
     fires on the reporter's own workaround measures nothing. `run --shader`
     only retargets the registered ground-truth compiler, so the controls have
     to be replayed against each release binary here.

Everything is derived from the releases table (`cached_path`), so downloaded
and test-seeded release trees are both covered. Commands are echoed exactly as
executed via subprocess.list2cmdline -- a transcribed command line is an
assertion nobody checks.

    python release-matrix.py            # writes manual-case-release-matrix.txt
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "scripts")
sys.path.insert(0, SCRIPTS)
import triage  # noqa: E402

TIMEOUT = 120

# Declared before running, mirroring match.json and expected.md. LOOPS means
# the predicate must match (a structured loop survives); FLAT means it must not.
CASES = [
    ("repro.hlsl", "LOOPS", "the reported nested [unroll] loops"),
    ("control-manual-unroll.hlsl", "FLAT", "reporter's workaround shape"),
    ("control-trivial.hlsl", "FLAT", "no loop at all -- SPIR-V availability"),
    ("control-runtime-loop.hlsl", "LOOPS", "uniform trip count -- detector alive"),
    ("minimal-nested.hlsl", "LOOPS", "minimal restatement of the repro"),
    ("minimal-manual.hlsl", "FLAT", "minimal restatement of the workaround"),
]

ANCHOR = re.compile(r'OpEntryPoint Fragment %\w+ "PS_bright_pass"')
LOOPMERGE = re.compile(r"^\s*OpLoopMerge ", re.MULTILINE)
DISASM_HEADER = re.compile(r"^; SPIR-V\b", re.MULTILINE)
NO_SPIRV = re.compile(r"SPIR-V CodeGen not available", re.IGNORECASE)

ARGS = ["-T", "ps_6_0", "-E", "PS_bright_pass", "-spirv"]


def run(exe, argv, cwd):
    line = subprocess.list2cmdline([triage.display_exe(exe)] + argv)
    try:
        p = subprocess.run([exe] + argv, cwd=cwd, capture_output=True,
                           text=True, timeout=TIMEOUT)
        return line, p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired:
        return line, None, "<timed out>"


def probe(exe, shader, cwd):
    line, rc, text = run(exe, ARGS + [shader], cwd)
    anchor = bool(ANCHOR.search(text))
    loops = len(LOOPMERGE.findall(text))
    return {
        "cmd": line, "rc": rc, "anchor": anchor, "loops": loops,
        "disasm": bool(DISASM_HEADER.search(text)),
        "no_spirv": bool(NO_SPIRV.search(text)),
        "verdict": "match" if (anchor and loops) else "no-match",
    }


def main():
    c = triage.con()
    rows = list(c.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE prerelease=0 AND bisectable=1 AND cached_path IS NOT NULL "
        "ORDER BY build_date, tag"))
    gt = c.execute("SELECT id, exe_path, version FROM compilers "
                   "WHERE id='main-debug'").fetchone()

    targets = [(r["tag"], r["cached_path"]) for r in rows]
    targets.append((gt["id"], gt["exe_path"]))

    out = []
    w = out.append
    w("# issue 4486 -- per-release instrument self-test and control matrix")
    w("#")
    w("# Generated by release-matrix.py; re-run it to re-derive this file.")
    w("# Each cell is the pair (anchor, OpLoopMerge count) from one run of")
    w("#   dxc " + " ".join(ARGS) + " <shader>")
    w("# anchor = the predicate's clause 1, `OpEntryPoint Fragment %<id>")
    w('#   "PS_bright_pass"`. anchor=no means that build measured NOTHING:')
    w("#   unmeasurable, not clean.")
    w("# loops  = clause 2, count of OpLoopMerge lines in the emitted module.")
    w("#")
    w("# Declared expectations (from expected.md, written before any run):")
    for shader, want, why in CASES:
        w(f"#   {want:5}  {shader:30} {why}")
    w("")

    deviations = []
    parse_warnings = []
    for tag, exe in targets:
        if not exe or not os.path.isfile(exe):
            w(f"== {tag}: no executable at {triage.display_exe(exe or '')}")
            w("")
            continue
        vline, vrc, vtext = run(exe, ["--version"], HERE)
        w(f"== {tag}")
        w(f"$ {vline}")
        w(f"[exit {vrc}] " + " | ".join(
            ln.strip() for ln in vtext.splitlines() if ln.strip()))
        for shader, want, _why in CASES:
            r = probe(exe, shader, HERE)
            got = "LOOPS" if r["verdict"] == "match" else "FLAT"
            if not r["anchor"]:
                got = "UNMEASURABLE"
            state = "ok" if got == want else "DEVIATION"
            if got == "UNMEASURABLE":
                state = ("expected -- no SPIR-V backend"
                         if r["no_spirv"] else "DEVIATION")
            w(f"$ {r['cmd']}")
            w(f"[exit {r['rc']}] anchor={'yes' if r['anchor'] else 'no'} "
              f"OpLoopMerge={r['loops']} disasm={'yes' if r['disasm'] else 'no'}"
              f" -> {got} (want {want}) [{state}]")
            if state == "DEVIATION":
                deviations.append(f"{tag} {shader}: got {got}, want {want}")
            # A harness that can return "nothing here" and "nothing matched"
            # through the same channel will eventually be believed. Say so
            # loudly when the text scored is not disassembly at all.
            if r["anchor"] and not r["disasm"]:
                parse_warnings.append(f"{tag} {shader}: anchor without "
                                      f"'; SPIR-V' disassembly header")
            if not r["anchor"] and not r["no_spirv"] and r["rc"] == 0:
                parse_warnings.append(f"{tag} {shader}: exit 0 but no anchor "
                                      f"and no SPIR-V-unavailable diagnostic")
        w("")

    w("== matrix self-test")
    for line in parse_warnings:
        w(f"MATRIX-4486: PARSE-WARNING: {line}")
    if not parse_warnings:
        w("MATRIX-4486: PARSE-OK: every scored run was either SPIR-V "
          "disassembly or an explicit SPIR-V-unavailable diagnostic")
    for line in deviations:
        w(f"MATRIX-4486: DEVIATION: {line}")
    if not deviations:
        w("MATRIX-4486: SELFTEST-PASS: every release agreed with the "
          "expectations declared above; the predicate discriminated the repro "
          "from the workaround on every build that has a SPIR-V backend")

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "manual-case-release-matrix.txt"), "w",
              newline="\n") as f:
        f.write(text)
    print(text)
    return 1 if deviations or parse_warnings else 0


if __name__ == "__main__":
    sys.exit(main())
