"""Generate manual-case captures for issue 4763.

Answers three questions the primary probe cannot:

  container   what actually lands in the emitted DXIL container, and whether the
              DXIL validator rejects the module (front end silent + validator
              catches it would be a materially weaker finding than a silent
              accept)
  asfiled     whether the reporter's exact command line (`-T ps_6_6 -E PSMain
              -Fh test.h`) behaves as the lowered `-T ps_6_0` command in cmd.txt
  fxc         what FXC does with the same source -- the issue is labelled
              `fxc-disagrees`

Every command is echoed with subprocess.list2cmdline(argv), i.e. exactly what
was executed, and every captured byte goes through triage.redact_paths().

Run from the issue directory:
    python make-manual-cases.py
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
BIN = os.path.join(triage.REPO_ROOT, "build", "Debug", "bin")
DXC = os.path.join(BIN, "dxc.exe")
DXV = os.path.join(BIN, "dxv.exe")
DXA = os.path.join(BIN, "dxa.exe")
FXC = (r"C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe")


def run(argv):
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       errors="replace")
    body = (p.stdout or "") + (p.stderr or "")
    return ("$ " + subprocess.list2cmdline(argv) + "\n"
            + "[exit] 0x%08X (%d)\n" % (p.returncode & 0xFFFFFFFF, p.returncode)
            + body.rstrip("\n") + "\n\n")


def write(name, header, chunks):
    text = triage.redact_paths(header + "".join(chunks))
    with open(os.path.join(HERE, name), "w", encoding="utf-8",
              newline="\n") as f:
        f.write(text)
    print("wrote", name)


def container():
    hdr = (
        "# manual case: what lands in the container, and does the DXIL "
        "validator object?\n"
        "# generated by make-manual-cases.py; commands echoed verbatim\n"
        "# compiler: main-debug\n\n")
    out = []
    for src, dxo in (("repro.hlsl", "repro.dxo"),
                     ("variant-resources-used.hlsl", "used.dxo"),
                     ("control-resources-global.hlsl", "global.dxo")):
        out.append(run([DXC, "-T", "ps_6_0", "-E", "PSMain", "-Fo", dxo, src]))
        out.append(run([DXV, dxo]))
        out.append(run([DXA, "-dumpreflection", dxo]))
    write("manual-case-container.txt", hdr, out)


def asfiled():
    hdr = (
        "# manual case: the reporter's command line, verbatim from the issue "
        "body\n"
        "#   -T ps_6_6 -E PSMain -Fh test.h test.hlsl\n"
        "# cmd.txt lowers the profile to ps_6_0 so every release back to the\n"
        "# v1.4.1907 floor can run it; this shows the deviation is inert.\n"
        "# generated by make-manual-cases.py\n"
        "# compiler: main-debug\n\n")
    out = [
        run([DXC, "-T", "ps_6_6", "-E", "PSMain", "-Fh", "test-asfiled.h",
             "repro.hlsl"]),
        run([DXC, "-T", "ps_6_6", "-E", "PSMain", "-Fo", "asfiled66.dxo",
             "repro.hlsl"]),
        run([DXC, "-T", "ps_6_0", "-E", "PSMain", "-Fo", "asfiled60.dxo",
             "repro.hlsl"]),
    ]
    for tag, path in (("ps_6_6", "asfiled66.dxo"), ("ps_6_0", "asfiled60.dxo")):
        full = os.path.join(HERE, path)
        if os.path.exists(full):
            with open(full, "rb") as f:
                blob = f.read()
            out.append("[%s container] %d bytes\n\n" % (tag, len(blob)))
    write("manual-case-asfiled.txt", hdr, out)


def fxc():
    hdr = (
        "# manual case: FXC on the same source (issue is labelled "
        "fxc-disagrees)\n"
        "# generated by make-manual-cases.py\n\n")
    out = [run([FXC, "/nologo", "/T", "ps_5_0", "/E", "PSMain",
                "/Fc", "fxc-repro.asm", "repro.hlsl"])]
    asm = os.path.join(HERE, "fxc-repro.asm")
    if os.path.exists(asm):
        with open(asm, encoding="utf-8", errors="replace") as f:
            out.append("--- fxc-repro.asm ---\n" + f.read().rstrip("\n")
                       + "\n\n")
    out.append(run([FXC, "/nologo", "/T", "ps_5_0", "/E", "PSMain",
                    "/Fc", "fxc-control.asm", "control-resources-global.hlsl"]))
    asm = os.path.join(HERE, "fxc-control.asm")
    if os.path.exists(asm):
        with open(asm, encoding="utf-8", errors="replace") as f:
            out.append("--- fxc-control.asm (CONTROL: same program with the "
                       "resources declared as ordinary globals) ---\n"
                       + f.read().rstrip("\n") + "\n\n")
    out.append(run([FXC, "/nologo", "/T", "ps_5_0", "/E", "PSMain",
                    "/Fc", "fxc-used.asm", "variant-resources-used.hlsl"]))
    asm = os.path.join(HERE, "fxc-used.asm")
    if os.path.exists(asm):
        with open(asm, encoding="utf-8", errors="replace") as f:
            head = f.read().split("ps_5_0")[0]
            out.append("--- fxc-used.asm, declarations only (the buffers are "
                       "read, so they survive) ---\n" + head.rstrip("\n")
                       + "\n\n")
    write("manual-case-fxc.txt", hdr, out)


if __name__ == "__main__":
    container()
    asfiled()
    fxc()
