"""Per-release control matrix for issue 4763.

`triage.py run --shader` retargets only the registered ground-truth compiler, so
per-release controls need an issue-local matrix. This one holds the sources fixed
and varies the release executable, taking each path from the catalog's
`releases.cached_path` column (which reconciles both physical release roots:
`.cache/compilers/releases/` and `build/tools/clang/test/dxc_releases/`).

For every stable release it runs, under the repro's own `-T ps_6_0 -E PSMain`:

  repro.hlsl                      the probe itself -- recorded here only to show
                                  it exited 0, i.e. that the release actually
                                  COMPILED it. An absence-based verdict from a
                                  release that failed to compile the shader
                                  would be measuring nothing.
  control-feature-presence.hlsl   smallest shader that puts a resource inside a
                                  cbuffer and uses it. Proves the release can
                                  express the construct under test.
  control-cbv-array.hlsl          POSITIVE control: a resource in a
                                  ConstantBuffer view ARRAY, which DXC does
                                  diagnose. Proves this release has a working
                                  diagnostic about resources in constant buffers
                                  and reaches it -- so silence on repro.hlsl is a
                                  gap in what is checked, not a compiler that
                                  never looks.
  control-resources-global.hlsl   NEGATIVE control: the same program written
                                  correctly. The predicate must not fire on it on
                                  any release.
  variant-cbv-scalar.hlsl         the title's literal wording, a scalar
                                  ConstantBuffer<T> holding a resource.

Prereleases are excluded: the issue text names none.

Every command is echoed with subprocess.list2cmdline(argv) and every captured
byte goes through triage.redact_paths().

Run from the issue directory:
    python release-matrix.py
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "..", "scripts"))
import triage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ARGS = ["-T", "ps_6_0", "-E", "PSMain"]

SOURCES = [
    ("repro", "repro.hlsl", "must compile (exit 0) for its probe to count"),
    ("feature-presence", "control-feature-presence.hlsl",
     "must compile (exit 0): release can express a resource in a cbuffer"),
    ("positive-control", "control-cbv-array.hlsl",
     "must be DIAGNOSED: 'object types not supported in cbuffer/tbuffer view "
     "arrays.'"),
    ("negative-control", "control-resources-global.hlsl",
     "correct code: must compile and must not match the predicate"),
    ("cbv-scalar", "variant-cbv-scalar.hlsl",
     "scalar ConstantBuffer<T> holding a resource -- the title's wording"),
]

DIAG = re.compile(r"^.*\b(error|warning)\s*:.*$", re.MULTILINE)


def stable_releases():
    conn = triage.con()
    rows = conn.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE prerelease = 0 AND cached_path IS NOT NULL "
        "ORDER BY build_date").fetchall()
    conn.close()
    return [(r["tag"], r["build_date"], r["cached_path"]) for r in rows]


def run(argv):
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       errors="replace")
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def main():
    out = ["# manual case: per-release control matrix for issue 4763\n",
           "# generated by release-matrix.py; commands echoed verbatim\n",
           "# sources fixed, release executable varied; prereleases excluded\n",
           "\n"]
    summary = []
    for tag, date, exe in stable_releases():
        out.append("=" * 72 + "\n%s  (build %s)\n" % (tag, date) + "=" * 72
                   + "\n")
        rc, ver = run([exe, "--version"])
        out.append("$ " + subprocess.list2cmdline([exe, "--version"])
                   + "\n[exit] 0x%08X\n%s\n" % (rc & 0xFFFFFFFF, ver.strip()))
        row = {"tag": tag}
        for name, src, why in SOURCES:
            argv = [exe] + ARGS + [src]
            rc, text = run(argv)
            diags = DIAG.findall(text)
            diaglines = [m.group(0).strip()
                         for m in DIAG.finditer(text)]
            out.append("\n-- %s (%s)\n" % (name, why))
            out.append("$ " + subprocess.list2cmdline(argv) + "\n")
            out.append("[exit] 0x%08X (%d)\n" % (rc & 0xFFFFFFFF, rc))
            out.append("[diagnostic lines] %d\n" % len(diags))
            for line in diaglines[:4]:
                out.append("    " + line + "\n")
            row[name] = (rc, len(diags))
        out.append("\n")
        summary.append(row)

    out.append("=" * 72 + "\nSUMMARY  (exit / diagnostic-line count)\n"
               + "=" * 72 + "\n")
    hdr = "%-16s" % "release" + "".join("%-22s" % n for n, _, _ in SOURCES)
    out.append(hdr + "\n")
    for row in summary:
        line = "%-16s" % row["tag"]
        for name, _, _ in SOURCES:
            rc, nd = row[name]
            line += "%-22s" % ("0x%08X/%d" % (rc & 0xFFFFFFFF, nd))
        out.append(line + "\n")

    text = triage.redact_paths("".join(out))
    with open(os.path.join(HERE, "manual-case-release-controls.txt"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote manual-case-release-controls.txt (%d releases)"
          % len(summary))


if __name__ == "__main__":
    main()
