#!/usr/bin/env python
"""Capture #2633's hand-run probes into manual-case-*.txt.

Everything the tool's own `run`/`bisect` can drive is captured by them. This
covers the two things they cannot:

  * the IMPORT-side flag matrix, which varies the target profile and the flag
    set rather than the source, and is cited in match.json's `note` as the
    evidence that `found undefined function` is invariant under all of them;
  * the `dxc -link` and `-default-linkage` questions, which are about the
    driver rather than about a shader.

SKILL.md step 11: generate every manual-case file from a script that echoes the
command it is about to run, and commit the generator next to its output. A
transcribed command line is an assertion checked by nobody.

Usage (from this directory):
    python probe-driver-cases.py [path\\to\\dxc.exe]
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DXC = sys.argv[1] if len(sys.argv) > 1 else os.environ.get(
    "DXC", os.path.join(HERE, "..", "..", "..", "..", "..", "..",
                        "build", "Debug", "bin", "dxc.exe"))


def run(argv, out):
    """Run one command, echoing exactly what was executed."""
    line = subprocess.list2cmdline(["dxc"] + argv)
    out.append("$ " + line)
    try:
        p = subprocess.run([DXC] + argv, cwd=HERE, capture_output=True,
                           text=True, errors="replace", timeout=300)
        rc, text = p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired:
        rc, text = None, "(timeout)"
    out.append("[exit] " + ("TIMEOUT" if rc is None
                            else "0x%08X" % (rc & 0xFFFFFFFF)))
    out.append(text.rstrip("\n"))
    out.append("")
    return rc, text


def version():
    p = subprocess.run([DXC, "--version"], capture_output=True, text=True)
    return (p.stdout + p.stderr).strip()


def write(name, header, lines):
    path = os.path.join(HERE, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by probe-driver-cases.py -- do not hand-edit\n")
        f.write("# dxc: %s\n" % version())
        f.write("# exe: %s\n" % os.path.normpath(DXC))
        f.write("#\n")
        for h in header:
            f.write("# %s\n" % h)
        f.write("\n" + "\n".join(lines))
    print("wrote " + name)


def flag_matrix():
    """Is `found undefined function` invariant under profile and flags?"""
    out, verdicts = [], []
    cases = [
        ["-T", "lib_6_3", "-spirv", "repro.hlsl"],
        ["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5",
         "repro.hlsl"],
        ["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5", "-fcgl",
         "repro.hlsl"],
        ["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5", "-Vd",
         "repro.hlsl"],
        # lib_6_6 is the profile in @s-perron's own https://godbolt.org/z/4s8xaEdTK
        ["-T", "lib_6_6", "-spirv", "-fspv-target-env=universal1.5",
         "repro.hlsl"],
        ["-T", "lib_6_9", "-spirv", "-fspv-target-env=universal1.5",
         "repro.hlsl"],
        # ...and the same six questions asked of the EXPORT half.
        ["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5",
         "lib-export.hlsl"],
    ]
    for argv in cases:
        _, text = run(argv, out)
        verdicts.append("found undefined function" in text)
    out.append("SUMMARY: 'found undefined function' in %d of the %d import-side"
               " cases" % (sum(verdicts[:6]), 6))
    write("manual-case-flag-matrix.txt", [
        "Is the IMPORT-side diagnostic invariant under target profile and flag",
        "set?  If some profile or flag already produced an Import decoration",
        "instead, the capability would be partly present and match.json would",
        "be measuring an artefact of one configuration.",
    ], out)


def driver_cases():
    """Can any existing driver-level facility already do this?"""
    out = []
    out.append("### 1. -default-linkage external: a DXIL knob. Does it drive")
    out.append("###    SPIR-V linkage, i.e. export without the `export` keyword?")
    out.append("")
    run(["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5",
         "-default-linkage", "external",
         "variant-default-linkage-external.hlsl"], out)
    out.append("### 2. ...and the same source WITH the `export` keyword, as the")
    out.append("###    control: this is the form that does work.")
    out.append("")
    run(["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5",
         "lib-export.hlsl"], out)
    out.append("### 3. dxc -link is the DXIL linker. Fed SPIR-V, what happens?")
    out.append("")
    run(["-T", "lib_6_3", "-spirv", "-fspv-target-env=universal1.5", "-Fo",
         "lib-export.spv", "lib-export.hlsl"], out)
    run(["-T", "lib_6_3", "-spirv", "-link", "-Fo", "linked.spv",
         "lib-export.spv"], out)
    for junk in ("lib-export.spv", "linked.spv"):
        p = os.path.join(HERE, junk)
        if os.path.isfile(p):
            os.remove(p)
    write("manual-case-driver-cases.txt", [
        "Is there already a driver-level route to a relocatable SPIR-V module?",
        "These are questions about dxc's own options rather than about a",
        "shader, so `run`/`bisect` (one profile, one source) cannot ask them.",
    ], out)


if __name__ == "__main__":
    if not os.path.isfile(DXC):
        sys.exit("no dxc at %s -- pass a path or set DXC" % DXC)
    flag_matrix()
    driver_cases()
