"""Capture cdb sessions for #4307 into manual-case-*.txt.

Run from anywhere:  python capture-cdb.py

Two things this exists for:

* The command line in a committed capture is an assertion about what was run, and a
  transcribed one is checked by nobody. This script prints
  `subprocess.list2cmdline(argv)` -- exactly what it executed.
* cdb output is mostly noise (the Debugger Extensions Gallery preamble and ~40
  ModLoad lines), and it embeds this machine's checkout path. Filtering and the
  `<repo>` redaction happen here, in the generator, rather than by hand-editing a
  capture afterwards.

Nothing in the compiler's own diagnostic text is rewritten: only the absolute path
prefix of this checkout is replaced with `<repo>`, and `/`-separated forms too.
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[5]
assert REPO.name == "DirectXShaderCompiler", REPO
DXC = REPO / "build" / "Debug" / "bin" / "dxc.exe"
CDB = Path(r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe")

DXC_ARGS = [
    "repro.hlsl", "/Zi", "/E", "main", "/Od",
    "/Fo", "test.mso", "/Tms_6_6", "-Qembed_debug",
]

NOISE = re.compile(
    r"^(ModLoad:|\s*$|\*{4,}|>{4,}|\s+-{2,}>|\s+(ExtensionRepository|UseExperimental"
    r"|AllowNuget|NonInteractiveNuget|AllowParallel|EnableRedirect|-- Configuring"
    r"|Response\s|Deferred\s)|Symbol search path|Executable search path|\+-{4,}"
    r"|\|.*\||Microsoft \(R\) Windows Debugger|Copyright \(c\) Microsoft"
    r"|CommandLine:|Path validation summary|srv\*|NatVis script )"
)


def redact(text: str) -> str:
    for sep in ("\\", "/"):
        text = text.replace(str(REPO).replace("\\", sep), "<repo>")
    return text


def capture(name: str, cdb_cmd: str, what: str) -> None:
    argv = [str(CDB), "-c", cdb_cmd, str(DXC), *DXC_ARGS]
    proc = subprocess.run(
        argv, cwd=HERE, capture_output=True, text=True, errors="replace"
    )

    def keep(stream: str) -> list[str]:
        return [redact(ln) for ln in stream.splitlines() if not NOISE.match(ln)]

    out, err = keep(proc.stdout), keep(proc.stderr)
    body = [
        f"# what: {what}",
        "# generated by: capture-cdb.py  (re-run it to reproduce this file)",
        "# cwd: <repo>/.github/skills/dxc-issue-triage/data/issues/4307",
        f"# cdb exit: {proc.returncode}   (the debugger's status, not dxc's)",
        "",
        "$ " + redact(subprocess.list2cmdline(argv)),
        "",
        "--- cdb session (stdout) ---",
        *out,
        "",
        "--- dxc stderr ---",
        *err,
        "",
    ]
    (HERE / name).write_text("\n".join(body), encoding="utf-8", newline="\n")
    print(f"wrote {name}  (stdout {len(out)} / stderr {len(err)} lines kept)")


def main() -> int:
    if not CDB.exists():
        sys.exit(f"cdb not found at {CDB}")
    if not DXC.exists():
        sys.exit(f"dxc not found at {DXC}")

    capture(
        "manual-case-assert-stack.txt",
        "g;kn 40;q",
        "Debug ground truth: run to the DXASSERT trap and print the stack",
    )
    capture(
        "manual-case-release-path.txt",
        "g;gh;g;q",
        "step PAST the trap ('gh' emulates NDEBUG) to see what a Release build "
        "of the same source would print -- this is the path a release user hits",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
