"""Ask Compiler Explorer whether hlsl_clang_trunk can answer #4307 at all.

Run from anywhere:  python clang-probe.py

The skill suggests a Clang pane for missing/poor-diagnostic issues, because "has
the successor front end already solved this?" is often more useful than "does DXC
still do it?". But a Clang error is not evidence until it has a control: Clang's
HLSL support is uneven, and a pane full of complaints about the shader stage says
nothing about the issue.

So this probes two sources through CE's public compile API:

  A. a trivial, obviously-valid mesh shader  -- the control
  B. the issue's own repro                   -- the case

If A already fails, the pane cannot distinguish "Clang diagnoses #4307" from
"Clang cannot compile mesh shaders", and no Clang pane should be published.
Output goes to manual-case-clang-probe.txt.
"""

import json
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
API = "https://godbolt.org/api/compiler/{}/compile"
COMPILER = "hlsl_clang_trunk"
ARGS = "-T ms_6_6 -E main"

CONTROL = """\
struct V { float4 p : SV_POSITION; };

[numthreads(1, 1, 1)]
[outputtopology("triangle")]
void main(out vertices V verts[1], out indices uint3 tris[1])
{
    SetMeshOutputCounts(1, 1);
    verts[0].p = float4(0, 0, 0, 1);
    tris[0] = uint3(0, 0, 0);
}
"""


def compile_on_ce(source: str) -> tuple[int, str]:
    payload = {
        "source": source,
        "options": {
            "userArguments": ARGS,
            "filters": {"execute": False, "intel": False, "demangle": False},
        },
        "lang": "hlsl",
        "allowStoreCodeDebug": False,
    }
    req = urllib.request.Request(
        API.format(COMPILER),
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=90) as r:
        body = json.load(r)
    text = "\n".join(
        ln.get("text", "") for ln in (body.get("stdout", []) + body.get("stderr", []))
    )
    return body.get("code", -1), text


def main() -> int:
    lines = [
        "# what: can hlsl_clang_trunk on Compiler Explorer answer #4307?",
        "# generated by: clang-probe.py  (re-run it to reproduce this file)",
        f"# compiler: {COMPILER}    args: {ARGS}",
        "",
    ]
    cases = [
        ("CONTROL: trivial valid mesh shader", CONTROL),
        ("CASE: the issue's repro", (HERE / "repro.hlsl").read_text(encoding="utf-8")),
    ]
    control_rc = None
    for name, src in cases:
        try:
            rc, text = compile_on_ce(src)
        except Exception as exc:  # network failure is not a negative result
            sys.exit(f"CE request failed for {name!r}: {exc!r}")
        if control_rc is None:
            control_rc = rc
        lines += ["=" * 74, f"## {name}", f"exit: {rc}", "", text.rstrip(), ""]

    verdict = (
        "control compiled cleanly, so a Clang pane WOULD be meaningful"
        if control_rc == 0
        else "control already fails, so any Clang error on the repro is about the "
        "stage, not about #4307 -- do not publish a Clang pane"
    )
    lines += ["=" * 74, f"CONCLUSION: {verdict}", ""]
    (HERE / "manual-case-clang-probe.txt").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n"
    )
    print(f"control exit={control_rc}: {verdict}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
