"""Release matrix for #4307.

Run from anywhere:  python release-matrix.py

`triage.py bisect` answers one question -- does the repro, exactly as filed,
still produce the reported diagnostic -- across the stable releases. Three things
it cannot answer are needed here, and all three want the same 2-D sweep:

1. **Are v1.4.1907 and v1.5.2010 really unprobeable?** `bisect` demoted them, but
   an `invalid-probe` on the repro alone is ambiguous: it can mean the release
   predates the feature, or that something unrelated in the repro was rejected.
   The feature-presence control (a mesh shader that differs from the repro only
   in not reading its output) separates those.
2. **Does the symptom depend on `ms_6_6`?** Mesh shaders exist from SM 6.5, so
   re-running at `ms_6_5` says whether the history is genuinely bounded by SM 6.6
   availability or by the defect.
3. **The reporter's third ask.** The body says the same error appears when the
   output member is passed to a function parameter "even if the parameter of the
   function is marked as out". On today's build it does not -- `out` compiles
   clean and `inout` fails -- so the question is whether that was ever true.

Self-test: the control must compile cleanly on at least one release, or the
harness is measuring nothing and says so loudly rather than reporting a tidy
matrix of failures. Second self-test: `elem-read` must produce the existing
mesh-output-read diagnostic on at least one release, or the good-diagnostic
column is measuring nothing either.
"""

import re
import sqlite3
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[5]
assert REPO.name == "DirectXShaderCompiler", REPO
DB = REPO / ".github" / "skills" / "dxc-issue-triage" / ".cache" / "triage.db"
SCRATCH = HERE / "scratch"

# Deliberately NOT test.mso: the ground-truth runs driven by triage.py write
# that name, and a sweep sharing it would silently restamp their artifacts.
CASES = [
    ("repro ms_6_6", "repro.hlsl", "ms_6_6"),
    ("repro ms_6_5", "repro.hlsl", "ms_6_5"),
    ("control ms_6_6", "control-no-readback.hlsl", "ms_6_6"),
    ("control ms_6_5", "control-no-readback.hlsl", "ms_6_5"),
    ("out-param ms_6_6", "case-out-param.hlsl", "ms_6_6"),
    ("out-param-elem ms_6_6", "case-out-param-elem.hlsl", "ms_6_6"),
    ("inout-param ms_6_6", "case-inout-param.hlsl", "ms_6_6"),
    ("elem-read ms_6_6", "case-elem-read.hlsl", "ms_6_6"),
    ("elem-read ms_6_5", "case-elem-read.hlsl", "ms_6_5"),
]

GOOD_DIAG = "output arrays of a mesh shader can not be read from"

INTERESTING = re.compile(r"(error|warning|Internal compiler error|Validation failed)", re.I)


def redact(text: str) -> str:
    for sep in ("\\", "/"):
        text = text.replace(str(REPO).replace("\\", sep), "<repo>")
    return text


def first_diag(text: str) -> str:
    for line in text.splitlines():
        if INTERESTING.search(line):
            return line.strip()
    return "(no diagnostic)"


def run(exe: Path, shader: str, profile: str, tag: str, case: str):
    out = SCRATCH / f"{tag}-{case.replace(' ', '_')}.mso"
    argv = [
        str(exe), shader, "/Zi", "/E", "main", "/Od",
        "/Fo", str(out), f"/T{profile}", "-Qembed_debug",
    ]
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True, errors="replace")
    return p.returncode, redact(p.stdout + p.stderr), redact(subprocess.list2cmdline(argv))


def main() -> int:
    SCRATCH.mkdir(exist_ok=True)
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    rows = con.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE prerelease=0 AND cached_path IS NOT NULL ORDER BY build_date"
    ).fetchall()
    con.close()
    if not rows:
        sys.exit("no cached stable releases; run `triage.py bisect` first")

    lines = [
        "# what: #4307 across every cached stable release, six configurations each",
        "# generated by: release-matrix.py  (re-run it to reproduce this file)",
        "# cwd: <repo>/.github/skills/dxc-issue-triage/data/issues/4307",
        "# note: exit 0x80004005 (2147500037) is E_FAIL, which is what dxc returns for",
        "#       ANY diagnosed error on Windows -- it is not a crash.",
        "",
    ]
    control_ok = 0
    good_diag_ok = 0
    summary = []

    for tag, date, exe_path in rows:
        exe = Path(exe_path)
        ver = subprocess.run(
            [str(exe), "--version"], capture_output=True, text=True, errors="replace"
        )
        lines += ["=" * 78, f"{tag}   ({date})", f"  exe:     {redact(str(exe))}",
                  f"  version: {ver.stdout.strip() or ver.stderr.strip()}", ""]
        row = {"tag": tag}
        for case, shader, profile in CASES:
            rc, text, cmd = run(exe, shader, profile, tag, case)
            diag = first_diag(text)
            row[case] = (rc, diag)
            if case == "control ms_6_6" and rc == 0:
                control_ok += 1
            if case == "elem-read ms_6_6" and GOOD_DIAG in text:
                good_diag_ok += 1
            lines += [f"  $ {cmd}", f"    [{case}] exit={rc} (0x{rc & 0xFFFFFFFF:08X})",
                      f"    {diag}", ""]
        summary.append(row)

    lines += ["=" * 78, "SUMMARY  (exit code / first diagnostic)", ""]
    for row in summary:
        lines.append(f"{row['tag']}")
        for case, _, _ in CASES:
            rc, diag = row[case]
            lines.append(f"    {case:<20} 0x{rc & 0xFFFFFFFF:08X}  {diag[:96]}")
        lines.append("")

    lines += [
        "=" * 78,
        f"HARNESS SELF-TEST 1: control ms_6_6 compiled cleanly on {control_ok}/{len(rows)} "
        f"releases -- {'PASS' if control_ok else 'FAIL: the harness produced no clean '
        'compile anywhere, so every failure above may be an artefact of the harness'}",
        f"HARNESS SELF-TEST 2: elem-read ms_6_6 emitted the existing mesh-output-read "
        f"diagnostic on {good_diag_ok}/{len(rows)} releases -- "
        f"{'PASS' if good_diag_ok else 'FAIL: the good-diagnostic column never fired, '
        'so its absence on the repro proves nothing'}",
        "",
    ]
    (HERE / "manual-case-release-matrix.txt").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n"
    )
    print(f"wrote manual-case-release-matrix.txt  ({len(rows)} releases x {len(CASES)} cases)")
    print(f"self-test 1: control compiled cleanly on {control_ok}/{len(rows)} releases")
    print(f"self-test 2: good diagnostic fired on {good_diag_ok}/{len(rows)} releases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
