"""Generate manual-case-miscompile-matrix.txt for #3835.

The second half of this issue. tex3d's minimal repro

    int array1[1];
    int main() : OUT { int error_expr[] = array1; return error_expr[0]; }

asserts on a Debug build but, per his 2024-08-28 comment, "produces incorrect
code on release build". This harness measures that claim on every cached stable
release rather than repeating it, and pairs each measurement with the same
shader written with a COMPLETE array type (control-minimal-sized.hlsl), which
is the only difference between the two inputs.

Why a harness and not a `match-*.json` predicate: the symptom lives in the DXIL
disassembly, and on these Windows binaries `-Fc -` writes nothing to a pipe
(measured: exit 0, zero bytes on stdout and stderr), so no stdout predicate can
see it. `-Fc <file>` is the only way to get the text, which needs a command
chain the runner does not express. SKILL.md's rule for that case is to find the
producing instrument rather than manufacture a hollow predicate.

Self-consistency, per SKILL.md ("a harness that can return 'nothing here' and
'nothing matched' through the same channel will eventually be believed"): every
parse asserts it found an entry definition and prints MISCOMPILE-3835:
PARSE-WARNING when it does not, and the run ends with a SELFTEST line that fails
loudly if the control never produced a storeOutput on any build.

Run from the issue directory:  python make-miscompile-matrix.py
"""
import os
import re
import shutil
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))
REPO = os.path.abspath(os.path.join(SKILL, os.pardir, os.pardir, os.pardir))
CACHE = os.path.join(SKILL, ".cache")
DB = os.path.join(CACHE, "triage.db")
GROUND_TRUTH = os.path.join(REPO, "build", "Debug", "bin", "dxc.exe")
SCRATCH = os.path.join(HERE, "dis")

SHADERS = [("minimal-repro.hlsl", "incomplete array  int error_expr[]"),
           ("control-minimal-sized.hlsl", "CONTROL: sized  int error_expr[1]")]
ARGS = ["-T", "vs_6_0", "-E", "main"]


def show(argv):
    """Echo what ran, with this machine's roots tokenised. Cache first: it
    lives inside the repo, so replacing the repo root first would hide it."""
    return subprocess.list2cmdline(argv).replace(CACHE, "<cache>") \
                                        .replace(REPO, "<repo>")


def builds():
    """Stable releases with a usable dxc, oldest first, then ground truth.

    Read from the triage database rather than by walking a directory: the
    catalog reconciles two physical release roots and orders by the build date
    encoded in the asset name, not by publish date.
    """
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, cached_path FROM releases "
        "WHERE prerelease = 0 AND build_date IS NOT NULL "
        "ORDER BY build_date").fetchall()
    con.close()
    out = []
    for r in rows:
        exe = r["cached_path"]
        if exe and os.path.isfile(exe):
            out.append((r["tag"], exe))
    out.append(("main-debug", GROUND_TRUTH))
    return out


ENTRY_RE = re.compile(r"^define void @main\(\).*?^\}", re.M | re.S)


def analyse(dis_path, tag, shader):
    """Return (entry_body_lines, has_store_output, note)."""
    if not os.path.isfile(dis_path):
        return [], False, "no disassembly produced"
    text = open(dis_path, encoding="utf-8", errors="replace").read()
    m = ENTRY_RE.search(text)
    if not m:
        print("MISCOMPILE-3835: PARSE-WARNING: no 'define void @main()' found "
              "in the disassembly from %s for %s -- treat this row as "
              "unmeasured, not as an absence." % (tag, shader))
        return [], False, "entry definition not found"
    body = [ln.strip() for ln in m.group(0).splitlines()]
    return body, ("storeOutput" in m.group(0)), ""


def main():
    print("# issue: 3835")
    print("# generated by: make-miscompile-matrix.py (committed beside this file)")
    print("# question: does the minimal repro silently emit an entry point that")
    print("#           never writes its output, on shipped Release compilers?")
    print("# self-test: the sized-array control must emit a storeOutput call;")
    print("#            if it never does on any build the instrument is broken")
    print("#            and every 'absence' below is meaningless.")
    print()
    os.makedirs(SCRATCH, exist_ok=True)
    control_ever_stored = False
    try:
        for shader, why in SHADERS:
            print("=" * 78)
            print("%s   (%s)" % (shader, why))
            print("=" * 78)
            print("%-16s %-12s %-14s %s"
                  % ("build", "exit", "storeOutput", "entry point body"))
            for tag, exe in builds():
                dis = os.path.join(SCRATCH, "dis-%s.txt" % tag)
                if os.path.exists(dis):
                    os.remove(dis)
                argv = [exe, shader] + ARGS + ["-Fc", dis]
                p = subprocess.run(argv, capture_output=True, text=True,
                                   errors="replace", cwd=HERE, timeout=300)
                rc = p.returncode & 0xFFFFFFFF
                body, stored, note = analyse(dis, tag, shader)
                control_ever_stored = control_ever_stored or (
                    stored and shader == "control-minimal-sized.hlsl")
                summary = note or " ".join(body[1:-1])[:78] or "(empty body)"
                print("%-16s 0x%08X   %-14s %s"
                      % (tag, rc, "yes" if stored else "no", summary))
                if rc != 0:
                    err = (p.stdout + p.stderr).strip().splitlines()
                    print("%-16s %s" % ("", err[-1] if err
                                        else "(no diagnostic printed)"))
            print()
        print("$ example command: " + show(
            [builds()[-2][1], "minimal-repro.hlsl"] + ARGS
            + ["-Fc", os.path.join(SCRATCH, "dis-<tag>.txt")]))
        print()
        print("SELFTEST control-emits-storeOutput=%s"
              % ("pass" if control_ever_stored else "FAIL"))
        if not control_ever_stored:
            sys.exit("SELFTEST FAILED: the sized-array control never produced "
                     "a storeOutput, so this harness cannot distinguish a "
                     "miscompile from a parsing failure.")
    finally:
        shutil.rmtree(SCRATCH, ignore_errors=True)


if __name__ == "__main__":
    main()
