"""Compiler Explorer controls for the Clang pane on the #3835 triage.

The published multi-pane link shows `hlsl_clang_trunk` rejecting the two
crashing declarations with "array initializer must be an initializer list".
SKILL.md: a Clang error is not evidence until it has a control, because
Clang's HLSL support is incomplete and it fails on inputs unrelated to the
issue -- and the same pane also emits "unknown HLSL semantic 'SV_ClipDistance'"
noise, which proves the point.

Three controls, all through POST /api/compiler/<id>/compile so the full text
is available (the CE pane UI is not needed):

  CASE A  pane-runs control: a trivial vertex shader with the *same* Clang
          flags. Must succeed, or every error above is about the stage.
  CASE B  same-subject near miss, unsized: the minimal repro restated as a
          compute shader so Clang's complete stage support is used and the
          clip-distance noise is gone. Expect the same array-initializer
          error, on the array-assignment line only.
  CASE C  same-subject near miss, sized: CASE B with one token changed,
          `[1]` instead of `[]`. Expect a clean compile -- this is what
          separates "Clang rejects this initialisation form" from "Clang
          rejects this shader".

The same three shaders also go through `dxc_trunk` (Release, Linux) so the
comparison is on identical input.

Cases F/G/H do the same for FXC, so the thread's "FXC compiles this" claim is
measured rather than repeated on trust. FXC gets its own control pair for the
same reason Clang does.

Re-derive with:  python make-godbolt-clang-controls.py
"""

import json
import os
import re
import urllib.request

API = "https://godbolt.org/api/compiler/{cid}/compile"
SGR = re.compile(r"\x1b\[[0-9;]*m")

HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(HERE, "repro.hlsl"), "r", encoding="utf-8") as _fh:
    FILED_SHADER = _fh.read()

TRIVIAL_VS = """float4 vert_main(float4 pos : POSITION) : SV_Position {
    return pos;
}
"""

UNSIZED_CS = """RWBuffer<int> Out : register(u0);
static int array1[1] = { 7 };

[numthreads(1, 1, 1)]
void main() {
    int error_expr[] = array1;
    Out[0] = error_expr[0];
}
"""

SIZED_CS = UNSIZED_CS.replace("int error_expr[]", "int error_expr[1]")

CLANG = "hlsl_clang_trunk"
DXC = "dxc_trunk"
FXC = "fxc_10_0_26100"

CASES = [
    ("A", "pane-runs control: trivial vertex shader, Clang, same flags",
     CLANG, "-T vs_6_0 -E vert_main -fsyntax-only", TRIVIAL_VS,
     "expect: clean compile (exit 0)"),
    ("B", "near miss, UNSIZED array assignment, Clang, compute",
     CLANG, "-T cs_6_0 -E main -fsyntax-only", UNSIZED_CS,
     "expect: rejected, on the array-assignment line"),
    ("C", "near miss, SIZED array assignment, Clang, compute",
     CLANG, "-T cs_6_0 -E main -fsyntax-only", SIZED_CS,
     "expect: clean compile (exit 0)"),
    ("D", "near miss, UNSIZED array assignment, DXC trunk, compute",
     DXC, "-T cs_6_0 -E main", UNSIZED_CS,
     "expect: the DXC defect, or silent bad codegen"),
    ("E", "near miss, SIZED array assignment, DXC trunk, compute",
     DXC, "-T cs_6_0 -E main", SIZED_CS,
     "expect: clean compile (exit 0)"),
    ("F", "the filed shader, verbatim, through FXC",
     FXC, "/T vs_5_0 /E vert_main", FILED_SHADER,
     "expect: clean compile if the thread's FXC claim holds"),
    ("G", "near miss, UNSIZED array assignment, FXC, compute",
     FXC, "/T cs_5_0 /E main", UNSIZED_CS,
     "expect: clean compile"),
    ("H", "pane-runs control: SIZED array assignment, FXC, compute",
     FXC, "/T cs_5_0 /E main", SIZED_CS,
     "expect: clean compile (exit 0)"),
]


def compile_one(cid, args, source):
    payload = {
        "source": source,
        "options": {
            "userArguments": args,
            "filters": {"execute": False, "intel": False, "demangle": False},
            "compilerOptions": {"skipAsm": False},
        },
        "lang": "hlsl",
        "allowStoreCodeDebug": True,
    }
    req = urllib.request.Request(
        API.format(cid=cid),
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as fh:
        return json.loads(fh.read().decode("utf-8"))


def text_of(result, key):
    return "\n".join(SGR.sub("", line.get("text", "")) for line in result.get(key, []))


def main():
    out = []
    out.append("# Compiler Explorer controls for the Clang pane.")
    out.append("# Generated by make-godbolt-clang-controls.py -- rerun to re-derive.")
    out.append("# ANSI colour escapes are stripped; nothing else is edited.")
    out.append("# CE runs Linux Release builds.")
    verdicts = {}
    for tag, title, cid, args, source, expectation in CASES:
        result = compile_one(cid, args, source)
        code = result.get("code")
        stderr = text_of(result, "stderr")
        stdout = text_of(result, "stdout")
        asm = "\n".join(
            SGR.sub("", line.get("text", "")) for line in result.get("asm", [])
        )
        verdicts[tag] = (code, stderr)
        out.append("")
        out.append("=" * 74)
        out.append("# CASE %s  %s" % (tag, title))
        out.append("# compiler: %s" % cid)
        out.append("# args:     %s" % args)
        out.append("# %s" % expectation)
        out.append("# exit:     %s" % code)
        out.append("")
        out.append("--- source ---")
        out.append(source.rstrip("\n"))
        out.append("--- stderr ---")
        out.append(stderr if stderr.strip() else "(empty)")
        if stdout.strip():
            out.append("--- stdout ---")
            out.append(stdout)
        out.append("--- output pane (first 12 lines) ---")
        out.append("\n".join(asm.splitlines()[:12]) if asm.strip() else "(empty)")

    out.append("")
    out.append("=" * 74)
    out.append("# SELFTEST")
    a_code = verdicts["A"][0]
    b_code, b_err = verdicts["B"]
    c_code = verdicts["C"][0]
    d_code = verdicts["D"][0]
    e_code = verdicts["E"][0]
    checks = [
        ("clang-pane-runs", a_code == 0),
        ("clang-rejects-unsized", b_code != 0 and "initializer" in b_err),
        ("clang-accepts-sized", c_code == 0),
        ("clang-difference-is-one-token", b_code != 0 and c_code == 0),
        ("dxc-sized-compiles", e_code == 0),
        ("fxc-pane-runs", verdicts["H"][0] == 0),
        ("fxc-accepts-filed-shader", verdicts["F"][0] == 0),
        ("fxc-accepts-unsized", verdicts["G"][0] == 0),
    ]
    for name, ok in checks:
        out.append("%s=%s" % (name, "pass" if ok else "FAIL"))
    out.append("dxc-unsized-exit=%s (recorded, not asserted)" % d_code)
    text = "\n".join(out) + "\n"
    with open("manual-case-godbolt-clang-controls.txt", "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text[-1400:])


if __name__ == "__main__":
    main()
