"""Generate manual-case-assert-stack.txt for #3835.

Two questions this answers, neither of which a plain `dxc` capture can:

1. **Which assert fires, and where.** tex3d's 2024-08-28 comment attributes the
   failure to `assert(!isIncompleteType() && "This doesn't make sense for
   incomplete types")` under `Type::isConstantSizeType` from
   `CodeGenFunction::EmitAutoVarAlloca`. A stack either shows that or it does
   not; quoting the comment back is not evidence.

2. **What the Release build does with the assert removed.** cdb's `gh`
   ("go handled") continues past the trapped assert, which emulates NDEBUG --
   it runs the code a Release build would have run. That is how a Debug binary
   can show the reporter's Release symptom without building Release.

Both invocations are echoed with subprocess.list2cmdline, so the file records
exactly what ran rather than a transcription of it. Output is filtered (not
edited) by KEEP below: a raw cdb dump is ~200 lines of module loads.

Run from the issue directory:  python make-assert-stack.py
"""
import os
import re
import subprocess
import sys

CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
# Anchored on the repository name rather than an absolute prefix, so the script
# is portable and leaks nobody's directory layout. SKILL.md's redaction rule:
# where a path is executable logic, make it machine-independent instead of
# search-and-replacing it afterwards.
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, *([os.pardir] * 6)))
DXC = os.environ.get("DXC_EXE",
                     os.path.join(REPO, "build", "Debug", "bin", "dxc.exe"))


def show(argv):
    """Echo exactly what ran, with this machine's repo root tokenised."""
    return subprocess.list2cmdline(argv).replace(REPO, "<repo>")


# Lines worth keeping: the assert text, exception records, stack frames, the
# .lastevent line, and any dxc diagnostic. Everything else cdb prints is
# module-load and symbol-path noise.
KEEP = re.compile(
    r"(Error: assert|Assertion|assert\(|"
    r"chance\)|Unknown exception|Access violation|"
    r"^ *# Child-SP|^[0-9a-f]{2} [0-9a-f]{8}`|"
    r"^dxcompiler!|^dxc!|"
    r"Last event|lastevent|"
    r"Internal compiler error|error:|warning:|"
    r"^!dx\.|^define |^target datalayout|^; <label>|"
    r"quit:|^Debugger)", re.M)


def run(title, why, cdb_cmd, dxc_args, keep=KEEP, limit=32):
    argv = [CDB, "-c", cdb_cmd, DXC] + dxc_args
    print("=" * 74)
    print(title)
    print(why)
    print("$ " + show(argv))
    p = subprocess.run(argv, capture_output=True, text=True,
                       errors="replace", timeout=900)
    print("[exit] %d (0x%08X)" % (p.returncode, p.returncode & 0xFFFFFFFF))
    lines = [ln.rstrip() for ln in (p.stdout + p.stderr).splitlines()
             if keep.search(ln)]
    print("--- filtered cdb output (%d of %d lines kept) ---"
          % (len(lines), len((p.stdout + p.stderr).splitlines())))
    for ln in lines[:limit]:
        print(ln)
    if len(lines) > limit:
        print("... %d further kept lines omitted by limit=%d"
              % (len(lines) - limit, limit))
    print()


def main():
    if not os.path.isfile(CDB):
        sys.exit("cdb.exe not found at %s" % CDB)
    if not os.path.isfile(DXC):
        sys.exit("dxc.exe not found at %s; set DXC_EXE" % DXC)
    print("# issue: 3835")
    print("# generated by: make-assert-stack.py (committed beside this file)")
    print("# dxc: <repo>/build/Debug/bin/dxc.exe")
    print("# note: cdb's inner quotes are written bare here; list2cmdline adds")
    print("#       the backslash escaping cdb needs. Pre-escaping them yields")
    print("#       \\\\\\\" on the wire and cdb answers 'Quotes required in'.")
    print()

    run("CASE 1 -- which assert fires (minimal repro)",
        "Break on the assert's e0000001 exception, print 14 frames, continue.",
        'sxe -c "kn 14; gh" e0000001; g; q',
        ["minimal-repro.hlsl", "-T", "vs_6_0", "-E", "main"])

    run("CASE 2 -- which assert fires (the shader as filed)",
        "Same, on repro.hlsl with cmd.txt's arguments.",
        'sxe -c "kn 14; gh" e0000001; g; q',
        ["repro.hlsl", "-T", "vs_5_0", "-E", "vert_main", "-Zi",
         "-Qembed_debug"])

    run("CASE 3 -- NDEBUG emulation, filed shader",
        "gh past every assert so the Debug binary runs the Release path. "
        "The reporter saw 0xC0000005 here on a Release build.",
        'sxe -c "gh" e0000001; g; .lastevent; kn 8; q',
        ["repro.hlsl", "-T", "vs_5_0", "-E", "vert_main", "-Zi",
         "-Qembed_debug"])

    run("CASE 4 -- NDEBUG emulation, minimal repro",
        "tex3d: the minimal case 'produces incorrect code on release build' "
        "rather than crashing. gh past the assert and see whether it survives.",
        'sxe -c "gh" e0000001; g; .lastevent; q',
        ["minimal-repro.hlsl", "-T", "vs_6_0", "-E", "main"], limit=40)


if __name__ == "__main__":
    main()
