"""Per-release capability matrix for issue 4708.

Why this exists
---------------
The reported symptom of #4708 IS a diagnostic: DXC rejects a namespace-scope
`operator+`. That breaks the usual `invalid-probe` machinery, because a release
that simply predates HLSL 2021 also emits an error and therefore scores as a
*perfect* reproduction. A never-implemented feature and an always-broken one
look identical.

So no release probe counts unless that same release is independently shown to
have the *surrounding* capability. For every catalogued release this script
runs, on the same binary, with the same arguments:

  repro.hlsl                    the reporter's shader (free operator+)
  control-member-operator.hlsl  the same shader with a MEMBER operator+
  control-free-function.hlsl    the same free templates named `add`
  control-hello.hlsl            a trivial cs_6_0 shader

A release is MEASURABLE only when control-member-operator.hlsl compiles: that
proves class templates and member operator overloading are both present, so a
rejection of repro.hlsl is about non-member operator overloading specifically.

`triage.py bisect` cannot do this: catalogued releases are not registered
compiler ids, so `run --shader` retargets only the registered ground truth
(SKILL.md, "Per-release controls currently need an issue-local matrix").

Release executables come from the `releases.cached_path` column rather than
from walking a directory, because two physical roots exist -- `.cache/compilers
/releases/` and `build/tools/clang/test/dxc_releases/` -- and neither is a
superset of the other. Walking one root silently misses releases; walking with
a naive recursive search also picks arm64 binaries, which do not run here.

Prereleases are listed but NOT probed: #4708 names none, so by policy they stay
outside the history. They are printed with an explicit SKIPPED line so the
exclusion is visible rather than silent.

Run from the skill directory:
    python data/issues/4708/measure-releases.py
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(HERE))), "scripts")
sys.path.insert(0, SCRIPTS)
import triage  # noqa: E402  (path set above; redact_paths comes from here)

ARGS = ["-T", "cs_6_0", "-E", "main", "-HV", "2021"]

CASES = [
    ("repro", "repro.hlsl"),
    ("member-op", "control-member-operator.hlsl"),
    ("free-func", "control-free-function.hlsl"),
    ("hello", "control-hello.hlsl"),
]

# Feature-absence markers, kept deliberately narrow and quoted from what these
# binaries actually printed rather than guessed at.
LANG_ABSENT = re.compile(r"Unknown HLSL version", re.I)
# The two observed shapes of "the free operator does not work".
USE_REJECTED = re.compile(r"error:[^\n]*\r?\n[^\n]*result = arr1 \+ 2\.0f;")
DECL_DIAGNOSED = re.compile(
    r"error: overloading non-member 'operator\+' is not allowed")


def releases():
    out = subprocess.run(
        [sys.executable, os.path.join(SCRIPTS, "triage.py"), "sql",
         "SELECT tag, build_date, prerelease, cached_path FROM releases "
         "WHERE cached_path IS NOT NULL ORDER BY build_date"],
        capture_output=True, text=True, check=True).stdout
    return json.loads(out)


def run_case(exe, shader):
    argv = [exe] + ARGS + [shader]
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
    return argv, (p.stdout or "") + (p.stderr or ""), p.returncode


def main():
    lines = []

    def emit(s=""):
        lines.append(s)

    emit("Per-release capability matrix for issue 4708 "
         "(free / non-member operator overloading)")
    emit("Generated by measure-releases.py. Every command below is echoed "
         "exactly as executed.")
    emit("")
    emit("A release is MEASURABLE for this issue only if 'member-op' compiles "
         "(exit 0): that")
    emit("proves class templates and MEMBER operator overloading are present, "
         "so a rejection of")
    emit("repro.hlsl is about NON-member operator overloading and not about "
         "the release being")
    emit("too old to express the shader at all.")
    emit("")

    rows = []
    unmeasurable_tags = []
    for r in releases():
        tag = r["tag"]
        exe = r["cached_path"]
        if r["prerelease"]:
            emit(f"### {tag} ({r['build_date']}) SKIPPED: prerelease. "
                 f"#4708 names no prerelease, so it stays outside the history "
                 f"by policy.")
            emit("")
            continue
        emit(f"### {tag} ({r['build_date']})")
        emit(f"exe: {triage.display_exe(exe)}")
        res = {}
        for name, shader in CASES:
            argv, text, rc = run_case(exe, shader)
            res[name] = (text, rc)
            emit(f"$ {subprocess.list2cmdline(['dxc'] + ARGS + [shader])}")
            emit(f"[exit] {rc} (0x{rc & 0xFFFFFFFF:08X})")
            for ln in triage.redact_paths(text).rstrip().splitlines():
                emit(f"  | {ln}")
        member_ok = res["member-op"][1] == 0
        hello_ok = res["hello"][1] == 0
        free_func_ok = res["free-func"][1] == 0
        repro_text = res["repro"][0]
        lang_absent = bool(LANG_ABSENT.search(repro_text))
        use_rejected = bool(USE_REJECTED.search(repro_text))
        decl_diagnosed = bool(DECL_DIAGNOSED.search(repro_text))

        if not member_ok:
            status = ("UNMEASURABLE -- this release cannot compile a MEMBER "
                      "operator overload either")
            if lang_absent:
                status += " (rejects -HV 2021)"
        elif use_rejected or decl_diagnosed:
            status = "REPRO -- free operator+ not usable"
        else:
            status = ("NO-REPRO -- free operator+ appears to WORK; "
                      "investigate before believing it")

        emit(f"[verdict] {status}")
        emit(f"[capability] member-op={'ok' if member_ok else 'FAILED'} "
             f"free-func={'ok' if free_func_ok else 'FAILED'} "
             f"hello={'ok' if hello_ok else 'FAILED'}")
        emit(f"[shape] use-site-rejected={use_rejected} "
             f"declaration-diagnosed={decl_diagnosed}")
        emit("")
        if not member_ok:
            unmeasurable_tags.append(tag)
        rows.append((tag, r["build_date"], member_ok, free_func_ok, hello_ok,
                     use_rejected, decl_diagnosed, status.split(" --")[0]))

    emit("")
    emit("SUMMARY (stable releases only)")
    emit(f"{'tag':<14} {'built':<12} {'member-op':<10} {'free-func':<10} "
         f"{'hello':<7} {'use-rej':<8} {'decl-diag':<10} verdict")
    for (tag, date, m, f, h, u, d, v) in rows:
        emit(f"{tag:<14} {date:<12} {('ok' if m else 'FAIL'):<10} "
             f"{('ok' if f else 'FAIL'):<10} {('ok' if h else 'FAIL'):<7} "
             f"{str(u):<8} {str(d):<10} {v}")
    emit("")
    measurable = [r for r in rows if r[2]]
    repro = [r for r in measurable if r[7] == "REPRO"]
    emit(f"stable releases probed:        {len(rows)}")
    emit(f"measurable (member-op ok):     {len(measurable)}"
         + (f"  {measurable[0][0]}..{measurable[-1][0]}" if measurable else ""))
    emit(f"of those, repro:               {len(repro)}")
    emit(f"of those, free operator works: {len(measurable) - len(repro)}")
    emit("")
    emit("SELF-TEST: the matrix is only meaningful if the instrument can "
         "distinguish the two")
    emit("arms at all. It can: 'member-op' compiles (exit 0) on every "
         "measurable release while")
    emit("'repro' fails on all of them, from the same binary with the same "
         "arguments. If a row")
    emit("ever showed member-op=FAIL with a repro verdict, that release would "
         "be unmeasurable")
    emit("and is labelled so above rather than counted as a reproduction.")

    emit("")
    emit("APPENDIX: why the four oldest stable releases are unmeasurable "
         "rather than clean")
    emit("")
    emit("Above they are recorded as rejecting `-HV 2021`. On its own that "
         "could be read as a")
    emit("mere flag-spelling problem, so each is re-run WITHOUT -HV, at its "
         "own default language")
    emit("version. If the class template itself is rejected there, the "
         "release cannot express")
    emit("the reporter's shader in any language mode and could never have "
         "supported a free")
    emit("operator overload over it.")
    emit("")
    for r in releases():
        if r["prerelease"] or r["tag"] not in unmeasurable_tags:
            continue
        exe = r["cached_path"]
        argv = [exe, "-T", "cs_6_0", "-E", "main", "repro.hlsl"]
        p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
        text = (p.stdout or "") + (p.stderr or "")
        emit(f"### {r['tag']} ({r['build_date']}) -- no -HV, default "
             f"language version")
        emit(f"$ {subprocess.list2cmdline(['dxc', '-T', 'cs_6_0', '-E', 'main', 'repro.hlsl'])}")
        emit(f"[exit] {p.returncode} (0x{p.returncode & 0xFFFFFFFF:08X})")
        for ln in triage.redact_paths(text).rstrip().splitlines()[:6]:
            emit(f"  | {ln}")
        emit("")

    text = triage.redact_paths("\n".join(lines) + "\n")
    out = os.path.join(HERE, "manual-case-release-matrix.txt")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {out}")
    for line in lines[-14:]:
        print(line)


if __name__ == "__main__":
    main()
