"""Compiler Explorer control matrix for issue 4708.

Why a matrix and not just a link
--------------------------------
#4708 is a language-design question -- "can HLSL have free operator overloads?"
-- so the most useful evidence is not another DXC reproduction but **what the
successor compiler does**. Compiler Explorer carries `hlsl_clang_trunk`, the
Clang-based HLSL front end that is replacing DXC's.

But SKILL.md's rule applies: *a Clang error is not evidence until you have a
control*. Clang's HLSL support is incomplete, so it fails on inputs that have
nothing to do with the issue. A pane must therefore be read against a trivial
compile with the same flags, and against a near-miss on the same subject.

CE gives every pane one shared source, so the four sources cannot be compared
inside a single link. This script posts each of them to the CE compile API on
each compiler and writes the full text out, which is the same thing a link
would show, only complete.

  repro.hlsl                    free (namespace-scope) operator+   <- subject
  control-member-operator.hlsl  member operator+                   <- near miss
  control-free-function.hlsl    free template named `add`          <- near miss
  control-hello.hlsl            trivial cs_6_0 shader              <- pane works

Run from the skill directory:
    python data/issues/4708/measure-clang.py
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(HERE))), "scripts")
sys.path.insert(0, SCRIPTS)
import triage  # noqa: E402

SOURCES = [
    ("repro", "repro.hlsl",
     "SUBJECT: the reporter's shader. Two namespace-scope `operator+` "
     "templates over a class template, used as `arr1 + 2.0f`."),
    ("repro-observable", "repro-observable.hlsl",
     "SUBJECT, MADE VISIBLE: the same shader with the result stored to a UAV, "
     "so a compiler that accepts the program emits the arithmetic instead of "
     "an empty main(). Without this, 'accepted' and 'did nothing' look alike."),
    ("member-operator", "control-member-operator.hlsl",
     "NEAR MISS: identical except the operator is a MEMBER. Separates 'this "
     "compiler rejects non-member operators' from 'this compiler cannot do "
     "operator overloading / class templates at all'."),
    ("free-function", "control-free-function.hlsl",
     "NEAR MISS: the same free templates named `add` instead of `operator+`. "
     "Separates 'operators at namespace scope' from 'free templates'."),
    ("hello", "control-hello.hlsl",
     "TRIVIAL CONTROL: proves the pane, the profile and the flags work on "
     "this compiler at all, so an error above cannot be blamed on the setup."),
]

# dxc_1_6_2112 is CE's oldest DXC; dxc_trunk is a rolling build. The Clang
# panes are the point of this file. -fsyntax-only is NOT used: the question is
# whether the declaration is accepted, and if a front end hard-errors the
# backend never runs anyway -- so the front-end answer is already visible.
COMPILERS = [
    ("dxc_1_6_2112", "-T cs_6_0 -E main -HV 2021"),
    ("dxc_trunk", "-T cs_6_0 -E main -HV 2021"),
    ("hlsl_clang_trunk", "-T cs_6_0 -E main"),
    ("hlsl_clang_trunk", "-T cs_6_0 -E main -fsyntax-only"),
]


def main():
    lines = []

    def emit(s=""):
        lines.append(s)

    emit("Compiler Explorer control matrix for issue 4708 "
         "(free / non-member operator overloading)")
    emit("Generated by measure-clang.py against https://godbolt.org "
         "/api/compiler/<id>/compile.")
    emit("Output is reproduced in full, including CE's ANSI colour escapes "
         "where Clang emitted them:")
    emit("hand-cleaning a capture would be falsification. dxc_trunk is a "
         "rolling build and is not")
    emit("reproducible over time -- read it as a class of result, not a "
         "pinned symptom.")
    emit("")
    emit("-HV 2021 is passed to the DXC panes only. Clang's HLSL front end "
         "does not accept it as")
    emit("a language selector; it is also unnecessary there, since Clang "
         "implements the newer")
    emit("language by construction. The trivial control below is what proves "
         "the Clang panes work.")
    emit("")

    results = {}
    for name, shader, why in SOURCES:
        with open(os.path.join(HERE, shader), encoding="utf-8") as fh:
            src = fh.read()
        emit("=" * 78)
        emit(f"SOURCE {name}  ({shader})")
        emit(why)
        emit("=" * 78)
        for cid, args in COMPILERS:
            key = f"{cid} {args}"
            emit("")
            emit(f"--- {cid}   args: {args}")
            try:
                code, text, crashed = triage.ce_compile(src, cid, args)
            except Exception as exc:  # noqa: BLE001 - report, do not hide
                emit(f"[error contacting CE] {exc!r}")
                continue
            emit(f"[exit] {code}" + ("  [internal failure]" if crashed else ""))
            body = triage.redact_paths(text).rstrip()
            if body:
                for ln in body.splitlines():
                    emit(f"  | {ln}")
            else:
                emit("  | (no diagnostics)")
            results[(name, key)] = (code, text)

    emit("")
    emit("=" * 78)
    emit("SUMMARY")
    emit("=" * 78)
    emit(f"{'source':<18} " + " ".join(
        f"{cid.replace('hlsl_clang_trunk', 'clang')[:22]:<24}"
        for cid, _ in COMPILERS))
    for name, shader, _ in SOURCES:
        cells = []
        for cid, args in COMPILERS:
            code, _text = results.get((name, f"{cid} {args}"), ("?", ""))
            cells.append(f"{('exit ' + str(code)):<24}")
        emit(f"{name:<18} " + " ".join(cells))
    emit("")
    emit("HOW TO READ THIS. The claim under test is about the CONTRAST "
         "between the first row and")
    emit("the rest, on the same compiler. A compiler that fails the trivial "
         "control cannot be")
    emit("cited for anything. A compiler that compiles the trivial control "
         "and the member-operator")
    emit("near miss, and fails only on the free operator, is answering the "
         "issue's question.")

    out = os.path.join(HERE, "manual-case-clang-controls.txt")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(triage.redact_paths("\n".join(lines) + "\n"))
    print(f"wrote {out}")
    for ln in lines[-14:]:
        print(ln)


if __name__ == "__main__":
    main()
