"""Issue 4615: does the Clang-based HLSL front end honour #line in DXIL debug info?

The successor request on this issue asks for standard `#line` semantics in the
HLSL/Clang modernisation effort, so "what does clang-dxc do today" is a
separate question from "what does dxcompiler do". Compiler Explorer carries
`hlsl_clang_trunk`; its DXIL backend cannot lower a pixel shader writing
SV_Target, so the question is asked with a compute restating that both
compilers can lower, and `dxc_trunk` is run on the identical source as the
control that the restating still shows the behaviour under test.

Uses the same CE filter settings as triage.py's godbolt client, because CE's
default "remove comment-only lines" filter throws away the metadata block that
holds the evidence.

Run:  python clang-probe.py       (writes manual-case-clang-probe.txt)
"""
import json
import os
import re
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

OUT = os.path.join(HERE, "manual-case-clang-probe.txt")
SOURCE = os.path.join(HERE, "compute-restating.hlsl")
ARGS = "-T cs_6_0 -E main -Zi"
COMPILERS = ["hlsl_clang_trunk", "dxc_trunk"]

with open(SOURCE, encoding="utf-8") as f:
    src = f.read()

lines = [
    "# issue 4615 -- #line in DXIL debug info: clang-dxc vs dxcompiler",
    "# generated by clang-probe.py against the Compiler Explorer API",
    f"# source: {os.path.basename(SOURCE)}   args: {ARGS}",
    "# NOTE: CE appends its own -Zi -Qembed_debug -Fc - to every pane.",
    "",
]

for cid in COMPILERS:
    payload = json.dumps({
        "source": src, "lang": "hlsl", "compiler": cid,
        "options": {"userArguments": ARGS,
                    "compilerOptions": {"skipAsm": False, "executorRequest": False},
                    "filters": dict(triage.CE_FILTERS), "tools": [], "libraries": []},
        "allowStoreCodeDebug": True,
    }).encode()
    req = urllib.request.Request(
        f"https://godbolt.org/api/compiler/{cid}/compile", data=payload,
        headers={"Content-Type": "application/json", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as r:
        res = json.load(r)
    asm = "\n".join(x.get("text", "") for x in res.get("asm", []) if isinstance(x, dict))
    err = "\n".join(x.get("text", "") for x in res.get("stderr", []))
    diloc = sorted(set(re.findall(r"!DILocation\(line: (\d+),", asm)), key=int)
    difile = sorted(set(re.findall(r'!DIFile\(filename: "([^"]+)"', asm)))
    lines += [
        f"=== {cid} ===",
        "$ " + subprocess.list2cmdline(["curl", "-d", "@-",
                                        f"https://godbolt.org/api/compiler/{cid}/compile"]),
        f"[exit] {res.get('code')}",
        f"[asm lines] {len(asm.splitlines())}",
        f"[!DILocation lines] {', '.join(diloc) if diloc else '(none in the asm pane)'}",
        f"[!DIFile names] {', '.join(difile) if difile else '(none in the asm pane)'}",
    ]
    for pat, label in ((r"^!\d+ = !DIFile.*$", "DIFile"),
                       (r"^!\d+ = !DILocation.*$", "DILocation")):
        for m in re.findall(pat, asm, re.MULTILINE)[:8]:
            lines.append(f"  {label}: {m.strip()}")
    diag = [ln for ln in err.splitlines() if ln.strip()][:6]
    lines.append("[stderr] " + (diag[0] if diag else "(empty)"))
    lines += ["         " + ln for ln in diag[1:]]
    lines.append("")

text = triage.redact_paths("\n".join(lines))
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(text)
print(text)
