"""Issue 4615: prove the debug-info flags in cmd.txt were actually parsed.

A clean exit never proves a flag was honoured -- dxc silently ignores
unrecognised `/`-style options -- and an absence-based predicate is satisfied
for free by a compile that emitted no debug metadata at all. This harness
measures, rather than assumes, that `-Zi -Qembed_debug` is load-bearing:

  baseline      the exact cmd.txt command
  no-Qembed     `-Zi` alone: dxc warns that it is embedding a PDB anyway
  slash-nonsense  `/ZZZNONSENSE` added where a real option goes -- exit and
                  output must be identical to baseline, which is what makes
                  "it exited 0" worthless as evidence a flag was parsed
  dash-nonsense   a mistyped `-Qembed_debugZZZ`: the `-` parser does reject it
  bad-Fd          `-Fd` pointed at a directory that does not exist: a flag made
                  to fail, proving that class of option is parsed at all
  no-debug-flags  neither flag: no debug metadata is produced

Every command is echoed with subprocess.list2cmdline, so the transcript is the
command that ran rather than one somebody typed. Output is passed through
triage.redact_paths() before being written.

Run:  python flag-provenance.py            (writes manual-case-flag-provenance.txt)
Set DXC_EXE to point at a different compiler.
"""
import hashlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

REPO = os.path.abspath(os.path.join(HERE, *([".."] * 6)))
EXE = os.environ.get("DXC_EXE") or os.path.join(REPO, "build", "Debug", "bin", "dxc.exe")
OUT = os.path.join(HERE, "manual-case-flag-provenance.txt")

CASES = [
    ("baseline", ["-T", "ps_6_0", "-E", "main", "-Zi", "-Qembed_debug", "repro.hlsl"]),
    ("no-Qembed", ["-T", "ps_6_0", "-E", "main", "-Zi", "repro.hlsl"]),
    ("slash-nonsense", ["-T", "ps_6_0", "-E", "main", "-Zi", "/ZZZNONSENSE",
                        "-Qembed_debug", "repro.hlsl"]),
    ("dash-nonsense", ["-T", "ps_6_0", "-E", "main", "-Zi", "-Qembed_debugZZZ",
                       "repro.hlsl"]),
    ("bad-Fd", ["-T", "ps_6_0", "-E", "main", "-Zi", "-Fd",
                "no-such-directory\\", "repro.hlsl"]),
    ("no-debug-flags", ["-T", "ps_6_0", "-E", "main", "repro.hlsl"]),
]

lines = [
    "# issue 4615 -- were the debug-info flags actually parsed?",
    "# generated by flag-provenance.py; paths redacted by triage.redact_paths()",
    f"# exe: {triage.redact_paths(EXE)}",
    "",
]

baseline_hash = None
for name, args in CASES:
    p = subprocess.run([EXE] + args, cwd=HERE, capture_output=True, text=True)
    out = triage.redact_paths(p.stdout or "")
    err = triage.redact_paths(p.stderr or "")
    digest = hashlib.sha256(out.encode("utf-8", "replace")).hexdigest()[:16]
    if name == "baseline":
        baseline_hash = digest
    dilocs = sorted(set(re.findall(r"!DILocation\(line: (\d+),", out)), key=int)
    difiles = sorted(set(re.findall(r'!DIFile\(filename: "([^"]+)"', out)))
    lines += [
        f"=== {name} ===",
        "$ " + subprocess.list2cmdline(["dxc"] + args),
        f"[exit] {p.returncode}",
        f"[stdout sha256/16] {digest}"
        + ("  (identical to baseline)" if digest == baseline_hash and name != "baseline"
           else ("  (baseline)" if name == "baseline" else "  (differs from baseline)")),
        f"[!DILocation lines] {', '.join(dilocs) if dilocs else '(none -- no debug metadata)'}",
        f"[!DIFile names] {', '.join(difiles) if difiles else '(none)'}",
    ]
    diag = [ln for ln in err.splitlines() if ln.strip()]
    lines.append("[stderr] " + (diag[0] if diag else "(empty)"))
    lines += ["         " + ln for ln in diag[1:6]]
    lines.append("")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print("\n".join(lines))
