"""Issue 4615: per-capture debug-metadata self-test table.

The primary predicate is an all_of whose first clause is a PRESENCE self-test
(`!DILocation(line: 7,` -- the statement that sits before the `#line`
directive). That clause is what stops the two absence clauses from being
satisfied for free by a compile that emitted no debug info at all. This script
makes the guard readable rather than merely encoded: for every capture in the
issue directory it prints the debug-metadata evidence the predicate scored, so
a reader can see that each `repro` verdict rests on debug metadata that was
*present*, and that the single `no-repro` release is not an empty module.

Run:  python release-matrix.py    (writes manual-case-release-matrix.txt)
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

OUT = os.path.join(HERE, "manual-case-release-matrix.txt")


def order(name):
    m = re.match(r"out-v(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?\.txt$", name)
    if m:
        return (1,) + tuple(int(x or 0) for x in m.groups())
    return (0, 0, 0, 0, 0) if name.startswith("out-main") else (2, 0, 0, 0, 0)


def header(text, key):
    m = re.search(rf"^# {key}: (.*)$", text, re.MULTILINE)
    return m.group(1).strip() if m else "?"


files = sorted((f for f in os.listdir(HERE)
                if (f.startswith("out-") or f.startswith("variant-"))
                and f.endswith(".txt")), key=order)

rows = []
for name in files:
    with open(os.path.join(HERE, name), encoding="utf-8", errors="replace") as f:
        text = f.read()
    lines = sorted(set(re.findall(r"!DILocation\(line: (\d+),", text)), key=int)
    files_seen = sorted(set(re.findall(r'!DIFile\(filename: "([^"]+)"', text)))
    rows.append((
        name,
        header(text, "compiler"),
        header(text, "verdict"),
        "PASS" if re.search(r"!DILocation\(line: 7,", text) else "fail",
        ",".join(lines) or "(no debug locations)",
        ",".join(files_seen) or "(none)",
    ))

w = [max(len(r[i]) for r in rows) for i in range(6)]
head = ("capture", "compiler", "verdict", "selftest", "!DILocation lines",
        "!DIFile names")
w = [max(w[i], len(head[i])) for i in range(6)]
fmt = "  ".join("{:<%d}" % n for n in w)

out = [
    "# issue 4615 -- debug metadata actually present in every scored capture",
    "# generated by release-matrix.py",
    "#",
    "# selftest = the predicate's first clause, `!DILocation(line: 7,`: the",
    "#   Sample() call on physical line 7 sits BEFORE the #line directive, so it",
    "#   reports line 7 whether or not #line is honoured. It fails only if the",
    "#   module carries no debug locations, or spells them differently. A `repro`",
    "#   verdict therefore cannot be produced by a module with no debug info.",
    "",
    fmt.format(*head),
    fmt.format(*("-" * n for n in w)),
]
out += [fmt.format(*r).rstrip() for r in rows]
out.append("")

text = triage.redact_paths("\n".join(out))
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(text)
print(subprocess.list2cmdline(["python", os.path.basename(__file__)]))
print(text)
