"""#4497 per-release control matrix: does the test1/test2 ASYMMETRY hold on every release?

`triage.py bisect` answers only half the question.  It scores `cmd.txt`
(`-T ps_6_0 -E test1`) on each release and reported `always-repro'd` -- the float
load of SData::value is unconditional on all 20 stable releases.  But the issue is
not "a load is unconditional"; it is "the by-value form loads unconditionally *where
the direct-indexing form does not*".  If some old release had also hoisted the load
in `test2`, the asymmetry the report is about would not exist there, and
`always-repro'd` would be describing something narrower than the issue.

Catalogued releases are not registered compiler ids, so `run --shader` cannot
retarget them (SKILL step 6, "Per-release controls currently need an issue-local
matrix").  This script is that matrix: for every stable release with a cached
`dxc.exe`, plus the ground-truth build, it runs BOTH entry points with otherwise
identical arguments and scores each with this issue's own `match.json`, through
`triage.py`'s own `matches()` so the scoring cannot drift from the tool's.

Self-test: every row must be `repro` for test1 and `no-repro` for test2.  Any other
combination is printed as `** UNEXPECTED **` and counted in the summary, so a run
that measured nothing cannot look like a clean run.  It also prints each release's
`--version` line, because a probe from a binary that is not what you think it is
answers a different question.

Every command is echoed exactly as executed via subprocess.list2cmdline, and paths
are printed in triage.py's own <repo>/<cache> tokenised form.

    python measure-release-matrix.py > manual-case-test2-control-matrix.txt
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))
sys.path.insert(0, SCRIPTS)
import triage  # noqa: E402

ISSUE = 4497
PROFILE = "ps_6_0"
ENTRIES = [("test1", "repro"), ("test2", "no-repro")]


def run(exe, args):
    argv = [exe] + args
    print("$ " + subprocess.list2cmdline([triage.display_exe(exe)] + args))
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       timeout=triage.TIMEOUT)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def version_of(exe):
    try:
        rc, out = run(exe, ["--version"])
    except Exception as e:                                   # noqa: BLE001
        return f"<--version failed: {e}>"
    return " / ".join(l.strip() for l in out.splitlines() if l.strip())


def main():
    con = triage.con()
    rows = con.execute(
        "SELECT tag, cached_path FROM releases "
        "WHERE prerelease=0 AND cached_path IS NOT NULL ORDER BY build_date"
    ).fetchall()
    builds = [(r["tag"], r["cached_path"]) for r in rows]
    gt = triage.resolve_compiler("main-debug")
    builds.append(("main-debug", gt))

    print(f"#{ISSUE} test1-vs-test2 control matrix -- generated by "
          "measure-release-matrix.py")
    print(f"predicate: match.json;  profile: {PROFILE};  source: repro.hlsl")
    print("expected on every build: test1 -> repro, test2 -> no-repro")
    print()

    unexpected = 0
    summary = []
    for tag, exe in builds:
        print(f"===== {tag} =====")
        print(f"[exe] {triage.display_exe(exe)}")
        print(f"[version] {version_of(exe)}")
        scores = {}
        for entry, want in ENTRIES:
            args = ["-T", PROFILE, "-E", entry, "repro.hlsl"]
            rc, out = run(exe, args)
            verdict = triage.classify(ISSUE, out, rc, False)
            scores[entry] = verdict
            flag = "" if verdict == want else "   ** UNEXPECTED **"
            if verdict != want:
                unexpected += 1
            print(f"[exit] {rc}  [predicate] {verdict}  (expected {want}){flag}")
            # the two lines that carry the finding, in source order
            for line in out.splitlines():
                s = line.strip()
                if s.startswith("br i1 ") or "BufferLoad(srv" in s:
                    print("    | " + s)
            print()
        summary.append((tag, scores["test1"], scores["test2"]))

    print("===== summary =====")
    print(f"{'build':<16}{'test1':<12}{'test2':<12}asymmetry")
    for tag, a, b in summary:
        ok = "yes" if (a == "repro" and b == "no-repro") else "NO"
        print(f"{tag:<16}{a:<12}{b:<12}{ok}")
    print()
    print(f"builds probed: {len(summary)}   unexpected scores: {unexpected}")
    print("SELF-TEST: " + ("pass" if unexpected == 0 else "FAIL"))


if __name__ == "__main__":
    main()
