"""Compiler Explorer control probe for issue 3708.

`triage.py godbolt` publishes one source through several panes, which is what
the issue's shareable link needs. It cannot run a *second*, control source
through those same panes -- and without one, Clang's answer is not evidence:
Clang rejects two of the four bounds in the published repro, and the obvious
reading ("Clang has the same restriction") is only one of two explanations.
The other is that Clang is objecting to `static const` rather than to the
swizzle, which is ordinary C++ and nothing to do with this issue.

So this script compiles ONE source that separates the two, through the same
four panes, and writes `manual-case-clang-control.txt`. It publishes nothing:
POST /api/compiler/<id>/compile only compiles, and no shortlink is created.

Usage, from anywhere:
    python run-ce-control-3708.py
"""

import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CE = "https://godbolt.org"

# Six bounds that differ in exactly one property each. The decisive rows are
# `staticConstScalar` and `swizzleOfLiteral`: if a compiler takes the first and
# refuses `swizzleOfConstVector`, the swizzle is what it objects to; if it
# refuses the first too, its objection is to `static const` and says nothing
# about this issue.
SOURCE = """\
static const uint  s  = 10;
static const uint2 v2 = uint2(20, 30);

RWBuffer<uint> Out;

[numthreads(1, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID)
{
    int plainLiteral[10];
    int swizzleOfLiteral[(10).x];
    int staticConstScalar[s];
    int swizzleOfConstScalar[s.x];
    int swizzleOfConstVector[v2.x];
    int subscriptOfConstVector[v2[1]];
    plainLiteral[0] = 1; swizzleOfLiteral[0] = 1; staticConstScalar[0] = 1;
    swizzleOfConstScalar[0] = 1; swizzleOfConstVector[0] = 1;
    subscriptOfConstVector[0] = 1;
    Out[tid.x] = plainLiteral[0] + swizzleOfLiteral[0] + staticConstScalar[0]
               + swizzleOfConstScalar[0] + swizzleOfConstVector[0]
               + subscriptOfConstVector[0];
}
"""

PANES = [
    ("fxc_10_0_26100", "/T cs_5_0 /E main"),
    ("dxc_trunk", "-T cs_6_0 -E main"),
    ("hlsl_clang_trunk", "-T cs_6_0 -E main"),
]

# Clang's notes on the source above blame `read of non-constexpr variable 'v2'`,
# which is the ordinary C++ rule for a `const` object of non-integral type. If
# that is the whole of Clang's objection then spelling the vector `constexpr`
# should make it accept the component -- and whether DXC understands the
# spelling at all is the other half of the question.
SOURCE_CONSTEXPR = """\
constexpr uint2 cv2 = uint2(20, 30);

RWBuffer<uint> Out;

[numthreads(1, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID)
{
    int constexprSwizzle[cv2.x];
    int constexprSubscript[cv2[1]];
    constexprSwizzle[0] = 1; constexprSubscript[0] = 1;
    Out[tid.x] = constexprSwizzle[0] + constexprSubscript[0];
}
"""


def compile_on_ce(source, cid, args):
    body = json.dumps({
        "source": source,
        "options": {
            "userArguments": args,
            "filters": {"execute": False, "commentOnly": True,
                        "directives": True, "labels": True, "trim": False},
            "compilerOptions": {},
        },
    }).encode()
    req = urllib.request.Request(
        f"{CE}/api/compiler/{cid}/compile", data=body,
        headers={"Content-Type": "application/json",
                 "Accept": "application/json"})
    r = json.load(urllib.request.urlopen(req, timeout=120))
    text = "\n".join(x.get("text", "")
                     for x in (r.get("stdout", []) + r.get("stderr", [])))
    return r.get("code"), text


def main():
    out = [
        "# Issue 3708 -- Compiler Explorer CONTROL probe.",
        "# Generated by run-ce-control-3708.py; rerun it to re-derive this file.",
        "# Compiles only (POST /api/compiler/<id>/compile). Publishes nothing.",
        "#",
        "# The published link (godbolt-compute.hlsl) shows DXC rejecting three",
        "# bounds Clang and FXC accept -- but Clang rejects two of them, and",
        "# that needs separating from an objection to `static const`, which is",
        "# plain C++ and unrelated to this issue. Read the `staticConstScalar`",
        "# row: a compiler that refuses it is not answering this issue's",
        "# question at all.",
        "",
    ]
    for title, source in (("A. static const operands", SOURCE),
                          ("B. constexpr operands", SOURCE_CONSTEXPR)):
        numbered = "\n".join(f"{i + 1:>3}| {ln}"
                             for i, ln in enumerate(source.splitlines()))
        out += ["#" * 74, f"# {title}", "#" * 74, "",
                "--- source, with line numbers ---", numbered, ""]
        for cid, args in PANES:
            code, text = compile_on_ce(source, cid, args)
            out += ["=" * 74,
                    f"# compiler: {cid}",
                    f"# args:     {args}",
                    f"# exit:     {code}",
                    "",
                    text.rstrip() or "(no diagnostics)",
                    ""]
    path = os.path.join(HERE, "manual-case-clang-control.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.basename(path))


if __name__ == "__main__":
    main()
