"""Measure the `fxc-disagrees` claim on issue 3708 instead of repeating it.

Runs the same sources through FXC (Windows SDK) and through the ground-truth
DXC, and writes `manual-case-fxc.txt`. Every command is printed exactly as it
was executed, via subprocess.list2cmdline, so a reader can re-derive the file
rather than trust it.

Usage, from anywhere:
    python run-fxc-3708.py

fxc.exe is found from $FXC, then PATH, then the newest
"%ProgramFiles(x86)%\\Windows Kits\\10\\bin\\<ver>\\x64\\fxc.exe".
dxc.exe is found from $DXC, else <repo>/build/Debug/bin/dxc.exe, both derived
from this file's location -- no absolute path is baked in.
"""

import glob
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, *([os.pardir] * 6)))


def find_fxc():
    if os.environ.get("FXC"):
        return os.environ["FXC"]
    found = shutil.which("fxc")
    if found:
        return found
    root = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
    pat = os.path.join(root, "Windows Kits", "10", "bin", "*", "x64", "fxc.exe")
    cands = sorted(glob.glob(pat))
    if not cands:
        sys.exit("no fxc.exe found; set FXC=<path to fxc.exe>")
    return cands[-1]


def find_dxc():
    if os.environ.get("DXC"):
        return os.environ["DXC"]
    p = os.path.join(REPO, "build", "Debug", "bin", "dxc.exe")
    if not os.path.exists(p):
        sys.exit(f"no dxc.exe at {p}; set DXC=<path to dxc.exe>")
    return p


def short(path):
    """Render an exe path without leaking a machine-specific prefix."""
    parts = path.replace("/", "\\").split("\\")
    return "\\".join(parts[-4:]) if len(parts) > 4 else path


def run(out, exe, label, argv):
    shown = [label] + argv
    out.append("$ " + subprocess.list2cmdline(shown))
    p = subprocess.run([exe] + argv, cwd=HERE, capture_output=True, text=True)
    out.append(f"[exit] {p.returncode}")
    body = (p.stdout + p.stderr).replace(HERE + os.sep, "").replace(HERE, ".")
    out.append(body.rstrip() or "(no output)")
    out.append("")
    return p.returncode


CASES = [
    ("repro.hlsl", "the issue body's minimal case"),
    ("control-literal.hlsl", "the issue body's working case"),
    ("case-array-bound-matrix.hlsl", "comment 1's six-case matrix"),
    ("case-nonarray-ice-contexts.hlsl", "case label / template arg / enumerator"),
    ("case-ice-fxc-portable.hlsl", "the same, minus the `enum` FXC cannot parse"),
]


def main():
    fxc, dxc = find_fxc(), find_dxc()
    out = [
        "# Issue 3708 -- FXC vs DXC on the same sources.",
        "# Generated by run-fxc-3708.py; rerun it to re-derive this file.",
        "# Commands are printed as executed (subprocess.list2cmdline); the exe",
        "# paths are shortened to their last components on purpose.",
        f"# fxc: {short(fxc)}",
        f"# dxc: {short(dxc)}",
        "",
    ]
    run(out, fxc, "fxc.exe", ["/?"])
    out[-2] = "\n".join(out[-2].splitlines()[:3])
    run(out, dxc, "dxc.exe", ["--version"])

    for src, why in CASES:
        out.append("=" * 74)
        out.append(f"# {src} -- {why}")
        out.append("=" * 74)
        out.append("")
        run(out, fxc, "fxc.exe", ["/nologo", "/T", "ps_5_0", "/E", "main",
                                  "/Fo", "NUL", src])
        run(out, dxc, "dxc.exe", ["-T", "ps_6_0", "-E", "main", src])

    path = os.path.join(HERE, "manual-case-fxc.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.basename(path))


if __name__ == "__main__":
    main()
