"""Paired release matrix for issue 4701.

WHY THIS EXISTS
---------------
#4701 is a missed-optimisation report, and a one-sided history probe on a code-quality
issue cannot distinguish "the reported case got worse" from "the comparison case got
better".  `triage.py bisect` scores only `repro.hlsl`, so it can say the groupshared arm
reproduced on every release and still leave open whether the `static` arm it is being
compared against was equally bad in 2019 and only improved later.  This script measures
BOTH arms -- plus the instrument self-test and the feature-presence probe -- on every
stable release in the catalog, with one shared address-space-agnostic predicate
(match-deadarray.json), and prints the pair side by side.

It also counts, rather than eyeballs, so that "not optimised" means something a reader can
re-derive in a year:

    G   module-level globals of type [10 x float] in address space 3 (groupshared / TGSM)
    A   module-level globals of type [10 x float] in ANY address space
    S3  `store` instructions whose pointer operand is in address space 3
    S   `store` instructions of any kind
    TGSM  the PSV runtime-info byte count of group shared memory, or "-" if that release's
          disassembler does not print the field.  Measured: NO catalogued release prints it
          -- v1.4.1907 prints no PSVRuntimeInfo block at all, and even v1.9.2607 prints the
          block without a NumBytesGroupSharedMemory line.  It is a post-v1.9.2607 addition,
          which is exactly why it is supplementary evidence and not part of any predicate.
          manual-case-tgsm-crosscheck.txt reads the same quantity out of every release's
          container with one fixed reader instead.

SELF-CONSISTENCY
----------------
A harness that can return "nothing here" and "nothing matched" through the same channel
will eventually be believed, so every row is checked:
  * the feature-presence arm (control-hello) must compile on the release, or the whole
    row is unmeasurable rather than clean;
  * the instrument self-test arm (control-gs-live) must show G>=1 and S3>=1, because a
    genuinely live groupshared array has to survive; a row where it does not is a broken
    reader, not a clean compiler.
Either failure prints a loud MATRIX-4701: PARSE-WARNING / UNMEASURABLE line.

Run from the skill directory:  python data/issues/4701/release-matrix.py
"""

import hashlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(SKILL, "scripts"))

import triage  # noqa: E402  (path set up above)

ARGS = ["-T", "cs_6_0", "-E", "main"]
SHADERS = [
    ("repro", "repro.hlsl", "reported case: groupshared, store-only"),
    ("static", "control-static.hlsl", "REFERENCE case: same source, static instead"),
    ("local", "control-local.hlsl", "reference case: same array, function-local"),
    ("gs-live", "control-gs-live.hlsl", "self-test: groupshared that IS read back"),
    ("hello", "control-hello.hlsl", "feature-presence: trivial cs_6_0, no array"),
]

RE_G = re.compile(r"^@[^\n=]*=[^\n=]*addrspace\(3\) global \[10 x float\]", re.M)
RE_A = re.compile(r"^@[^\n=]*=[^\n=]*global \[10 x float\]", re.M)
RE_S3 = re.compile(r"^\s*store [^\n]*addrspace\(3\)\*", re.M)
RE_S = re.compile(r"^\s*store ", re.M)
RE_TGSM = re.compile(r"^; NumBytesGroupSharedMemory: (\d+)", re.M)
RE_ENTRY = re.compile(r"!dx\.entryPoints\s*=")


def measure(exe, shader):
    argv = [exe] + ARGS + [shader]
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       errors="replace", timeout=300)
    text = triage.redact_paths((p.stdout or "") + (p.stderr or ""))
    tgsm = RE_TGSM.search(text)
    return {
        "cmd": triage.redact_paths(subprocess.list2cmdline(argv)),
        "rc": p.returncode,
        "text": text,
        "G": len(RE_G.findall(text)),
        "A": len(RE_A.findall(text)),
        "S3": len(RE_S3.findall(text)),
        "S": len(RE_S.findall(text)),
        "TGSM": tgsm.group(1) if tgsm else "-",
        "emitted": bool(RE_ENTRY.search(text)) and p.returncode == 0,
        "sha256": hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()[:16],
    }


def deadarray(m):
    """match-deadarray.json, evaluated on a measurement. Kept in step with that file."""
    return "repro" if (m["emitted"] and m["A"] >= 1 and m["S"] >= 1) else "no-repro"


def main():
    rows = list(triage.con().execute(
        "SELECT tag, build_date, cached_path, prerelease FROM releases"
        " WHERE prerelease = 0 AND cached_path IS NOT NULL AND cached_path <> ''"
        " ORDER BY build_date"))
    out = []
    w = out.append
    w("Paired release matrix for issue 4701 -- reported case vs reference case.")
    w("Generated by release-matrix.py, which echoes every command it runs.")
    w("Stable releases only; prereleases are excluded by policy and the issue names none.")
    w("")
    w("Columns: G = [10 x float] globals in addrspace(3); A = [10 x float] globals in any")
    w("address space; S3 = stores through an addrspace(3) pointer; S = stores of any kind;")
    w("TGSM = PSV NumBytesGroupSharedMemory ('-' = this release's disassembler has no such")
        w("field; measured, every catalogued release is '-' and only the ground-truth build")
        w("prints it, so it is supplementary evidence and not part of any predicate);")
        w("verdict = match-deadarray.json.")
    w("")
    hdr = (f"{'release':<14} {'arm':<8} {'rc':>4} {'G':>2} {'A':>2} {'S3':>3} {'S':>2} "
           f"{'TGSM':>5}  {'verdict':<9} sha256/16")
    w(hdr)
    w("-" * len(hdr))

    warnings = []
    ground = [("main-debug", triage.con().execute(
        "SELECT exe_path FROM compilers WHERE id = 'main-debug'").fetchone()["exe_path"])]
    targets = [(r["tag"], r["cached_path"]) for r in rows] + ground

    for tag, exe in targets:
        if not os.path.exists(exe):
            warnings.append(f"MATRIX-4701: UNMEASURABLE: {tag}: no executable at "
                            f"{triage.display_exe(exe)}")
            continue
        ms = {}
        for arm, shader, _ in SHADERS:
            ms[arm] = measure(exe, shader)
        for arm, shader, _ in SHADERS:
            m = ms[arm]
            w(f"{tag:<14} {arm:<8} {m['rc']:>4} {m['G']:>2} {m['A']:>2} {m['S3']:>3} "
              f"{m['S']:>2} {m['TGSM']:>5}  {deadarray(m):<9} {m['sha256']}")
        if not ms["hello"]["emitted"]:
            warnings.append(f"MATRIX-4701: UNMEASURABLE: {tag}: feature-presence control "
                            f"control-hello.hlsl did not compile (rc={ms['hello']['rc']}); "
                            f"this release's other rows are not evidence")
        if ms["gs-live"]["G"] < 1 or ms["gs-live"]["S3"] < 1:
            warnings.append(f"MATRIX-4701: PARSE-WARNING: {tag}: instrument self-test "
                            f"control-gs-live.hlsl gave G={ms['gs-live']['G']} "
                            f"S3={ms['gs-live']['S3']}; a live groupshared array must "
                            f"survive, so the reader is broken on this release")
        w("")

    w("")
    w("Commands run for each row (identical on every release except the executable):")
    for arm, shader, why in SHADERS:
        w(f"  {arm:<8} {subprocess.list2cmdline(['<dxc>'] + ARGS + [shader])}"
          f"   # {why}")
    w("")
    if warnings:
        w("SELF-CHECKS: " + str(len(warnings)) + " problem(s)")
        for x in warnings:
            w("  " + x)
    else:
        w("SELF-CHECKS: all rows measurable; the feature-presence control compiled on "
          "every release, and the instrument self-test saw a surviving groupshared "
          "global and addrspace(3) store on every release.")

    text = triage.redact_paths("\n".join(out) + "\n")
    dest = os.path.join(HERE, "manual-case-release-matrix.txt")
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(text)


if __name__ == "__main__":
    main()
