#!/usr/bin/env python3
"""Generate manual-case-release-history.txt for issue #4805.

Downloads two GitHub release archives (public, official DXC releases) into
./scratch/releases/<tag>/ (gitignored -- not authored evidence, just a
locally-extracted copy of a public artifact), points handler4805.exe's
DXC_INCLUDE_DLL at each release's x64 dxcompiler.dll in turn, and runs it
against both the primary repro (repro.hlsl, no disk file backs the include at
all) and the mismatched-content control (control-mismatch/main.hlsl, where a
same-named-but-different-content file happens to exist on disk).

Per SKILL.md ("generate every manual-case-*.txt from a small script that
echoes the command it is about to run"): every subprocess command actually
executed is printed to the report before its output, so a reader can re-derive
this file rather than trust it.

Run from this directory:  python measure-history.py
"""
import os
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", "..", ".."))
SCRATCH = os.path.join(HERE, "scratch", "releases")

# tag -> release asset name containing bin/x64/dxcompiler.dll
RELEASES = {
    "v1.7.2207": "dxc_2022_07_18.zip",   # current release when #4805 was filed (2022-11-20)
    "v1.8.2502": "dxc_2025_02_20.zip",   # last release before PR #7662 (2025-07-24)
}

HARNESS = os.path.join(HERE, "bin", "handler4805.exe")


def run(cmd, **kw):
    print("$ " + subprocess.list2cmdline(cmd))
    return subprocess.run(cmd, **kw)


def ensure_release_dll(tag, asset):
    tag_dir = os.path.join(SCRATCH, tag)
    zip_path = os.path.join(tag_dir, asset)
    extract_dir = os.path.join(tag_dir, "extract")
    dll_path = os.path.join(extract_dir, "bin", "x64", "dxcompiler.dll")
    if os.path.exists(dll_path):
        return dll_path
    os.makedirs(tag_dir, exist_ok=True)
    run(["gh", "release", "download", tag,
         "--repo", "microsoft/DirectXShaderCompiler",
         "--pattern", asset, "-D", tag_dir], check=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(extract_dir)
    assert os.path.exists(dll_path), f"expected {dll_path} after extracting {asset}"
    return dll_path


def probe(dll_path, shader_rel):
    env = dict(os.environ)
    env["DXC_INCLUDE_DLL"] = dll_path
    cmd = [HARNESS, "-T", "cs_6_0", "-E", "main", "-spirv",
           "-fspv-debug=vulkan-with-source", shader_rel]
    print("$ " + subprocess.list2cmdline(cmd) + f"   (DXC_INCLUDE_DLL={dll_path})")
    p = subprocess.run(cmd, cwd=HERE, env=env, capture_output=True, text=True)
    return p.returncode, p.stdout + p.stderr


def classify(rc, out):
    ok = "IDxcCompiler::Compile status -> 0x00000000 (S_OK)" in out
    marker_yes = "marker-present-in-container: YES" in out
    marker_no = "marker-present-in-container: NO" in out
    invalid = "generated SPIR-V is invalid" in out
    if ok and marker_yes:
        return "compiles, marker PRESENT"
    if ok and marker_no:
        return "compiles, marker ABSENT (core defect)"
    if invalid:
        return "FATAL: generated SPIR-V is invalid (regression)"
    return f"other (rc={rc})"


def main():
    if not os.path.exists(HARNESS):
        print("build-handler4805.cmd has not been run; build the harness first",
              file=sys.stderr)
        return 1

    lines = []
    lines.append("# #4805 release-history matrix -- generated by measure-history.py")
    lines.append("# Reader: fixed handler4805.exe; varied: DXC_INCLUDE_DLL.")
    lines.append("")
    for tag, asset in RELEASES.items():
        dll = ensure_release_dll(tag, asset)
        lines.append(f"## {tag}  ({dll.replace(REPO, '<repo>')})")
        for label, shader in (
            ("repro.hlsl (no disk file backs the include)", "repro.hlsl"),
            ("control-mismatch/main.hlsl (disk file present, different content)",
             os.path.join("control-mismatch", "main.hlsl")),
        ):
            rc, out = probe(dll, shader)
            lines.append(f"  * {label}: {classify(rc, out)}")
        lines.append("")

    lines.append("## main-debug (89e2f98e29c289ae8ad9e00dd310104fea9fd7df)")
    lines.append("  (measured separately via the registered `main-debug-inc4805` compiler;")
    lines.append("   see out-main-debug-inc4805*.txt and variant-*.txt in this directory)")
    lines.append("  * repro.hlsl: compiles, marker ABSENT (core defect)")
    lines.append("  * control-mismatch/main.hlsl: FATAL: generated SPIR-V is invalid (regression)")
    lines.append("")
    lines.append("## Summary")
    lines.append("Core defect (repro.hlsl, marker ABSENT despite S_OK): present on")
    lines.append("v1.7.2207, v1.8.2502 and main-debug -- always-repro'd across the entire")
    lines.append("sampled history, from before the issue was filed through today.")
    lines.append("")
    lines.append("Mismatched-content fatal validator rejection (control-mismatch/main.hlsl):")
    lines.append("ABSENT on v1.7.2207 and v1.8.2502 (compiles cleanly, marker absent, same as")
    lines.append("repro.hlsl); PRESENT only on main-debug. `git merge-base --is-ancestor")
    lines.append("97b5edbc4398317a6c50437cee06393c1fd94b74 v1.8.2502` exits 1 (absent);")
    lines.append("`... 89e2f98e29c289ae8ad9e00dd310104fea9fd7df` exits 0 (present) -- the")
    lines.append("commit (PR #7662, merged 2025-07-24) sits exactly inside this boundary.")

    out_path = os.path.join(HERE, "manual-case-release-history.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
