#!/usr/bin/env python3
"""Record the ground-truth compiler's self-reported identity for issue 3686.

Issue 3686 is not compiler-verifiable: it asks what the project publishes as
release artifacts, and no compiler invocation can answer that. So this directory
deliberately contains NO probe of the repro - there is no repro.

That absence needs to be distinguishable from "the worker never checked the
build", so the ground truth is identified here anyway, and this file is what a
reader should find when they wonder why there is no `out-main-debug.txt`.

Paths are derived from __file__ so this runs on any clone; the compiler is the
one `triage.py compiler --id main-debug` points at, at its conventional
location. Only the repo-relative path is printed.

Writes, next to itself:
  manual-case-ground-truth-version.txt
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[5]
DXC_REL = pathlib.PurePosixPath("build/Debug/bin/dxc.exe")

LINES = []


def emit(s=""):
    print(s)
    LINES.append(s)


def main():
    emit("# issue 3686 - ground-truth compiler identity")
    emit("# generated by check-ground-truth.py; re-run it to re-derive.")
    emit()
    emit("# WHY THERE IS NO out-main-debug.txt IN THIS DIRECTORY")
    emit("# The issue asks whether the project publishes macOS release binaries.")
    emit("# A compiler cannot answer that: a dxc that works perfectly and is")
    emit("# never uploaded to a release is precisely the reported situation. The")
    emit("# evidence is therefore release metadata and build configuration, in")
    emit("#   manual-case-release-assets.txt")
    emit("#   manual-case-ci-and-repo-config.txt")
    emit("#   manual-case-github-thread.txt")
    emit("# The build is identified below only so that 'not measured' is visibly")
    emit("# a decision rather than an omission.")
    emit()

    exe = REPO_ROOT / str(DXC_REL)
    emit(f"# compiler (repo-relative): {DXC_REL}")
    emit(f"# present: {exe.is_file()}")
    argv = [str(exe), "--version"]
    emit("$ " + subprocess.list2cmdline([str(DXC_REL), "--version"]))
    if not exe.is_file():
        emit("    (not built in this clone)")
        emit("    [exit n/a]")
    else:
        p = subprocess.run(argv, capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        body = ((p.stdout or "") + (p.stderr or "")).rstrip("\n")
        for line in (body.split("\n") if body else ["(no output)"]):
            emit("    " + line)
        emit(f"    [exit {p.returncode}]")
    emit()
    emit("# PROVENANCE CAVEAT - read this before citing the SHA above.")
    emit("# The binary self-reports '(triage, ab5400907)'. ab5400907 is a")
    emit("# fork-local merge commit orphaned by a history rewrite; it resolves")
    emit("# to nothing and must not be cited. The compiler sources this build")
    emit("# was made from are byte-identical to upstream main")
    emit("# 13730886e6a9019e4e0823746470f3ab75341d6b, which is the commit cited")
    emit("# in notes.md, comment.md and verdict.json. SKILL.md's tree check")
    emit("# (section 0 of manual-case-ci-and-repo-config.txt) is what")
    emit("# establishes that: 0 paths differ outside the triage skill directory.")

    (HERE / "manual-case-ground-truth-version.txt").write_text(
        "\n".join(LINES) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
