#!/usr/bin/env python3
"""Capture the GitHub-side thread evidence for issue 3686.

Three things the thread itself asserts, each checkable without running anything:

  * the issue was RE-TITLED in 2023 to track macOS only (comment 7) - so the
    title/body mismatch is deliberate, not staleness;
  * two other issues are cited as resolving part of it (#6057, #6770) - what
    happened to them?
  * whether triage itself has created any cross-reference on this issue. The
    triage workflow is read-only on GitHub, and a commit message containing
    "#3686" would silently break that. This is the check that proves it did not.

Read-only: `gh issue view` and `gh api` GET only.

Writes, next to itself:
  manual-case-github-thread.txt
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = "microsoft/DirectXShaderCompiler"

LINES = []


def emit(s=""):
    print(s)
    LINES.append(s)


def run(argv, note=None):
    emit("$ " + subprocess.list2cmdline(argv))
    if note:
        emit("# " + note)
    p = subprocess.run(argv, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    body = ((p.stdout or "") + (p.stderr or "")).rstrip("\n")
    for line in (body.split("\n") if body else ["(no output)"]):
        emit("    " + line)
    emit(f"    [exit {p.returncode}]")
    emit()
    return p


def main():
    emit("# issue 3686 - GitHub thread evidence")
    emit("# generated by collect-github-evidence.py; re-run it to re-derive.")
    emit()

    emit("=" * 72)
    emit("1. The re-title (comment 7, llvm-beanz, 2023-07-08)")
    emit("=" * 72)
    run(["gh", "api", f"repos/{REPO}/issues/3686/timeline?per_page=100",
         "--jq", '.[] | select(.event=="renamed") '
                 '| "\\(.created_at)  \\(.actor.login)  "'
                 '+ "\\(.rename.from)  ->  \\(.rename.to)"'],
        note="did the title actually change, and to what? The body still says"
             " 'Linux/macOS'; the title is the current scope.")

    emit("=" * 72)
    emit("2. State of the issues the thread cites as resolving part of this")
    emit("=" * 72)
    for n in (6057, 6770):
        run(["gh", "issue", "view", str(n), "--repo", REPO, "--json",
             "number,title,state,stateReason,closedAt", "--jq",
             '"#\\(.number) [\\(.state)\\(if .stateReason then " / " '
             '+ .stateReason else "" end)] \\(.closedAt // "")  \\(.title)"'])

    emit("=" * 72)
    emit("3. Cross-reference audit - did this triage post anything?")
    emit("=" * 72)
    run(["gh", "api", f"repos/{REPO}/issues/3686/timeline?per_page=100",
         "--jq", '.[] | select(.event=="cross-referenced") '
                 '| "\\(.created_at)  \\(.actor.login)  '
                 '#\\(.source.issue.number)"'],
        note="every event must PREDATE this triage. A cross-reference dated"
             " today would mean a commit message carried the issue number and"
             " the read-only rule was broken.")

    emit("=" * 72)
    emit("4. Is 3686 still the live tracking issue for this ask?")
    emit("=" * 72)
    run(["gh", "issue", "list", "--repo", REPO, "--state", "all",
         "--label", "macos", "--limit", "50", "--json",
         "number,title,state,createdAt", "--jq",
         '.[] | "#\\(.number) [\\(.state)] \\(.createdAt[0:10])  \\(.title)"'],
        note="every issue carrying the 'macos' label, open and closed")
    run(["gh", "issue", "list", "--repo", REPO, "--state", "open",
         "--search", "macOS in:title", "--limit", "50", "--json",
         "number,title,createdAt", "--jq",
         '.[] | "#\\(.number) \\(.createdAt[0:10])  \\(.title)"'],
        note="open issues with macOS in the title, label or not")

    (HERE / "manual-case-github-thread.txt").write_text(
        "\n".join(LINES) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
