#!/usr/bin/env python3
"""Capture the repo-side evidence for issue 3686 ("Binary release artifacts for macOS").

The question is what the project *publishes*, so half the evidence is release
metadata (see collect-release-assets.py) and half is the repo's own build/CI
configuration - captured here.

Read-only: every command below is a `git` query or a directory listing. Nothing
is written outside this directory.

Several of the findings are ABSENCE results ("nothing in the repo does X"), and
an absence result from a tool that silently found nothing is worthless. So every
absence check here is immediately followed by a POSITIVE CONTROL: the same tool,
the same scope, a pattern that is known to be present. If the control is empty,
the absence result above it means nothing and must be discarded.

Writes, next to itself:
  manual-case-ci-and-repo-config.txt
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
# <repo>/.github/skills/dxc-issue-triage/data/issues/3686/<this file>
REPO_ROOT = HERE.parents[5]

LINES = []


def emit(s=""):
    print(s)
    LINES.append(s)


def run(argv, note=None):
    emit("$ " + subprocess.list2cmdline(argv))
    if note:
        emit("# " + note)
    p = subprocess.run(argv, cwd=REPO_ROOT, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    out = (p.stdout or "") + (p.stderr or "")
    body = out.rstrip("\n")
    if body:
        for line in body.split("\n"):
            emit("    " + line)
    else:
        emit("    (no output)")
    emit(f"    [exit {p.returncode}]")
    emit()
    return p


def main():
    emit("# issue 3686 - repo build/CI configuration evidence")
    emit("# generated by collect-ci-evidence.py; re-run it from this directory to")
    emit("# re-derive this file. Paths are resolved from __file__, not hardcoded.")
    emit()

    emit("=" * 72)
    emit("0. What tree this evidence was gathered from")
    emit("=" * 72)
    run(["git", "rev-parse", "HEAD"])
    run(["git", "log", "-1", "--date=short",
         "--format=%H %ad %an %s", "13730886e6a9019e4e0823746470f3ab75341d6b"],
        note="the upstream commit the ground-truth 'main-debug' build corresponds to")
    p = subprocess.run(
        ["git", "diff", "--name-only",
         "13730886e6a9019e4e0823746470f3ab75341d6b", "HEAD"],
        cwd=REPO_ROOT, capture_output=True, text=True,
        encoding="utf-8", errors="replace")
    changed = [l for l in p.stdout.splitlines() if l.strip()]
    skill = ".github/skills/dxc-issue-triage/"
    outside = [l for l in changed if not l.startswith(skill)]
    emit("$ " + subprocess.list2cmdline(
        ["git", "diff", "--name-only",
         "13730886e6a9019e4e0823746470f3ab75341d6b", "HEAD"]) + "   (summarised)")
    emit("# SKILL.md's tree check: what makes a build ground truth for main is that")
    emit("# no compiler SOURCE differs from main. The raw list is hundreds of triage")
    emit("# artifacts, so it is summarised; the assertion is that 'outside' is empty.")
    emit(f"    paths changed in total .................. {len(changed)}")
    emit(f"    of those, under {skill} ... {len(changed) - len(outside)}")
    emit(f"    of those, OUTSIDE it (must be 0) ....... {len(outside)}")
    for l in outside:
        emit("      !! " + l)
    emit(f"    [exit {p.returncode}]")
    emit()

    emit("=" * 72)
    emit("1. Does the repo's CI build macOS?  (positive result expected)")
    emit("=" * 72)
    run(["git", "grep", "-n", "-i", "-E", "macos|darwin",
         "--", "azure-pipelines.yml"])

    emit("=" * 72)
    emit("2. Does the repo's CI PUBLISH anything from the macOS/Linux job?")
    emit("=" * 72)
    run(["git", "grep", "-n", "-E", "Publish[A-Za-z]*@|artifactName|artifact:",
         "--", "azure-pipelines.yml"],
        note="every publish step and artifact name in the pipeline; note which"
             " job each one sits in")

    emit("=" * 72)
    emit("3. ABSENCE: does anything in-repo produce a release asset name?")
    emit("=" * 72)
    run(["git", "grep", "-n", "-i", "linux_dxc"],
        note="ABSENCE CHECK. 'linux_dxc_<date>.x86_64.tar.gz' is the name of the"
             " Linux asset on every release since v1.7.2212. Exit 1 = not found.")
    run(["git", "grep", "-n", "MacOS_Clang_Release"],
        note="POSITIVE CONTROL for the check above: same tool, same scope, a"
             " string that is definitely present. Must print a hit.")

    emit("=" * 72)
    emit("4. ABSENCE: any macOS, or any release publishing, in .github/workflows?")
    emit("=" * 72)
    run(["git", "ls-files", ".github/workflows"])
    run(["git", "grep", "-n", "-i", "-E", "macos|darwin|apple",
         "--", ".github/workflows"],
        note="ABSENCE CHECK. Exit 1 = no workflow mentions macOS at all.")
    run(["git", "grep", "-n", "-i", "-E",
         "gh release|softprops|upload-release|create-release|actions/upload-artifact",
         "--", ".github/workflows"],
        note="ABSENCE CHECK. Exit 1 = no workflow uploads a release asset."
             " (A bare 'release' pattern is useless here: it matches"
             " CMAKE_BUILD_TYPE=Release.)")
    run(["git", "grep", "-n", "jobs:", "--", ".github/workflows"],
        note="POSITIVE CONTROL for both checks above: same tool, same pathspec."
             " Must print a hit per file, or the two zeroes mean nothing.")

    emit("=" * 72)
    emit("5. ABSENCE: is the AppVeyor build from comment 1 still configured here?")
    emit("=" * 72)
    run(["git", "grep", "-n", "-i", "appveyor", "--", "*.yml", "*.yaml", "*.md"],
        note="ABSENCE CHECK. Comment 1 (2021-04-14) pointed users at an AppVeyor"
             " build on a contributor fork. Exit 1 = no AppVeyor config in-tree.")
    run(["git", "grep", "-n", "-i", "ninja", "--", "*.yml", "*.yaml", "*.md"],
        note="POSITIVE CONTROL for the check above: same tool, same pathspec,"
             " a word known to appear in both a root .yml and .github/workflows."
             " Must print hits from more than one directory.")

    emit("=" * 72)
    emit("6. How long has macOS been a CI configuration?")
    emit("=" * 72)
    run(["git", "log", "--date=short", "--format=%h %ad %an %s",
         "-S", "macOS", "--", "azure-pipelines.yml"])
    run(["git", "log", "--date=short", "--format=%h %ad %an %s",
         "-S", "osx", "--", ".travis.yml"],
        note=".travis.yml was deleted by the Azure DevOps migration; -S still"
             " searches its history")

    emit("=" * 72)
    emit("7. The DXIL signing blocker several commenters cite (issue 6770)")
    emit("=" * 72)
    run(["git", "ls-files", "*DxilHash*"])
    run(["git", "grep", "-n", "DxilHash", "--",
         "tools/clang/tools/dxildll/CMakeLists.txt",
         "tools/clang/tools/dxcvalidator/CMakeLists.txt"],
        note="the in-tree hash library is linked into the in-tree validator and"
             " into dxildll, the in-tree dxil.dll")
    run(["git", "grep", "-n", "add_subdirectory(dxildll)", "--",
         "tools/clang/tools/CMakeLists.txt"],
        note="unconditional - not guarded by if(WIN32)")

    emit("=" * 72)
    emit("8. The other in-repo pipelines: which platforms produce a downloadable")
    emit("   artifact at all?")
    emit("=" * 72)
    run(["git", "ls-files", "gcp-pipelines"])
    run(["git", "grep", "-n", "-E", "artifacts:|location:|paths:|dxc-artifacts",
         "--", "gcp-pipelines"],
        note="these Cloud Build pipelines DO upload a build artifact to a public"
             " bucket - so the repo does contain artifact-publishing config, just"
             " not for macOS")
    run(["git", "grep", "-n", "-i", "-E", "macos|darwin|apple", "--",
         "gcp-pipelines"],
        note="ABSENCE CHECK. Exit 1 = no macOS Cloud Build pipeline.")
    run(["git", "grep", "-c", "-i", "cmake", "--", "gcp-pipelines"],
        note="POSITIVE CONTROL for the check above: same tool, same pathspec."
             " Must print a hit. (A 'linux' control fails here - the word is in"
             " the filename, not the file - which is exactly why controls are"
             " chosen from content, not from names.)")
    run(["git", "log", "--date=short", "--format=%h %ad %an %s", "--",
         "gcp-pipelines"],
        note="when the artifact-publishing pipelines were added")

    (HERE / "manual-case-ci-and-repo-config.txt").write_text(
        "\n".join(LINES) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
