#!/usr/bin/env python3
"""Collect the asset list of every published GitHub release of DXC.

Evidence generator for issue 3686 ("Binary release artifacts for macOS"). The
question that issue asks is not about compiler behaviour, it is about what the
project publishes - so the measurement is release metadata, not compiler output.

Read-only: it runs `gh release list` and `gh release view` and nothing else.

Writes, next to itself:
  release-assets.json          the raw `gh` payload, so the classification below
                               can be re-checked without re-running `gh`
  manual-case-release-assets.txt  a human-readable listing + platform summary

Every command is echoed with subprocess.list2cmdline(argv), i.e. exactly what
was executed rather than a transcription of it.
"""
import json
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = "microsoft/DirectXShaderCompiler"

# Substrings that identify the platform an asset targets. Matched against the
# lower-cased asset name. Order matters only for reporting.
PLATFORM_PATTERNS = [
    ("macos", (r"macos", r"mac-os", r"\bosx\b", r"darwin", r"apple",
               r"universal", r"\.dmg$", r"\.pkg$", r"aarch64-apple", r"arm64-apple")),
    ("linux", (r"linux", r"ubuntu", r"debian", r"\.deb$", r"\.rpm$",
               r"gnu", r"clang-linux")),
    ("windows", (r"^dxc[_-]", r"windows", r"win32", r"win64", r"\.msi$",
                 r"\.nupkg$", r"\.exe$")),
]


def gh(*args):
    argv = ["gh", *args]
    print("$ " + subprocess.list2cmdline(argv))
    out = subprocess.run(argv, capture_output=True, text=True,
                         encoding="utf-8", errors="replace")
    if out.returncode != 0:
        print(f"  (gh exited {out.returncode}) {out.stderr.strip()}")
        return None
    return out.stdout


def classify(name):
    low = name.lower()
    hits = [plat for plat, pats in PLATFORM_PATTERNS
            if any(re.search(p, low) for p in pats)]
    if not hits:
        return "unclassified"
    # A name matching several buckets is reported as all of them, so a
    # mis-heuristic is visible rather than silently resolved.
    return "+".join(hits)


def main():
    lines = []

    def emit(s=""):
        print(s)
        lines.append(s)

    emit("# issue 3686 - assets attached to every GitHub release of " + REPO)
    emit("# generated by collect-release-assets.py; re-run it to re-derive this file")
    emit()

    argv = ["release", "list", "--repo", REPO, "--limit", "200", "--json",
            "tagName,name,publishedAt,isDraft,isPrerelease,isLatest"]
    emit("$ " + subprocess.list2cmdline(["gh", *argv]))
    raw = gh(*argv)
    if raw is None:
        return 1
    releases = json.loads(raw)
    emit(f"# {len(releases)} entries returned")
    emit()

    # `gh release list` includes drafts, but a draft can have an empty tag.
    # Passing that empty string to `gh release view` does NOT select the draft:
    # gh silently falls back to the latest published release. Query drafts by
    # REST release id instead, and capture the fallback as a regression guard.
    emit("=" * 72)
    emit("UNPUBLISHED DRAFTS - queried by release id, excluded from published totals")
    emit("=" * 72)
    api_argv = ["api", f"repos/{REPO}/releases?per_page=100"]
    emit("$ " + subprocess.list2cmdline(["gh", *api_argv]))
    all_raw = gh(*api_argv)
    if all_raw is None:
        return 1
    drafts = [r for r in json.loads(all_raw) if r.get("draft")]
    if not drafts:
        emit("(none)")
    for draft in drafts:
        assets = draft.get("assets") or []
        emit(f"draft id={draft['id']} tag={draft.get('tag_name')!r} "
             f"created={draft.get('created_at')} assets={len(assets)}")
        for asset in assets:
            emit(f"     {classify(asset['name']):>16}  {asset['name']}  "
                 f"({asset.get('size', 0)} bytes, "
                 f"{asset.get('download_count', 0)} downloads)")
        if not assets:
            emit("     (no assets)")
    emit()

    empty_argv = ["release", "view", "", "--repo", REPO, "--json",
                  "tagName,isDraft,assets"]
    emit("$ " + subprocess.list2cmdline(["gh", *empty_argv]))
    empty_raw = gh(*empty_argv)
    if empty_raw is not None:
        empty_view = json.loads(empty_raw)
        emit("empty-tag lookup resolves to "
             f"tag={empty_view.get('tagName')!r}, "
             f"isDraft={empty_view.get('isDraft')}, "
             f"assets={len(empty_view.get('assets') or [])}")
        emit("Do not use an empty tag to inspect a draft; it double-counts the "
             "latest published release.")
    emit()

    releases.sort(key=lambda r: r.get("publishedAt") or "")

    collected = []
    for rel in releases:
        tag = rel.get("tagName") or ""
        if not tag:
            emit(f"-- excluding unpublished draft with no tag: "
                 f"name={rel.get('name')!r} "
                 f"publishedAt={rel.get('publishedAt')!r}; see REST census above")
            emit()
            continue
        vargv = ["release", "view", tag, "--repo", REPO, "--json",
                 "tagName,name,publishedAt,isDraft,isPrerelease,assets"]
        emit("$ " + subprocess.list2cmdline(["gh", *vargv]))
        vraw = gh(*vargv)
        if vraw is None:
            emit("   FAILED")
            emit()
            continue
        view = json.loads(vraw)
        collected.append(view)
        assets = view.get("assets") or []
        flags = []
        if view.get("isPrerelease"):
            flags.append("prerelease")
        if view.get("isDraft"):
            flags.append("draft")
        emit(f"   {tag}  published={view.get('publishedAt')}  "
             f"assets={len(assets)}{'  [' + ','.join(flags) + ']' if flags else ''}")
        for a in assets:
            emit(f"     {classify(a['name']):>16}  {a['name']}  "
                 f"({a.get('size', 0)} bytes, {a.get('downloadCount', 0)} downloads)")
        if not assets:
            emit("     (no assets)")
        emit()

    (HERE / "release-assets.json").write_text(
        json.dumps(collected, indent=2), encoding="utf-8")

    emit("=" * 72)
    emit("SUMMARY - releases carrying at least one asset of each platform class")
    emit("=" * 72)
    emit(f"{'tag':<32} {'published':<12} {'macos':<7} {'linux':<7} {'windows':<8} total")
    for view in collected:
        assets = view.get("assets") or []
        buckets = [classify(a["name"]) for a in assets]
        n_mac = sum(1 for b in buckets if "macos" in b)
        n_lin = sum(1 for b in buckets if "linux" in b)
        n_win = sum(1 for b in buckets if "windows" in b)
        emit(f"{view['tagName']:<32} {(view.get('publishedAt') or '')[:10]:<12} "
             f"{n_mac:<7} {n_lin:<7} {n_win:<8} {len(assets)}")
    emit()
    total_mac = sum(1 for v in collected for a in (v.get("assets") or [])
                    if "macos" in classify(a["name"]))
    total_lin = sum(1 for v in collected for a in (v.get("assets") or [])
                    if "linux" in classify(a["name"]))
    total_assets = sum(len(v.get("assets") or []) for v in collected)
    rel_with_lin = sum(1 for v in collected
                       if any("linux" in classify(a["name"])
                              for a in (v.get("assets") or [])))
    rel_with_mac = sum(1 for v in collected
                       if any("macos" in classify(a["name"])
                              for a in (v.get("assets") or [])))
    first_lin = next((v["tagName"] for v in collected
                      if any("linux" in classify(a["name"])
                             for a in (v.get("assets") or []))), None)
    emit(f"published releases enumerated ............. {len(collected)}")
    emit(f"assets across all of them ................. {total_assets}")
    emit(f"  ... classified macOS ................... {total_mac}")
    emit(f"  ... classified Linux ................... {total_lin}")
    emit(f"releases carrying >=1 macOS asset ......... {rel_with_mac}")
    emit(f"releases carrying >=1 Linux asset ......... {rel_with_lin}"
         f"  (first: {first_lin})")
    if collected:
        emit(f"oldest release ............................ {collected[0]['tagName']}"
             f"  {(collected[0].get('publishedAt') or '')[:10]}")
        emit(f"newest release ............................ {collected[-1]['tagName']}"
             f"  {(collected[-1].get('publishedAt') or '')[:10]}")
    emit()
    emit("The macOS count above rests on a name heuristic, so it is not the")
    emit("primary evidence. The primary evidence is the per-release listing")
    emit("earlier in this file: every one of these asset names can be read by")
    emit("eye. They comprise Windows binary/symbol archives, Linux archives")
    emit("(including preview and clang-cl variants), and dxil.zip on the 2017")
    emit("alpha. None has a macOS-shaped name.")
    emit()
    emit("Unclassified asset names (check these by eye - the heuristic above is")
    emit("not authoritative, and a macOS asset named unexpectedly would land here):")
    seen = set()
    for v in collected:
        for a in (v.get("assets") or []):
            if classify(a["name"]) == "unclassified" and a["name"] not in seen:
                seen.add(a["name"])
                emit(f"    {a['name']}")
    if not seen:
        emit("    (none)")
    emit()

    emit("=" * 72)
    emit("POSITIVE CONTROL for the macOS classifier")
    emit("=" * 72)
    emit("'0 macOS assets' is an ABSENCE result, and an absence result from a")
    emit("classifier that cannot recognise the thing it is looking for is")
    emit("worthless. So: names macOS assets would plausibly carry, run through")
    emit("the same classify() used above. Every line must say macos.")
    probes = [
        "macos_dxc_2026_07_29.arm64.tar.gz",
        "dxc_2026_07_29_macOS.zip",
        "dxc-universal-apple-darwin.tar.gz",
        "dxc_aarch64-apple-darwin.tar.gz",
        "dxc-osx-x86_64.tar.gz",
        "DirectXShaderCompiler.dmg",
        "dxc-1.9.2607.pkg",
    ]
    ok = True
    for name in probes:
        got = classify(name)
        flag = "OK  " if "macos" in got else "FAIL"
        ok = ok and "macos" in got
        emit(f"    {flag}  {got:>16}  {name}")
    emit()
    emit("    control result: " + ("PASS - the zero above is a real zero"
                                   if ok else
                                   "FAIL - discard the macOS count above"))
    emit()
    emit("Negative half of the control: no name actually present on a release")
    emit("classifies as macOS, which is the finding. The two halves together")
    emit("say the classifier discriminates rather than always answering no.")

    (HERE / "manual-case-release-assets.txt").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
