"""#3954: is the v1.8.2502+ behaviour a real fix, or just a silenced crash?

`Param.Matrix[2].r.xxx` and the reporter's own workaround `Param.Matrix[2].xxx` are
semantically the same expression -- `.r` selects component 0 of the row and `.xxx`
splats component 0 -- so a correct compiler must emit identical DXIL for repro.hlsl and
control-workaround.hlsl. That identity is the check this script performs, on every build
that can compile the repro at all.

Writes manual-case-identity.txt. Every command is echoed with
subprocess.list2cmdline(argv), so the file records what was actually run rather than a
transcription of it.

Run from this directory:  python check-identity.py
"""

import hashlib
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
REPO = os.path.abspath(os.path.join(SKILL, "..", "..", ".."))
REGISTRY = os.path.join(SKILL, ".cache", "compilers")

# Compiler ids to try, oldest first. Ones whose registry entry is missing are skipped
# and reported, so a fresh clone gets a readable file rather than a traceback.
COMPILERS = [
    "rel-1.4.1907-3954",
    "rel-1.6.2106-3954",
    "rel-1.8.2407-3954",
    "rel-1.8.2502-3954",
    "main-debug",
]

ARGS = ["-T", "lib_6_3"]
CASES = ["repro.hlsl", "control-workaround.hlsl"]


def display(path):
    """Machine-independent rendering: anchor on the repository, never a layout.

    Falls back through progressively weaker anchors and, in the worst case, to a
    bare basename -- so this never emits an absolute path from someone's machine
    regardless of where the repository or the compiler cache happens to live.
    """
    normalised = path.replace("\\", "/")
    try:
        inside = os.path.relpath(path, REPO)
        if not inside.startswith(".."):
            return "<repo>/" + inside.replace("\\", "/")
    except ValueError:
        pass
    parts = normalised.split("/")
    for anchor, label in (("DirectXShaderCompiler", "<repo>"),):
        if anchor in parts:
            return "/".join([label] + parts[parts.index(anchor) + 1:])
    return "<elsewhere>/" + parts[-1]


def main():
    out = []
    out.append("# #3954 -- DXIL identity between the repro and the reporter's workaround")
    out.append("# generated by check-identity.py; do not hand-edit")
    out.append("#")
    out.append("# `Param.Matrix[2].r.xxx` (repro.hlsl) and `Param.Matrix[2].xxx`")
    out.append("# (control-workaround.hlsl) denote the same value. A build that compiles")
    out.append("# both must produce the same DXIL; a build that fails on either cannot be")
    out.append("# compared and is reported as such.")
    out.append("")

    rows = []
    for cid in COMPILERS:
        reg = os.path.join(REGISTRY, cid + ".json")
        if not os.path.exists(reg):
            out.append("=== %s: NOT REGISTERED (%s missing) ===" % (cid, cid + ".json"))
            out.append("")
            rows.append((cid, "not-registered", "", ""))
            continue
        exe = json.load(open(reg))["exe_path"]
        out.append("=== %s ===" % cid)
        out.append("[exe] %s" % display(exe))
        digests = {}
        statuses = {}
        for case in CASES:
            argv = [exe] + ARGS + [case]
            out.append("$ " + subprocess.list2cmdline([display(exe)] + ARGS + [case]))
            p = subprocess.run(argv, cwd=HERE, capture_output=True)
            statuses[case] = p.returncode
            out.append("[exit] 0x%08X" % (p.returncode & 0xFFFFFFFF))
            if p.returncode == 0:
                digests[case] = hashlib.sha256(p.stdout).hexdigest()
                out.append("[sha256 of disassembly] %s" % digests[case])
            else:
                err = p.stderr.decode("utf-8", "replace").strip()
                out.append("[stderr] %s" % (err if err else "<empty>"))
        if len(digests) == len(CASES):
            same = len(set(digests.values())) == 1
            verdict = "IDENTICAL" if same else "DIFFERENT"
        else:
            verdict = "NOT COMPARABLE (a case failed to compile)"
        out.append("[result] %s" % verdict)
        out.append("")
        rows.append((cid, verdict, statuses[CASES[0]], statuses[CASES[1]]))

    out.append("--- summary ---")
    for cid, verdict, a, b in rows:
        out.append("%-20s %s" % (cid, verdict))

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "manual-case-identity.txt"), "w") as f:
        f.write(text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
