"""#3954: what would a message-matching predicate have concluded?

This issue's brief named one hazard above all others: on a crash-shaped issue, matching the
crash's *message text* instead of using the `internal_failure` predicate produces a
fabricated fix boundary. #3954 turns out to be an unusually sharp instance, because the same
defect is worded four different ways across the twenty probed releases and is silent on two
of them.

This script re-scores every captured probe under four predicates and prints the release
history each one would have reported. It reads the committed `out-*.txt` captures and
`triage.py`'s own `is_internal_failure`, so it re-derives rather than restates.

Writes manual-case-predicate-counterfactual.txt.

Run from this directory:  python check-predicate-counterfactual.py
"""

import glob
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))

_spec = importlib.util.spec_from_file_location(
    "triage", os.path.join(SCRIPTS, "triage.py"))
triage = importlib.util.module_from_spec(_spec)
sys.modules["triage"] = triage
_spec.loader.exec_module(triage)


def status_only(text, rc, timed_out):
    """`internal_failure` with the text markers removed -- exit status alone."""
    return triage.is_internal_failure("", rc, timed_out)


PREDICATES = [
    ("internal_failure (as used)",
     lambda t, rc, to: triage.is_internal_failure(t, rc, to)),
    ("exit status only, no text markers", status_only),
    ("contains the reporter's full quoted line",
     lambda t, rc, to: "Internal Compiler error: Unexpected matrix subscript use." in t),
    ("contains 'Unexpected matrix subscript use.'",
     lambda t, rc, to: "Unexpected matrix subscript use." in t),
]


def order_key(tag):
    if tag == "main-debug":
        return (2, ())
    m = re.findall(r"\d+", tag)
    return (1, tuple(int(x) for x in m))


def load(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    rc = None
    for line in text.splitlines():
        if line.startswith("# exit:"):
            rc = int(line.split(":", 1)[1].strip())
            break
    body = text.split("--- stdout ---", 1)
    return (body[1] if len(body) > 1 else text), rc


def history(results, tags):
    """Render the boundary a bisect over these results would have reported."""
    seq = [(t, results[t]) for t in tags if t != "main-debug"]
    if not seq:
        return "no releases"
    changes = []
    for i in range(1, len(seq)):
        if seq[i][1] != seq[i - 1][1]:
            changes.append("%s -> %s at %s"
                           % ("repro" if seq[i - 1][1] else "clean",
                              "repro" if seq[i][1] else "clean",
                              seq[i][0]))
    if not changes:
        return "always %s" % ("repro'd" if seq[0][1] else "clean")
    return "; ".join(changes)


def main():
    caps = {}
    for path in glob.glob(os.path.join(HERE, "out-*.txt")):
        tag = os.path.basename(path)[len("out-"):-len(".txt")]
        caps[tag] = load(path)
    tags = sorted(caps, key=order_key)

    out = []
    out.append("# #3954 -- what a message-matching predicate would have concluded")
    out.append("# generated by check-predicate-counterfactual.py; do not hand-edit")
    out.append("#")
    out.append("# Re-scores the committed out-*.txt captures under four predicates.")
    out.append("# 'repro' = predicate fired. Only the first predicate is the one used.")
    out.append("")

    scored = {}
    for name, fn in PREDICATES:
        scored[name] = {t: bool(fn(caps[t][0], caps[t][1], False)) for t in tags}

    width = max(len(t) for t in tags) + 2
    header = "".ljust(width) + "".join("  %-6s" % ("P%d" % (i + 1))
                                       for i in range(len(PREDICATES)))
    out.append(header + "   exit")
    for t in tags:
        row = t.ljust(width)
        for name, _ in PREDICATES:
            row += "  %-6s" % ("repro" if scored[name][t] else ".")
        rc = caps[t][1]
        row += "   0x%08X" % (rc & 0xFFFFFFFF) if rc is not None else "   ?"
        out.append(row)
    out.append("")

    for i, (name, _) in enumerate(PREDICATES):
        out.append("P%d  %s" % (i + 1, name))
        out.append("    history: %s" % history(scored[name], tags))
        n = sum(1 for t in tags if t != "main-debug" and scored[name][t])
        out.append("    releases scored repro: %d of %d"
                   % (n, len([t for t in tags if t != "main-debug"])))
        out.append("")

    out.append("--- why they differ ---")
    out.append("Four wordings and two silences, all of the same defect:")
    out.append("  v1.4.1907, v1.5.2010   0xC0000005, stderr COMPLETELY EMPTY")
    out.append("  v1.6.2104              0xE0000002, 'Internal compiler error: LLVM Unreachable'")
    out.append("  v1.6.2106, v1.6.2112   0x80AA001C, 'Internal Compiler error: <message>'")
    out.append("  v1.7.2207 .. v1.8.2407 0x80004005 (E_FAIL), 'error: <message>'")
    out.append("")
    out.append("E_FAIL is deliberately NOT in triage.py's INTERNAL_STATUS -- an ordinary")
    out.append("syntax error exits with it too -- so those nine releases are classified by")
    out.append("the build-agnostic 'UNREACHABLE executed' marker, not by exit status. Both")
    out.append("halves of is_internal_failure() are load-bearing here: neither alone")
    out.append("recovers the true range.")

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "manual-case-predicate-counterfactual.txt"), "w",
              encoding="utf-8") as f:
        f.write(text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
