"""#3954: which release, if any, produced the output the reporter quoted?

The issue body quotes two lines of compiler output but does not name a build ("the latest
revision of the master branch", 2021-09-17). This compares that quote against every
captured release probe, normalising only the source-tree root -- the reporter built
locally, so their path prefix is their checkout while a release binary carries its build
agent's. Everything after `lib/HLSL/` is compared verbatim, including the line number.

Reads issue.json for the quote so the comparison cannot drift from the fetched issue.
Writes manual-case-reporter-quote.txt.

Run from this directory:  python check-quote.py
"""

import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Lines of compiler output the reporter quoted, extracted from the issue body's first
# fenced block rather than retyped.
QUOTE_BLOCK_INDEX = 0


def normalise(line):
    """Drop the source-tree root so a local build and a build agent compare equal.

    Anchored on the `UNREACHABLE executed at ` marker and on `lib/HLSL/`, so it cannot
    rewrite anything but the path prefix. Handles both an absolute build-agent path
    (`D:\\agent\\_work\\8\\s\\lib\\HLSL\\...`) and the reporter's relative one
    (`DirectXShaderCompiler\\lib\\HLSL\\...`).
    """
    line = line.strip().replace("\\", "/")
    line = re.sub(r"(UNREACHABLE executed at )\S*?(lib/HLSL/)", r"\1\2", line)
    return line


def main():
    issue = json.load(open(os.path.join(HERE, "issue.json"), encoding="utf-8"))
    blocks = re.findall(r"```(?:\w*)\r?\n(.*?)```", issue["body"], re.S)
    if not blocks:
        sys.exit("no fenced block found in issue.json body")
    quoted = [normalise(l) for l in blocks[QUOTE_BLOCK_INDEX].splitlines() if l.strip()]

    out = []
    out.append("# #3954 -- reporter-quoted output vs every captured release probe")
    out.append("# generated by check-quote.py; do not hand-edit")
    out.append("#")
    out.append("# The reporter named no build. Source-tree roots are normalised away;")
    out.append("# the message text and the source line number are compared verbatim.")
    out.append("")
    out.append("--- quoted in the issue body (normalised) ---")
    out.extend(quoted)
    out.append("")

    matches = []
    for path in sorted(glob.glob(os.path.join(HERE, "out-*.txt"))):
        name = os.path.basename(path)[len("out-"):-len(".txt")]
        text = open(path, encoding="utf-8", errors="replace").read()
        body = text.split("--- stderr ---", 1)
        err = body[1] if len(body) > 1 else ""
        got = [normalise(l) for l in err.splitlines() if l.strip()]
        same = got == quoted
        out.append("=== %s: %s ===" % (name, "MATCHES QUOTE" if same else "differs"))
        out.extend(got if got else ["<empty stderr>"])
        out.append("")
        if same:
            matches.append(name)

    out.append("--- summary ---")
    out.append("captures matching the quoted output exactly: %s"
               % (", ".join(matches) if matches else "none"))
    out.append("")
    out.append("SELF-TEST: the comparison must be able to reject as well as accept.")
    out.append("v1.6.2104 also fails internally on this repro but prints a different")
    out.append("message ('Internal compiler error: LLVM Unreachable'), and v1.7.2207+")
    out.append("print the same text under an 'error:' prefix at a different line number.")
    out.append("Those appear above as 'differs'; if every capture were reported as")
    out.append("matching, the normalisation would be erasing the thing under test.")
    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "manual-case-reporter-quote.txt"), "w",
              encoding="utf-8") as f:
        f.write(text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
