"""Score issue 4629's ARCHIVED captures under two candidate predicates.

No compiler is run: this reads the files already on disk and asks what each
predicate would have concluded from them. The point is to make the two traps
named in the method concrete and re-derivable rather than asserted in prose.

  A. the predicate actually used -- match.json, kind=internal_failure
  B. the tempting one            -- contains "llvm::cast<X>", the exact string
                                    the issue title and body report

Trap B is the false-"fixed" generator: the Debug ground-truth build stops at a
DXASSERT whose text says nothing about casts, so B scores the one build that
demonstrably crashes as clean.

A third column records the raw exit status, to show that "nonzero exit" cannot
be used as a crash test here: the bad-cast path and an ordinary parse error both
exit 0x80004005.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

TEXT_ONLY = {"kind": "contains", "value": "llvm::cast<X>"}
OUT = "manual-case-predicate-trap.txt"


def main():
    rows = []
    names = sorted(n for n in os.listdir(HERE)
                   if (n.startswith("out-") or n.startswith("variant-"))
                   and n.endswith(".txt"))
    for name in names:
        meta, body = triage.read_out(os.path.join(HERE, name))
        rc = None if meta.get("exit") in (None, "None", "TIMEOUT") \
            else int(meta["exit"])
        timed_out = meta.get("timed_out") == "1"
        a = "match" if triage._eval_match(
            json.load(open(os.path.join(HERE, "match.json"), encoding="utf-8")),
            body, rc, timed_out, "match.json") else "no-match"
        b = "match" if triage._eval_match(
            TEXT_ONLY, body, rc, timed_out, "<demo>") else "no-match"
        rc_s = "n/a" if rc is None else "0x%08X" % (rc & 0xFFFFFFFF)
        rows.append((name, rc_s, a, b, meta.get("verdict", "?")))

    w = max(len(r[0]) for r in rows)
    lines = []
    lines.append("issue 4629 -- what each candidate predicate concludes from the")
    lines.append("captures already committed in this directory. No compiler was run;")
    lines.append("generated by demo-predicate-trap.py.")
    lines.append("")
    lines.append("  A = match.json           (kind: internal_failure)   <- used")
    lines.append('  B = contains "llvm::cast<X>"  (the reported message) <- rejected')
    lines.append("")
    lines.append("%-*s  %-10s  %-8s  %-8s  %s"
                 % (w, "capture", "exit", "A", "B", "recorded verdict"))
    lines.append("%-*s  %-10s  %-8s  %-8s  %s"
                 % (w, "-" * w, "-" * 10, "-" * 8, "-" * 8, "-" * 16))
    for name, rc_s, a, b, v in rows:
        lines.append("%-*s  %-10s  %-8s  %-8s  %s" % (w, name, rc_s, a, b, v))
    lines.append("")
    lines.append("Read the out-main-debug.txt row. Predicate B scores the ground-truth")
    lines.append("build -- which stops at a DXASSERT and exits 0x80000003 -- as no-match,")
    lines.append("because the Debug assert text contains no 'cast<X>' substring at all.")
    lines.append("Used as the issue predicate, B reports this crash as FIXED on main and")
    lines.append("on every release build whose wording differs, including CE's Linux")
    lines.append("build, which prints plain 'cast<X>()' without the 'llvm::' qualifier.")
    lines.append("")
    lines.append("Read the two error controls next. control-parseerror (a missing")
    lines.append("semicolon) and control-syntaxerror (an undeclared type) both exit")
    lines.append("0x80004005 -- byte-identical to the status the DXC_E_LLVM_CAST_ERROR")
    lines.append("path returns -- and neither scores as a reproduction. That is why the")
    lines.append("exit code alone cannot be used as the crash test either.")
    with open(os.path.join(HERE, OUT), "w", encoding="utf-8", newline="\n") as f:
        f.write(triage.redact_paths("\n".join(lines)) + "\n")
    print(OUT, "<-", len(rows), "captures scored")


if __name__ == "__main__":
    sys.exit(main())
