"""Generate the cdb stack captures for issue 4629.

Two questions, two invocations, one file each:

  manual-case-assert-stack.txt   what the Debug ground-truth build stops on
  manual-case-ndebug-stack.txt   what that same build does when the assert is
                                 stepped over -- `gh` ("go handled") emulates
                                 NDEBUG, so this is the code a Release build
                                 runs with the DXASSERT compiled out

The second is the one that matters for this issue: it shows the Debug binary
producing the *reporter's* symptom (the bad `llvm::cast<X>`) once the guard is
removed, which is what ties the two signatures to a single defect rather than
two.

`subprocess.list2cmdline` prints exactly what was executed, so the command line
in each capture is an observation and not a transcription. Output is passed
through `triage.redact_paths()` because a Debug build bakes __FILE__ into its
assert text.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
DXC = os.path.join(triage.REPO_ROOT, "build", "Debug", "bin", "dxc.exe")
ARGS = ["-T", "ps_6_5", "-E", "PSMain", "-HV", "2021", "repro.hlsl"]
# The history configuration: same source, oldest profile and flag set that still
# shows the symptom. Captured so the widening is a measured equivalence rather
# than an assumption -- it must stop at the same assert, in the same frames.
WIDE_ARGS = ["-T", "ps_6_0", "-E", "PSMain", "repro.hlsl"]

CASES = [
    ("manual-case-assert-stack.txt", ARGS,
     "g;kn 12;q",
     "Run to the __debugbreak() the DXASSERT raises and dump the stack. This is\n"
     "the Debug ground-truth signature: a trapped assert, exit 0x80000003.\n"
     "Command line is the reporter's, exactly as filed."),
    ("manual-case-ndebug-stack.txt", ARGS,
     "g;gh;.lastevent;kn 12;q",
     "Run to the same assert, then `gh` (go handled) past it. Continuing past a\n"
     "__debugbreak() emulates NDEBUG: execution proceeds into the code a Release\n"
     "build would run with the DXASSERT compiled to `do {} while (0)`.\n"
     "What it reaches is the reporter's reported symptom."),
    ("manual-case-widened-stack.txt", WIDE_ARGS,
     "g;kn 6;q",
     "The widened history configuration -- ps_6_0, no -HV 2021 -- which the\n"
     "release scan uses because far more releases can express it. This capture\n"
     "is the evidence that widening did not change what is being measured: same\n"
     "assert, same file and line, same top frames as the as-filed command."),
]


def main():
    for name, args, script, why in CASES:
        argv = [CDB, "-c", script, DXC] + args
        # cdb must be launched through cmd.exe: from PowerShell it produces no
        # output at all, which reads as "the debugger found nothing".
        cmdline = subprocess.list2cmdline(argv)
        # `cmd /c "<quoted exe> ..."` fails with "is not recognized"; /s plus an
        # outer quote pair is the documented idiom for a command whose first
        # token is itself quoted. Passed as a verbatim string so subprocess does
        # not re-quote it.
        p = subprocess.run('cmd.exe /s /c "' + cmdline + ' 2>&1"', cwd=HERE,
                           capture_output=True, text=True, errors="replace")
        body = triage.redact_paths(p.stdout + p.stderr)
        lines = [ln for ln in body.splitlines()
                 if keep(ln)]
        with open(os.path.join(HERE, name), "w", encoding="utf-8", newline="\n") as f:
            f.write("# issue 4629 -- cdb capture, generated by make-stacks.py\n")
            f.write("# purpose:\n")
            for ln in why.splitlines():
                f.write("#   " + ln + "\n")
            f.write("# cdb exit: %d\n" % p.returncode)
            f.write("#\n")
            f.write("$ " + triage.redact_paths(cmdline) + "\n\n")
            f.write("\n".join(lines) + "\n")
        print(name, "<-", len(lines), "lines kept, cdb exit", p.returncode)


def keep(ln):
    """Trim a full cdb transcript to the header, the failure and the frames.

    A full dump is thousands of lines of module loads; the SKILL asks for the
    header, the assert line and the frames.
    """
    markers = ("Break instruction exception", "Access violation",
               "Error: ", "File:", "Func:", "expected struct bitcast",
               "ScalarReplAggregatesHLSL", "Last event", "lastevent",
               "cast<", "Internal compiler error", "Assertion",
               "Child-SP", "exit code", "Terminal Error",
               "This dump file", "second chance", "first chance",
               "!(onlyUsedByLifetimeMarkers")
    if any(m in ln for m in markers):
        return True
    stripped = ln.strip()
    # stack frame rows look like "00 000000b8`c63844a0 ... dxcompiler!..."
    if "!" in ln and len(stripped) > 2 and stripped[:2].strip() and all(
            ch in "0123456789abcdef" for ch in stripped[:2]):
        return True
    return False


if __name__ == "__main__":
    sys.exit(main())
