"""issue 4629 -- characterise the v1.4.1907 / v1.5.2010 signature.

The linear scan scores these two releases `repro` on the strength of a timeout,
because is_internal_failure() returns True when timed_out. That is right in
general but it flattens two observably different things, so this measures the
difference instead of asserting it.

Three questions, each with its own control:

  1. Does the process terminate?          -> run to a long deadline, not 60s.
  2. Is it spinning or is it blocked?     -> sample CPU time while it runs. A
                                             modal dialog or a wait on a handle
                                             accrues no CPU; a spin accrues it
                                             at ~1 core.
  3. Is the binary itself usable?         -> compile a trivial shader first. If
                                             that hangs too the release is
                                             simply broken here and the repro
                                             result means nothing.

No claim in the write-up should rest on a number that is not in this file.
"""

import ctypes
import ctypes.wintypes as wt
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "scripts"))
import triage  # noqa: E402


class FILETIME(ctypes.Structure):
    _fields_ = [("lo", wt.DWORD), ("hi", wt.DWORD)]

    def seconds(self):
        return ((self.hi << 32) | self.lo) / 1e7


def cpu_seconds(handle):
    """User+kernel CPU consumed by a process, via GetProcessTimes. stdlib only."""
    creation, exit_, kernel, user = FILETIME(), FILETIME(), FILETIME(), FILETIME()
    ok = ctypes.windll.kernel32.GetProcessTimes(
        wt.HANDLE(handle),
        ctypes.byref(creation),
        ctypes.byref(exit_),
        ctypes.byref(kernel),
        ctypes.byref(user),
    )
    if not ok:
        return None
    return kernel.seconds() + user.seconds()

DEADLINE = 240.0
SAMPLE_EVERY = 20.0

TRIVIAL = "float4 PSMain() : SV_Target { return 1; }\n"
TRIVIAL_PATH = os.path.join(HERE, "hang-control-trivial.hlsl")

CASES = [
    ("v1.4.1907", "repro.hlsl", "the reported shader"),
    ("v1.4.1907", "@trivial", "control: does this release compile at all?"),
    ("v1.5.2010", "repro.hlsl", "the reported shader"),
    ("v1.5.2010", "@trivial", "control: does this release compile at all?"),
]


def release_exe(tag):
    row = triage.con().execute(
        "SELECT cached_path FROM releases WHERE tag = ?", (tag,)
    ).fetchone()
    if not row or not row[0]:
        raise SystemExit("no cached release for " + tag)
    # cached_path is the full path to dxc.exe, not the directory holding it,
    # and its shape differs between releases (v1.4.1907 has no bin\x64\).
    return row[0]


def run_sampled(exe, args, cwd):
    """Run to DEADLINE, sampling CPU. Returns (verdict, wall, cpu, samples, out)."""
    # Launched directly, not through cmd.exe, so proc.pid IS dxc and
    # GetProcessTimes measures the compiler rather than a shell wrapper.
    proc = subprocess.Popen(
        [exe] + args,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    handle = int(proc._handle)
    samples = []
    started = time.time()
    last_sample = 0.0
    cpu = 0.0
    while True:
        rc = proc.poll()
        wall = time.time() - started
        c = cpu_seconds(handle)
        if c is not None:
            cpu = c
        if rc is not None:
            out = proc.stdout.read().decode("utf-8", "replace")
            samples.append((wall, cpu))
            return ("exit 0x%08X" % (rc & 0xFFFFFFFF), wall, cpu, samples, out)
        if wall - last_sample >= SAMPLE_EVERY:
            samples.append((wall, cpu))
            last_sample = wall
        if wall >= DEADLINE:
            proc.kill()
            proc.wait()
            out = proc.stdout.read().decode("utf-8", "replace")
            samples.append((wall, cpu))
            return ("DID NOT TERMINATE", wall, cpu, samples, out)
        time.sleep(0.25)


def main():
    with open(TRIVIAL_PATH, "w", newline="\n") as f:
        f.write(TRIVIAL)

    lines = [
        "issue 4629 -- the two oldest releases: hang, or crash?",
        "generated by measure-oldest-hang.py",
        "",
        "deadline %.0fs, CPU sampled every %.0fs, command -T ps_6_0 -E PSMain"
        % (DEADLINE, SAMPLE_EVERY),
        "",
        "%-12s %-34s %-18s %8s %8s"
        % ("compiler", "case", "result", "wall", "cpu"),
        "-" * 86,
    ]
    detail = []
    for tag, shader, why in CASES:
        exe = release_exe(tag)
        src = "hang-control-trivial.hlsl" if shader == "@trivial" else shader
        verdict, wall, cpu, samples, out = run_sampled(
            exe, ["-T", "ps_6_0", "-E", "PSMain", src], HERE
        )
        lines.append(
            "%-12s %-34s %-18s %8.1f %8.1f" % (tag, why, verdict, wall, cpu)
        )
        detail.append("--- %s / %s -> %s" % (tag, src, verdict))
        detail.append("$ %s -T ps_6_0 -E PSMain %s" % (triage.redact_paths(exe), src))
        detail.append(
            "    CPU samples (wall s -> cpu s): "
            + ", ".join("%.0f->%.0f" % (w, c) for w, c in samples)
        )
        if len(samples) >= 2:
            dw = samples[-1][0] - samples[0][0]
            dc = samples[-1][1] - samples[0][1]
            if dw > 1.0:
                detail.append(
                    "    mean CPU utilisation over the run: %.2f core" % (dc / dw)
                )
        body = out.strip()
        detail.append("    output: " + (body.splitlines()[0] if body else "(none)"))
        detail.append("")

    lines += ["", "=" * 86, "detail", "=" * 86, ""] + detail
    lines += [
        "=" * 86,
        "reading",
        "=" * 86,
        "",
        "A process that is blocked -- on a message pump, a crash dialog, a file",
        "handle -- accrues no CPU while it waits. These accrue it continuously at",
        "close to one core for as long as they are allowed to run, and produce no",
        "output. That is a spin inside the compiler, not a crash and not a prompt",
        "waiting for someone to click it.",
        "",
        "The trivial control matters: it shows the release is not simply unusable",
        "in this harness. Same binary, same working directory, same command shape.",
        "",
        "So these two releases do not exhibit the signature the issue reports.",
        "They fail earlier and differently. match-crash.json exists to keep that",
        "distinction visible in the release scan, where the primary predicate",
        "scores both as reproductions via timed_out.",
        "",
        "What this does NOT establish: that the spin is unbounded. It was not",
        "allowed to run past %.0fs. The honest statement is 'did not terminate"
        % DEADLINE,
        "within %.0fs while burning CPU throughout', not 'infinite loop'." % DEADLINE,
    ]

    text = triage.redact_paths("\n".join(lines) + "\n")
    dst = os.path.join(HERE, "manual-case-oldest-hang.txt")
    with open(dst, "w", newline="\n") as f:
        f.write(text)
    print("manual-case-oldest-hang.txt written")


if __name__ == "__main__":
    main()
