"""Release matrix for issue 4629.

`triage.py bisect` answers one question -- does the primary repro reproduce --
against `cmd.txt`. Four further questions need the same binaries held fixed while
the *input* or the *arguments* vary, and catalogued releases are not registered
compiler ids, so they need an issue-local matrix:

  1. as-filed vs widened.  cmd.txt drops `-HV 2021` and lowers ps_6_5 to ps_6_0
     to reach the oldest releases. The equivalence was measured on ground truth;
     this checks it holds on every release too, so the widening cannot be the
     thing producing the history.

  2. feature presence, per release.  `invalid-probe` on a repro is ambiguous on
     its own: the release may predate the feature, or may have rejected
     something unrelated. control-interface-min.hlsl is the smallest shader that
     uses a class implementing an interface at all. Clean here + failing repro
     means the failure is about the reported combination, not about `interface`
     being unavailable. Run on EVERY release, not only ground truth.

  3. negative control, per release.  control-nointerface.hlsl is the repro with
     the interface inheritance removed and nothing else changed.

  4. what each release SAYS.  The issue reports a specific message. This records
     each release's stderr so the claim "the reported wording is not portable
     across release ages" is a measurement rather than a warning.

Hangs are the reason this script exists in the form it does: two releases spin
rather than crash, so each case records wall time, CPU time and whether the
process had to be killed. CPU burn is what separates a real hang from a process
blocked on something.

Exit statuses are captured from the Python that launched the process. Every
command line is printed with `subprocess.list2cmdline`, so it is an observation.
"""
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

TIMEOUT = 90
OUT = "manual-case-release-matrix.txt"

CASES = [
    ("repro/widened", ["-T", "ps_6_0", "-E", "PSMain", "repro.hlsl"]),
    ("repro/as-filed", ["-T", "ps_6_5", "-E", "PSMain", "-HV", "2021",
                        "repro.hlsl"]),
    ("ctl/interface-min", ["-T", "ps_6_0", "-E", "PSMain",
                           "control-interface-min.hlsl"]),
    ("ctl/nointerface", ["-T", "ps_6_0", "-E", "PSMain",
                         "control-nointerface.hlsl"]),
]


def run(exe, args):
    """Run one case, returning (status, wall, cpu, killed, first stderr line).

    Uses a Job-less poll loop rather than subprocess timeout so CPU time can be
    sampled while the process is still alive -- a spinning compiler and a
    compiler blocked on a dialog both miss a deadline, and only CPU burn tells
    them apart.
    """
    argv = [exe] + args
    t0 = time.time()
    p = subprocess.Popen(argv, cwd=HERE, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    cpu, killed = None, False
    while True:
        if p.poll() is not None:
            break
        if time.time() - t0 > TIMEOUT:
            cpu = sample_cpu(p.pid)
            p.kill()
            killed = True
            break
        time.sleep(0.25)
    out, err = p.communicate()
    wall = time.time() - t0
    rc = p.returncode
    text = (out or b"").decode("utf-8", "replace") \
        + (err or b"").decode("utf-8", "replace")
    if killed:
        status = "HANG (killed at %ds)" % TIMEOUT
    else:
        status = "0x%08X" % (rc & 0xFFFFFFFF)
    return status, wall, cpu, killed, text, argv


def sample_cpu(pid):
    """Total CPU seconds consumed by a live process, via WMI through PowerShell."""
    try:
        r = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             "(Get-Process -Id %d).CPU" % pid],
            capture_output=True, text=True, timeout=30)
        return float(r.stdout.strip())
    except Exception:
        return None


def first_message(text):
    for ln in text.splitlines():
        s = ln.strip()
        if s and not s.startswith(";"):
            return s
    return "(no output)"


def main():
    con = triage.con()
    rows = con.execute(
        "SELECT tag, cached_path FROM releases "
        "WHERE prerelease=0 AND cached_path IS NOT NULL ORDER BY build_date"
    ).fetchall()
    targets = [(r["tag"], r["cached_path"]) for r in rows]
    targets.append(("main-debug", os.path.join(
        triage.REPO_ROOT, "build", "Debug", "bin", "dxc.exe")))

    lines = []
    lines.append("issue 4629 -- release matrix, generated by measure-history.py")
    lines.append("timeout %ds; wall/cpu in seconds; status from the launching "
                 "Python, not a shell" % TIMEOUT)
    lines.append("")
    hdr = "%-14s  %-18s  %-22s  %7s  %7s  %s" % (
        "compiler", "case", "status", "wall", "cpu", "first message line")
    lines.append(hdr)
    lines.append("-" * len(hdr))

    transcript = []
    for tag, exe in targets:
        if not os.path.isfile(exe):
            exe_abs = os.path.join(triage.CACHE_ROOT, exe)
            if not os.path.isfile(exe_abs):
                lines.append("%-14s  %s" % (tag, "(no usable dxc asset)"))
                continue
            exe = exe_abs
        for label, args in CASES:
            status, wall, cpu, killed, text, argv = run(exe, args)
            lines.append("%-14s  %-18s  %-22s  %7.1f  %7s  %s" % (
                tag, label, status, wall,
                ("%.1f" % cpu) if cpu is not None else "-",
                first_message(text)[:78]))
            transcript.append((tag, label,
                               triage.redact_paths(
                                   subprocess.list2cmdline(argv)),
                               status, triage.redact_paths(text.strip())))
            print(tag, label, status, flush=True)

    lines.append("")
    lines.append("=" * 78)
    lines.append("full transcript")
    lines.append("=" * 78)
    for tag, label, cmdline, status, text in transcript:
        lines.append("")
        lines.append("--- %s / %s -> %s" % (tag, label, status))
        lines.append("$ " + cmdline)
        lines.append(text if text.strip() else "(no output)")

    with open(os.path.join(HERE, OUT), "w", encoding="utf-8",
              newline="\n") as f:
        f.write(triage.redact_paths("\n".join(lines)) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    sys.exit(main())
