"""Control for the Clang pane on issue 4629's Compiler Explorer link.

The published link carries an `hlsl_clang_trunk` pane that reports
`unknown type name 'interface'`. A Clang error is not evidence on its own:
Clang's HLSL support is incomplete, so it fails on plenty of inputs that have
nothing to do with the issue, and a pane full of errors would look identical.

So this asks the narrower question with the SAME compiler and the SAME arguments
against two inputs that must NOT fail:

  trivial        the smallest valid pixel shader there is
  nointerface    the issue's own repro with the interface inheritance removed,
                 which is the interesting control -- it keeps the class, the
                 inheritance, the fields and the method, and drops only the one
                 construct under test

If those compile and the repro does not, the difference is about `interface`.
If they fail too, the pane says nothing and must not be cited.

`-fsyntax-only` is used because the symptom being checked is a front-end
question ("does this front end implement `interface`?"). Without it, Clang's
DXIL backend cannot lower a shader writing SV_Target and the pane fills with
noise about the stage instead.

Uses triage.ce_compile so the request and the scoring are identical to the ones
the published link was verified with, rather than a second hand-rolled client.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts")))
import triage  # noqa: E402

COMPILER = "hlsl_clang_trunk"
ARGS = "-T ps_6_0 -E PSMain -fsyntax-only"
OUT = "manual-case-clang-control.txt"

TRIVIAL = "float4 PSMain() : SV_TARGET { return 1; }\n"

# The repro's structure with the `interface` keyword removed ENTIRELY -- class,
# inheritance, both fields and the method all survive. This control exists
# because the first attempt used control-nointerface.hlsl, which drops the
# interface from the *inheritance list* but still DECLARES it. That is a
# one-variable control for DXC, whose crash needs the inheritance; it is a
# zero-variable control for Clang, whose front end rejects the declaration
# itself. A control is only "one change away" with respect to the question being
# asked, and the same file can be a valid control for one compiler and a useless
# one for another.
NO_KEYWORD = """struct PSInput
{
};

class SurfaceData_BasePBR
{
    float3 albedo;
};

class SurfaceData_NewPBR : SurfaceData_BasePBR
{
    float3 emissiveLighting;

    void ApplySpecularAA()
    {
    }
};

float4 PSMain( PSInput input ) : SV_TARGET
{
    SurfaceData_NewPBR obj ;
    obj . albedo . x = 1 ;
    return float4 ( obj . albedo , 1 ) ;
}
"""

CASES = [
    ("repro (subject)", "repro.hlsl", "expect: fails"),
    ("control: interface-min", "control-interface-min.hlsl", "expect: fails "
     "-- second sighting of the keyword, in a shader sharing nothing else "
     "with the repro"),
    ("control: nointerface", "control-nointerface.hlsl", "expect: fails -- "
     "the DXC control, which still DECLARES the interface. Kept to show why it "
     "cannot serve as the Clang control"),
    ("control: no-keyword", None, "expect: compiles -- the repro's classes, "
     "inheritance, fields and method with the keyword removed entirely"),
    ("control: trivial", "@trivial", "expect: compiles -- proves the pane runs"),
]


def main():
    lines = [
        "issue 4629 -- Compiler Explorer Clang pane, with controls.",
        "Generated by verify-clang-control.py; no local compiler involved.",
        "",
        "compiler: %s" % COMPILER,
        "args:     %s" % ARGS,
        "",
    ]
    results = {}
    for label, filename, note in CASES:
        if filename is None:
            src = NO_KEYWORD
        elif filename == "@trivial":
            src = TRIVIAL
        else:
            with open(os.path.join(HERE, filename), encoding="utf-8") as f:
                src = f.read()
        rc, text, crashed = triage.ce_compile(src, COMPILER, ARGS)
        text = "\n".join(ln for ln in text.splitlines()
                         if "unused during compilation" not in ln)
        ok = (rc == 0)
        results[label] = ok
        lines.append("=" * 74)
        lines.append("%s  [%s]" % (
            label, {None: "<inline: repro without the keyword>",
                    "@trivial": "<inline trivial shader>"}.get(
                        filename, filename)))
        lines.append(note)
        lines.append("exit: %s   -> %s" % (rc, "compiled" if ok else "failed"))
        lines.append("")
        lines.append(text.strip() or "(no diagnostics)")
        lines.append("")

    lines.append("=" * 74)
    lines.append("conclusion")
    lines.append("=" * 74)
    concl = (
        "Every shader here containing the `interface` keyword fails at parse "
        "time; both that do not, compile. The pane is measuring the keyword."
        if (not results["repro (subject)"]
            and not results["control: interface-min"]
            and not results["control: nointerface"]
            and results["control: no-keyword"]
            and results["control: trivial"])
        else "MIXED -- read the cases above; the pane must not be cited as "
             "evidence about `interface` on this result.")
    lines.append(concl)
    lines.append("")
    lines.append("Note what this does and does not say. Clang rejects the")
    lines.append("keyword at parse time, so it is not reaching -- and therefore")
    lines.append("not answering -- the optimizer defect this issue reports. It")
    lines.append("is a datapoint about the successor front end's coverage of the")
    lines.append("language construct, nothing more.")

    with open(os.path.join(HERE, OUT), "w", encoding="utf-8",
              newline="\n") as f:
        f.write(triage.redact_paths("\n".join(lines)) + "\n")
    print(OUT, "->", concl)


if __name__ == "__main__":
    sys.exit(main())
