"""Capture the failing stack for issue #4036 and trim it for commit.

`dxc` reports `Internal Compiler error: llvm::cast<X>() argument of
incompatible type!` and exits 0x80AA001D, which says the compile died but not
where. DXC's `llvm_cast_assert` throws `hlsl::Exception(DXC_E_LLVM_CAST_ERROR)`
(include/llvm/Support/ErrorHandling.h, lib/Support/ErrorHandling.cpp) rather
than trapping, so the failure arrives as a C++ exception (0xE06D7363) and the
debugger has to break on the exception itself.

Two sections are captured:

  break   -- the stack at the throw. This is the evidence.
  continue-- the same run with the throw continued past as handled. That is a
             debugger artefact ("Continuing a non-continuable exception"), so
             it is indicative only, and is kept because it names the HL
             operation that was never lowered. It is NOT the basis of any
             claim about release builds; those were measured directly, in
             manual-case-release-matrix.txt.

The command lines are printed by `subprocess.list2cmdline`, i.e. exactly what
ran, rather than transcribed.

Run it from anywhere:  python capture-stack.py
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SKILL_DIR)))
DXC = os.path.join(REPO_ROOT, "build", "Debug", "bin", "dxc.exe")
CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
OUT = os.path.join(HERE, "manual-case-cast-stack.txt")
ARGS = ["-T", "ps_6_6", "-E", "PSMain", "repro.hlsl"]

# cdb is launched with an argv list straight from Python, with NO shell in the
# way. The documented rule -- "run cdb through cmd.exe, not PowerShell" -- is
# about PowerShell re-quoting the arguments; routing the same argv through
# `cmd /c` from Python reintroduces a quoting bug of cmd's own, because a
# command line that both starts with a quote and contains further quotes is
# mangled ("'\"...cdb.exe\"' is not recognized as an internal or external
# command"). Passing argv directly is what actually works here.
SECTIONS = [
    ("break at the throw",
     'sxe -c "kn 20; q" e06d7363; g; q'),
    ("continued past the throw as handled (debugger artefact -- indicative only)",
     'sxe -c "gh" e06d7363; g; q'),
]

# Frames that are pure process/CRT startup or the debugger's own noise.
DROP = re.compile(r"BaseThreadInitThunk|RtlUserThreadStart|__scrt_|invoke_main"
                  r"|wmainCRTStartup")


def display(path):
    p = os.path.abspath(path)
    try:
        rel = os.path.relpath(p, REPO_ROOT)
    except ValueError:
        return p.replace(os.sep, "/")
    return ("<repo>/" + rel.replace(os.sep, "/")) if not rel.startswith("..") \
        else p.replace(os.sep, "/")


def run(script):
    argv = [CDB, "-c", script, DXC] + ARGS
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
    return subprocess.list2cmdline(argv), p.stdout + p.stderr


def trim(text):
    """Keep the exception line, the frames, and dxc's own output."""
    keep, in_stack = [], False
    for ln in text.splitlines():
        s = ln.rstrip()
        if "Child-SP" in s:
            in_stack = True
            keep.append(s)
            continue
        if in_stack:
            if re.match(r"^[0-9a-f]{2} ", s):
                if not DROP.search(s):
                    keep.append(s)
                continue
            # cdb interleaves symbol/checksum warnings between frames; they are
            # not the end of the stack. Treating them as one truncated the
            # capture to a single frame.
            if s.startswith("***") or not s.strip():
                continue
            in_stack = False
        if re.search(r"C\+\+ EH exception|Internal Compiler error|"
                     r"non-continuable|^error:|^Function: |Validation failed|"
                     r"^repro\.hlsl", s):
            keep.append(s)
    return keep


def main():
    for path, what in ((CDB, "cdb.exe"), (DXC, "the ground-truth dxc.exe")):
        if not os.path.isfile(path):
            sys.exit(f"cannot find {what}: {path}")

    lines = ["# issue 4036 -- where the internal compiler error comes from",
             "#",
             "# Generated by capture-stack.py, which echoes every command it runs.",
             f"# dxc: {display(DXC)}",
             "# version: " + subprocess.run(
                 [DXC, "--version"], capture_output=True,
                 text=True).stdout.strip(),
             "# Stack frames are trimmed to the compiler's own; CRT startup",
             "# frames are dropped. Nothing else is edited.",
             ""]
    for title, script in SECTIONS:
        cmd, text = run(script)
        lines.append(f"== {title}")
        lines.append("   $ " + cmd.replace(DXC, display(DXC)))
        lines.append("")
        kept = trim(text)
        if not kept or not any(re.match(r"^[0-9a-f]{2} ", k) for k in kept) \
                and "kn " in script:
            lines.append("   PARSE-WARNING: expected stack frames and found "
                         "none; this section may not be measuring anything.")
        lines.extend("   " + k for k in kept)
        lines.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
