"""Per-release matrix for issue #4036.

`triage.py bisect` scores the repro on every release, but it cannot run the
feature-presence control beside it: catalogued releases are not registered
compiler ids, and `run --shader` only ever retargets the registered ground
truth. Without that control an `invalid-probe` is ambiguous -- "this release
predates Shader Model 6.6" and "this release rejected something else in my
repro" look identical -- and only the first justifies trimming a release out of
the history.

It also answers the question `bisect` cannot: whether `-HV 2021` (taken from the
issue's original title, `[hlsl 2021] Odd compiliation error`) is load-bearing.
It is not, and it cost two releases of history: v1.6.2104 and v1.6.2106 reject
the flag with `Unknown HLSL version: 2021`, which says nothing about Shader
Model 6.6, so they were demoted to invalid probes while in fact reproducing the
filed diagnostic. Every case is therefore run in both spellings, and the
IDENTITY line reports whether the two agree byte-for-byte -- an equivalence
control for the flag removal rather than an assertion that it is inert.

Each row is one real process launch. The command printed is produced by
`subprocess.list2cmdline(argv)` -- the exact argv that ran -- rather than
transcribed, so a reader can re-derive the file instead of trusting it.

Run it from anywhere:  python release-matrix.py
"""

import os
import sqlite3
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SKILL_DIR)))
CACHE_ROOT = os.path.abspath(os.environ.get(
    "DXC_TRIAGE_CACHE", os.path.join(SKILL_DIR, ".cache")))
DB = os.path.join(CACHE_ROOT, "triage.db")
GROUND_TRUTH = os.path.join(REPO_ROOT, "build", "Debug", "bin", "dxc.exe")
OUT = os.path.join(HERE, "manual-case-release-matrix.txt")

BASE = ["-T", "ps_6_6", "-E", "PSMain"]
HV = ["-HV", "2021"]

# (label, source).  Every case uses the repro's profile and entry point, so
# within a release the only thing that varies is the source or the one flag.
CASES = [
    ("repro         ", "repro.hlsl"),
    ("control-heap  ", "control-heap.hlsl"),
    ("control-local ", "control-local.hlsl"),
]


def display(path):
    p = os.path.abspath(path)
    for base, token in ((CACHE_ROOT, "<cache>"), (REPO_ROOT, "<repo>")):
        try:
            rel = os.path.relpath(p, base)
        except ValueError:
            continue
        if not rel.startswith(".."):
            return token + "/" + rel.replace(os.sep, "/")
    return p.replace(os.sep, "/")


def run(exe, tail):
    argv = [exe] + tail
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True)
    return (subprocess.list2cmdline(argv), p.returncode & 0xFFFFFFFF,
            p.stdout + p.stderr)


def first_meaningful(text):
    for ln in text.splitlines():
        if ln.strip():
            return ln.strip()
    return "(no output)"


def main():
    con = sqlite3.connect(DB)
    rows = con.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE prerelease = 0 AND cached_path IS NOT NULL "
        "ORDER BY build_date").fetchall()
    con.close()

    builds = list(rows)
    builds.append(("main-debug", "13730886e", GROUND_TRUTH))

    lines = []
    w = lines.append
    w("# issue 4036 -- per-release matrix: repro, feature-presence control, workaround")
    w("#")
    w("# Generated by release-matrix.py, which echoes every command it runs.")
    w("# Stable releases only; prereleases are outside the search by policy and")
    w("# this issue names none.  Exit codes are the raw 32-bit process status.")
    w("#   0x00000000             -- compiled clean")
    w("#   0x00000001             -- driver rejected the command line")
    w("#   0x80004005 E_FAIL      -- ordinary diagnosed error (NOT an internal failure)")
    w("#   0x80AA001D DXC_E_LLVM_CAST_ERROR -- internal failure")
    w("#")
    w("# Each case is run twice, with and without the `-HV 2021` from the issue's")
    w("# original title.  IDENTITY says whether the two runs agree on exit status")
    w("# and on every byte of output; that is the equivalence control for dropping")
    w("# the flag from cmd.txt.")
    w("")

    identity = {"same": 0, "differ": 0}
    for tag, date, exe in builds:
        if not os.path.isfile(exe):
            w(f"== {tag} ({date}) -- MISSING: {display(exe)}")
            w("")
            continue
        ver = subprocess.run([exe, "--version"], capture_output=True, text=True)
        w(f"== {tag} ({date})")
        w(f"   exe:     {display(exe)}")
        w(f"   version: {(ver.stdout + ver.stderr).strip().splitlines()[0]}")
        for label, src in CASES:
            cmd_a, rc_a, out_a = run(exe, BASE + [src])
            cmd_b, rc_b, out_b = run(exe, BASE + HV + [src])
            same = (rc_a == rc_b and out_a == out_b)
            identity["same" if same else "differ"] += 1
            w(f"   {label} -HV off  exit=0x{rc_a:08X}  {first_meaningful(out_a)}")
            w(f"       $ {cmd_a.replace(exe, display(exe))}")
            w(f"   {label} -HV 2021 exit=0x{rc_b:08X}  {first_meaningful(out_b)}")
            w(f"       $ {cmd_b.replace(exe, display(exe))}")
            w(f"   {label} IDENTITY {'same' if same else 'DIFFER'}"
              f" (exit and output byte-for-byte)")
        w("")

    # Self-test: a matrix that silently compared nothing would print an
    # unbroken column of "same" too, so state the counts and require both
    # outcomes to have been observed somewhere -- v1.6.2104 and v1.6.2106
    # differ, every SM 6.6-capable later release agrees.
    w(f"# IDENTITY totals: {identity['same']} same, {identity['differ']} differ"
      f" (of {identity['same'] + identity['differ']} comparisons)")
    if identity["same"] and identity["differ"]:
        w("# SELF-TEST pass: the comparison distinguishes agreeing runs from "
          "differing ones.")
    else:
        w("# SELF-TEST FAIL: every comparison came out the same way, so this "
          "column may not be measuring anything.")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(builds)} builds x {len(CASES)} cases x 2 spellings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
