"""Corroborating source evidence for issue 4036.

Answers two questions with git alone, so a reviewer can re-run it without
building anything:

  1. Does the in-tree test suite already cover the construct in the repro
     (a cast applied directly to a ResourceDescriptorHeap subscript)?
  2. The measured regression window is v1.6.2112 -> v1.7.2207.  Did the
     lowering that now throws (LowerGetResourceFromHeap) change inside that
     window, or did something upstream of it start letting the construct
     through?

Every command is echoed before it runs, and its output is reproduced
unedited.  Run from this directory:

    python source-window.py > manual-case-source-window.txt
"""

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[6]
OLD_TAG = "v1.6.2112"
NEW_TAG = "v1.7.2207"
PASS_FILE = "tools/clang/lib/CodeGen/CGHLSLMSFinishCodeGen.cpp"
FUNC = "LowerGetResourceFromHeap"


def run(args, echo=None, head=None):
    """Run a git command, echo it, and reproduce its output unedited.

    head=N prints only the first N lines and says how many were withheld;
    the command is echoed in full so anyone can see the rest.
    """
    print("   $ " + (echo or " ".join(args)))
    print()
    proc = subprocess.run(args, cwd=REPO, capture_output=True, text=True)
    body = (proc.stdout or "") + (proc.stderr or "")
    if not body.strip():
        body = "(no output)\n"
    lines = body.rstrip("\n").split("\n")
    shown = lines if head is None else lines[:head]
    for line in shown:
        print("   " + line)
    if head is not None and len(lines) > head:
        print("   ... %d more lines, not reproduced here" % (len(lines) - head))
    print()
    return proc.stdout


def section(title):
    print("== " + title)


def show(path, tag):
    """Return the source of PASS_FILE at a tag as a list of lines."""
    out = subprocess.run(
        ["git", "show", f"{tag}:{path}"], cwd=REPO, capture_output=True, text=True
    )
    if out.returncode != 0:
        return None
    return out.stdout.split("\n")


def main():
    print("# issue 4036 -- source corroboration: test coverage and the")
    print("# regression window " + OLD_TAG + " -> " + NEW_TAG)
    print("#")
    print("# Generated by source-window.py, which echoes every command it runs.")
    print("# Every command runs with the repository root as its working")
    print("# directory; all pathspecs are repository-relative.")
    print("# Nothing here runs the compiler; this is git evidence only.")
    print("# It supports, and does not replace, the measured per-release")
    print("# results in manual-case-release-matrix.txt.")
    print()

    section("1. is the construct in the repro covered by an in-tree test?")
    print("   The repro calls a method on a cast applied straight to a heap")
    print("   subscript:")
    print("       ((StructuredBuffer<float>)ResourceDescriptorHeap[i]).Load(0)")
    print("   Search every test for a cast applied straight to a heap")
    print("   subscript, i.e. the ')' of a cast immediately followed by the")
    print("   heap name.")
    print()
    run(
        [
            "git",
            "grep",
            "-n",
            "-E",
            r"\)(ResourceDescriptorHeap|SamplerDescriptorHeap)\[",
            "HEAD",
            "--",
            "tools/clang/test",
        ]
    )
    print("   The construct does appear -- but look at what those tests run.")
    print("   Print the RUN line of each:")
    print()
    for path in (
        "tools/clang/test/HLSLFileCheck/hlsl/template/FunctionOverloads.hlsl",
        "tools/clang/test/HLSLFileCheck/hlsl/template/InstantiateObjectMethods.hlsl",
        "tools/clang/test/HLSLFileCheckLit/hlsl/auto/auto-no-descriptor-heap.hlsl",
    ):
        run(["git", "grep", "-h", "-n", "RUN:", "HEAD", "--", path])
    print("   The two template tests are -ast-dump: they stop after parsing.")
    print("   The auto test is -verify and its other lines expect errors, so")
    print("   compilation stops after Sema.  None of the three reaches code")
    print("   generation, which is where this issue fails.  The construct is")
    print("   present in the suite but the failing path is not exercised.")
    print()
    print("   For contrast, count the tests using the supported spelling")
    print("   (assign the subscript to a local first):")
    print()
    out = run(
        [
            "git",
            "grep",
            "-l",
            "-E",
            r"(ResourceDescriptorHeap|SamplerDescriptorHeap)\[",
            "HEAD",
            "--",
            "tools/clang/test",
        ],
        head=6,
    )
    print("   files matching: %d" % len([x for x in out.split("\n") if x.strip()]))
    print()
    print("   Which shape actually fails is measured, not inferred -- see")
    print("   variant-control-cast-local-main-debug--match-fails.txt (cast")
    print("   assigned to a local: compiles) and")
    print("   variant-control-cast-arg-main-debug--match-fails.txt (cast")
    print("   passed as an argument: compiles).  Only the member call on the")
    print("   cast expression itself fails.")
    print()

    section("2. when was the failing lowering introduced?")
    run(
        [
            "git",
            "log",
            "--all",
            "-S",
            FUNC,
            "--format=%h %ad %s",
            "--date=short",
            "--",
            PASS_FILE,
        ]
    )

    section("3. how big is the regression window?")
    out = run(["git", "log", "--oneline", f"{OLD_TAG}..{NEW_TAG}"], head=5)
    n = len([x for x in out.split("\n") if x.strip()])
    print("   commits in %s..%s: %d" % (OLD_TAG, NEW_TAG, n))
    print()
    print("   ...of which touch the file holding the failing lowering:")
    print()
    run(
        [
            "git",
            "log",
            "--format=%h %ad %s",
            "--date=short",
            f"{OLD_TAG}..{NEW_TAG}",
            "--",
            PASS_FILE,
        ]
    )

    section("4. did the failing lowering itself change in the window?")
    print("   Compare the first 80 lines of " + FUNC + " at each tag.")
    print("   (The function moved: the line numbers differ, the text may not.)")
    print()
    old = show(PASS_FILE, OLD_TAG)
    new = show(PASS_FILE, NEW_TAG)
    if old is None or new is None:
        print("   SELF-TEST fail: could not read " + PASS_FILE + " at both tags")
        return 1

    def first_hit(lines):
        for i, line in enumerate(lines):
            if FUNC in line:
                return i
        return None

    oi, ni = first_hit(old), first_hit(new)
    if oi is None or ni is None:
        print("   SELF-TEST fail: %s not found at both tags" % FUNC)
        return 1
    print("   %s: %s first appears at line %d" % (OLD_TAG, PASS_FILE, oi + 1))
    print("   %s: %s first appears at line %d" % (NEW_TAG, PASS_FILE, ni + 1))
    print()
    old_body = old[oi : oi + 80]
    new_body = new[ni : ni + 80]
    diff = [
        (a, b) for a, b in zip(old_body, new_body) if a != b
    ]
    if diff:
        print("   DIFFERS -- %d of 80 lines are not equal:" % len(diff))
        for a, b in diff[:20]:
            print("     %s: %s" % (OLD_TAG, a))
            print("     %s: %s" % (NEW_TAG, b))
    else:
        print("   IDENTICAL -- all 80 lines of %s are byte-equal at both" % FUNC)
        print("   tags.  The lowering that now throws did not change across")
        print("   the window, so whatever started producing an IR shape it")
        print("   cannot handle lies upstream of code generation.")
    print()

    print("   SELF-TEST: the comparison above must be able to report a")
    print("   difference, or 'IDENTICAL' means nothing.  Compare the same")
    print("   window against a deliberately different function to prove the")
    print("   comparison is not vacuous.")
    print()
    other = first_hit_named(new, "FinishIntrinsics")
    if other is None:
        print("   SELF-TEST inconclusive: control function not found")
    else:
        ctl = new[other : other + 80]
        ctl_diff = [(a, b) for a, b in zip(old_body, ctl) if a != b]
        print(
            "   control (%s at %s vs FinishIntrinsics at %s): %d of 80 differ"
            % (FUNC, OLD_TAG, NEW_TAG, len(ctl_diff))
        )
        print(
            "   SELF-TEST %s"
            % ("pass" if ctl_diff and not diff else "pass" if ctl_diff else "fail")
        )
    print()
    return 0


def first_hit_named(lines, name):
    for i, line in enumerate(lines):
        if name in line:
            return i
    return None


if __name__ == "__main__":
    sys.exit(main())
