#!/usr/bin/env python3
"""#4341 -- per-release matrix: is `-HV 2021` load-bearing, and can each release
express the feature at all?

Two questions that a single `bisect` run cannot answer, measured together on
every stable release plus the ground-truth build:

  A. `-HV 2021` inertness.  The issue title says "[HLSL 2021]" and the flag was
     put into cmd.txt on that basis.  An inherited `-HV 2021` has manufactured a
     false feature floor before, so the flag is measured rather than assumed:
     each release compiles the repro WITH the flag and WITHOUT it.  If the two
     agree everywhere, the flag is inert and cmd.txt should drop it to widen the
     history; if they differ, the flag is load-bearing and the releases that
     answer `Unknown HLSL version: 2021` are honest invalid probes.

  B. Feature presence.  `invalid-probe` on the repro alone is ambiguous: it can
     mean the release predates the feature, or that something unrelated in the
     repro was rejected.  variant-getter-read.hlsl is the smallest shader that
     uses a user-defined `operator[]` at all -- same struct, same profile, same
     flags, subscript READ instead of written.  invalid-probe on both means
     feature absence; a clean control beside a rejected repro would mean the
     rejection is about the repro, not the release.

  C. The overload-resolution claim.  llvm-beanz's comment on the issue says the
     limitation is "caused by broken behavior in DXC's overload resolution", so
     the C++ getter/setter idiom -- a const overload beside a non-const one --
     is compiled on every release too.

Writes manual-case-release-matrix.txt.  Every command is printed with
subprocess.list2cmdline(argv), i.e. exactly what was executed -- not a
transcription.  Machine paths are rewritten to <repo>.
"""

import re
import sqlite3
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[5]
SKILL = REPO / ".github" / "skills" / "dxc-issue-triage"
DB = SKILL / ".cache" / "triage.db"
GROUND_TRUTH = REPO / "build" / "Debug" / "bin" / "dxc.exe"

ARMS = [
    ("repro, WITH -HV 2021",
     ["-T", "ps_6_0", "-E", "main", "-HV", "2021", "repro.hlsl"]),
    ("repro, WITHOUT -HV 2021 (compiler default)",
     ["-T", "ps_6_0", "-E", "main", "repro.hlsl"]),
    ("feature-presence control (subscript READ), WITH -HV 2021",
     ["-T", "ps_6_0", "-E", "main", "-HV", "2021", "variant-getter-read.hlsl"]),
    ("const/non-const operator[] pair, WITH -HV 2021",
     ["-T", "ps_6_0", "-E", "main", "-HV", "2021", "variant-const-overload-pair.hlsl"]),
]

NOISE = re.compile(r"error|warning|Unknown|failed|not assignable", re.I)


def redact(text: str) -> str:
    """Rewrite this machine's layout to <repo>.

    The escaped form is replaced first: in JSON-ish text the separator is
    doubled, so a pattern written with single backslashes never sees it.
    """
    for root in (str(REPO), str(SKILL)):
        label = "<repo>" if root == str(REPO) else "<skill>"
        for variant in (root.replace("\\", "\\\\"), root, root.replace("\\", "/")):
            text = text.replace(variant, label)
    return re.sub(r"(<repo>|<skill>)[\\/]+", r"\1/", text)


def run(exe: Path, args):
    argv = [str(exe)] + args
    try:
        p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired:
        return None, ["TIMEOUT"]
    status = p.returncode & 0xFFFFFFFF
    body = (p.stdout or "") + (p.stderr or "")
    lines = [ln.rstrip() for ln in body.splitlines() if ln.strip()]
    diags = [ln for ln in lines if NOISE.search(ln)]
    if diags:
        shown = diags[:6]
    else:
        shown = [f"(compiled clean; {len(lines)} lines of output, no diagnostic)"]
    return status, shown


def compilers():
    out = [("main-debug", GROUND_TRUTH)]
    con = sqlite3.connect(str(DB))
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, cached_path FROM releases WHERE prerelease=0 ORDER BY published_at"
    ).fetchall()
    con.close()
    for r in rows:
        if r["cached_path"]:
            out.append((r["tag"], Path(r["cached_path"])))
        else:
            out.append((r["tag"], None))
    return out


def main():
    out = []
    out.append("#4341 -- per-release matrix: -HV 2021 inertness and feature presence")
    out.append("=" * 74)
    out.append("")
    out.append("Generated by")
    out.append("<repo>/.github/skills/dxc-issue-triage/data/issues/4341/measure-release-matrix.py")
    out.append("")
    out.append("repro.hlsl              declares float4 operator[](int) on a struct and")
    out.append("                        writes through it: `m[0] = 9.0;`")
    out.append("variant-getter-read.hlsl same struct, subscript READ instead of written")
    out.append("")

    summary = []
    for name, exe in compilers():
        out.append(f"### {name}")
        out.append("")
        if exe is None or not exe.exists():
            out.append("  no cached dxc asset for this tag -- not probed")
            out.append("")
            out.append("-" * 74)
            out.append("")
            summary.append((name, "-", "-", "-", "-"))
            continue
        vp = subprocess.run([str(exe), "--version"], capture_output=True, text=True)
        vtext = ((vp.stdout or "") + (vp.stderr or "")).strip().splitlines()
        out.append(f"$ {subprocess.list2cmdline(['<compiler>', '--version'])}")
        for ln in vtext:
            if ln.strip():
                out.append(f"  | {ln.rstrip()}")
        out.append("")
        codes = []
        for label, args in ARMS:
            out.append(f"-- {label} --")
            out.append(f"$ {subprocess.list2cmdline(['<compiler>'] + args)}")
            status, shown = run(exe, args)
            out.append(f"  exit: 0x{status:08X}" if status is not None else "  exit: TIMEOUT")
            for ln in shown:
                out.append(f"  | {ln}")
            out.append("")
            codes.append(classify(status, shown))
        out.append("-" * 74)
        out.append("")
        summary.append((name, *codes))

    out.append("SUMMARY")
    out.append("=" * 74)
    out.append(f"{'compiler':16} {'repro +HV2021':>16} {'repro -HV':>16} {'read +HV2021':>16} {'const-pair':>16}")
    for row in summary:
        out.append(f"{row[0]:16} {row[1]:>16} {row[2]:>16} {row[3]:>16} {row[4]:>16}")
    out.append("")
    out.append("rejected-assign = `error: expression is not assignable` on `m[0] = 9.0;`")
    out.append("no-hlsl-2021    = `dxc failed : Unknown HLSL version: 2021`")
    out.append("no-operator     = `'operator' is a reserved keyword in HLSL`")
    out.append("redeclared      = `error: class member cannot be redeclared` -- the trailing")
    out.append("                  `const` is not part of the signature, so the getter/setter")
    out.append("                  pair is a redeclaration rather than an overload")
    out.append("clean           = compiled with no diagnostic")
    out.append("")

    text = redact("\n".join(out) + "\n")
    (HERE / "manual-case-release-matrix.txt").write_text(text, encoding="utf-8")
    sys.stdout.write(text)


def classify(status, shown):
    if status is None:
        return "TIMEOUT"
    blob = "\n".join(shown)
    if "Unknown HLSL version: 2021" in blob:
        return "no-hlsl-2021"
    if "reserved keyword in HLSL" in blob:
        return "no-operator"
    if "class member cannot be redeclared" in blob:
        return "redeclared"
    if "expression is not assignable" in blob:
        return "rejected-assign"
    if status == 0 and "compiled clean" in blob:
        return "clean"
    return f"other(0x{status:08X})"


if __name__ == "__main__":
    main()
