"""Capture the stack at the internal failure reported in issue 4350.

Runs the repro under cdb, breaking on the MSVC C++ exception (0xE06D7363) that
`hlsl::Exception(DXC_E_LLVM_CAST_ERROR, ...)` is thrown as, and writes a trimmed
frame list to manual-case-cast-stack.txt.

The command actually executed is echoed with subprocess.list2cmdline, so the
committed capture is not a transcription. Machine paths are rewritten to <repo>
relative to the repository root so the artifact is machine-independent; the
substitution is anchored on the repository *name*, not on one contributor's layout.

  python capture-stack.py
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# data/issues/4350 -> issues -> data -> dxc-issue-triage -> skills -> .github -> <repo>
REPO = os.path.abspath(os.path.join(HERE, *([os.pardir] * 6)))
DXC = os.path.join(REPO, "build", "Debug", "bin", "dxc.exe")
CDB = r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe"
OUT = os.path.join(HERE, "manual-case-cast-stack.txt")


def redact(text):
    """Replace this machine's repository path with <repo>, in every spelling."""
    root = REPO.rstrip("\\/")
    variants = [root, root.replace("\\", "/"), root.replace("\\", "\\\\")]
    for v in sorted(variants, key=len, reverse=True):
        text = re.sub(re.escape(v), "<repo>", text, flags=re.IGNORECASE)
    return text.replace("\\", "/") if False else text


def main():
    if not os.path.exists(CDB):
        print("cdb.exe not found at %s" % CDB, file=sys.stderr)
        return 2
    if not os.path.exists(DXC):
        # Redaction rewrites this machine's repository root to <repo>, which would
        # make a wrong path look plausible in the committed capture. Fail loudly
        # instead: a capture produced by a debugger that never launched the target
        # is not evidence.
        print("dxc.exe not found at %s" % DXC, file=sys.stderr)
        return 2

    # Break on the C++ exception itself, print frames, then go-handled so the
    # driver's own handler still reports the error and the process exits normally.
    # cdb is launched through cmd.exe: the skill records that cdb's -c argument
    # does not survive other shells' re-quoting. The whole command is wrapped in
    # one extra pair of quotes, which is what `cmd /c` needs when the program
    # path itself is quoted; without it cmd reports "is not recognized".
    printed = ('"%s" -c "sxe -c \\"kn 25; gh\\" e06d7363; g; q" %s '
               '-T vs_6_0 repro.hlsl' % (CDB, DXC))
    comspec = os.environ.get("ComSpec", "cmd.exe")
    # Passed as a single string so Windows receives it verbatim: list2cmdline
    # would re-quote the embedded quotes and cdb would never see its -c script.
    cmdline = '%s /c "%s"' % (comspec, printed)

    proc = subprocess.run(cmdline, cwd=HERE, capture_output=True, text=True)
    raw = proc.stdout + proc.stderr

    # Trim: keep from the C++ EH exception line through the frame list, plus the
    # driver's own final message. A full cdb dump is noise.
    lines = raw.splitlines()
    keep, in_frames = [], False
    for ln in lines:
        if "C++ EH exception" in ln:
            in_frames = True
        if in_frames:
            keep.append(ln)
            if re.match(r"^\s*\d\d ", ln) and "dxcompiler!DxcCompiler" in ln:
                break
    tail = [ln for ln in lines if "incompatible type" in ln]

    body = [
        "# issue 4350: stack at the internal failure",
        "# generated by capture-stack.py; do not hand-edit",
        "# cdb exit: %d" % proc.returncode,
        "",
        "$ " + printed,
        "",
    ]
    body += keep if keep else ["(no C++ exception frames captured)"]
    if tail:
        body += ["", "--- driver output ---"] + tail

    text = redact("\n".join(body) + "\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    if not keep:
        with open(os.path.join(HERE, "capture-stack-raw.txt"), "w",
                  encoding="utf-8", newline="\n") as f:
            f.write(redact(raw))
    print("wrote %s (%d lines)" % (os.path.basename(OUT), text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
