"""#4350: what would a message-matching or exit-status-only predicate have concluded?

This issue's brief named one hazard above all others: on a crash-shaped issue, matching the
crash's *message text* instead of using the `internal_failure` predicate is the single biggest
source of wrong verdicts in this workflow. #4350 is a sharp instance in the opposite direction
from most: **every** probed release reproduces, so any predicate that is not build-agnostic
does not merely shift a boundary, it manufactures one out of nothing.

The same defect wears four faces across the twenty stable releases and is completely silent on
two of them:

  v1.4.1907, v1.5.2010    0xC0000005, stderr COMPLETELY EMPTY
  v1.6.2104               0xC0000005, 'Internal compiler error: access violation. ...'
  v1.6.2106, v1.6.2112    0x80AA001D, 'Internal Compiler error: llvm::cast<X>() ...'
  v1.7.2207 .. main       0x80004005 (E_FAIL), 'error: llvm::cast<X>() ...'

This script re-scores every captured probe under five predicates and prints the release history
each one would have reported. It reads the committed `out-*.txt` captures and imports
`triage.py`'s own `is_internal_failure`, so it re-derives rather than restates.

It also scores the four committed controls, because a predicate is only as good as what it
refuses to fire on: `control-syntax-error.hlsl` exits with the *same* status as the repro
(0x80004005) while being an ordinary diagnosed error.

Writes manual-case-predicate-counterfactual.txt.

Run from this directory:  python check-predicate-counterfactual.py
"""

import glob
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.abspath(os.path.join(HERE, "..", "..", "..", "scripts"))

_spec = importlib.util.spec_from_file_location(
    "triage", os.path.join(SCRIPTS, "triage.py"))
triage = importlib.util.module_from_spec(_spec)
sys.modules["triage"] = triage
_spec.loader.exec_module(triage)

REPORTER_LINE = "llvm::cast<X>() argument of incompatible type!"


def status_only(text, rc, timed_out):
    """`internal_failure` with the text markers removed -- exit status alone."""
    return triage.is_internal_failure("", rc, timed_out)


def nonzero_exit(text, rc, timed_out):
    return bool(rc)


PREDICATES = [
    ("internal_failure (as used)",
     lambda t, rc, to: triage.is_internal_failure(t, rc, to)),
    ("exit status only, no text markers", status_only),
    ("contains the reporter's quoted message",
     lambda t, rc, to: REPORTER_LINE in t),
    ("contains 'internal compiler error' (the issue title's phrase)",
     lambda t, rc, to: re.search(r"(?i)internal compiler error", t) is not None),
    ("nonzero exit", nonzero_exit),
]

CONTROLS = [
    ("control-static", "the object made `static`, so mutable: compiles, exit 0"),
    ("control-memberfn", "member function on a mutable local: compiles, exit 0"),
    ("control-constlocal", "const *local* object, same violation: compiles, exit 0"),
    ("control-syntaxerr", "ordinary syntax error: E_FAIL, SAME status as the repro"),
]


def order_key(tag):
    if tag == "main-debug":
        return (2, ())
    return (1, tuple(int(x) for x in re.findall(r"\d+", tag)))


def load(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    rc = None
    for line in text.splitlines():
        if line.startswith("# exit:"):
            rc = int(line.split(":", 1)[1].strip())
            break
    body = text.split("--- stdout ---", 1)
    return (body[1] if len(body) > 1 else text), rc


def history(results, tags):
    """Render the boundary a bisect over these results would have reported."""
    seq = [(t, results[t]) for t in tags if t != "main-debug"]
    if not seq:
        return "no releases"
    changes = []
    for i in range(1, len(seq)):
        if seq[i][1] != seq[i - 1][1]:
            changes.append("%s -> %s at %s"
                           % ("repro" if seq[i - 1][1] else "clean",
                              "repro" if seq[i][1] else "clean",
                              seq[i][0]))
    if not changes:
        return "always %s" % ("repro'd" if seq[0][1] else "clean")
    return "; ".join(changes)


def main():
    caps = {}
    for path in glob.glob(os.path.join(HERE, "out-*.txt")):
        tag = os.path.basename(path)[len("out-"):-len(".txt")]
        caps[tag] = load(path)
    if not caps:
        print("no out-*.txt captures found", file=sys.stderr)
        return 2
    tags = sorted(caps, key=order_key)

    scored = {name: {t: bool(fn(caps[t][0], caps[t][1], False)) for t in tags}
              for name, fn in PREDICATES}

    out = []
    out.append("# #4350 -- what a message-matching predicate would have concluded")
    out.append("# generated by check-predicate-counterfactual.py; do not hand-edit")
    out.append("#")
    out.append("# Re-scores the committed out-*.txt captures under five predicates.")
    out.append("# 'repro' = predicate fired. Only P1 is the predicate this triage used.")
    out.append("")

    width = max(len(t) for t in tags) + 2
    out.append("".ljust(width)
               + "".join("  %-6s" % ("P%d" % (i + 1)) for i in range(len(PREDICATES)))
               + "   exit")
    for t in tags:
        row = t.ljust(width)
        for name, _ in PREDICATES:
            row += "  %-6s" % ("repro" if scored[name][t] else ".")
        rc = caps[t][1]
        row += "   0x%08X" % (rc & 0xFFFFFFFF) if rc is not None else "   ?"
        out.append(row)
    out.append("")

    nrel = len([t for t in tags if t != "main-debug"])
    for i, (name, _) in enumerate(PREDICATES):
        n = sum(1 for t in tags if t != "main-debug" and scored[name][t])
        out.append("P%d  %s" % (i + 1, name))
        out.append("    history: %s" % history(scored[name], tags))
        out.append("    releases scored repro: %d of %d" % (n, nrel))
        out.append("")

    # A predicate is also defined by what it refuses to fire on.
    out.append("--- the same five predicates against the controls (main-debug) ---")
    out.append("A '!' marks a predicate firing on an input that is NOT the defect.")
    out.append("")
    cwidth = max(len(c) for c, _ in CONTROLS) + 2
    out.append("".ljust(cwidth)
               + "".join("  %-6s" % ("P%d" % (i + 1)) for i in range(len(PREDICATES)))
               + "   exit       what it is")
    for label, desc in CONTROLS:
        path = os.path.join(HERE, "variant-%s-main-debug.txt" % label)
        if not os.path.exists(path):
            out.append("%s  (capture missing)" % label.ljust(cwidth))
            continue
        text, rc = load(path)
        row = label.ljust(cwidth)
        for name, fn in PREDICATES:
            row += "  %-6s" % ("!" if fn(text, rc, False) else ".")
        row += "   0x%08X" % (rc & 0xFFFFFFFF)
        row += "  " + desc
        out.append(row)
    out.append("")

    out.append("--- why they differ ---")
    out.append("Four faces and two silences, all of the same defect. On the ground-truth")
    out.append("build the stack (manual-case-cast-stack.txt) shows a store to a $Globals-backed")
    out.append("object reaching TranslateCBAddressUserLegacy's `// Must be GEP here` in")
    out.append("lib/HLSL/HLOperationLower.cpp. The release binaries carry no symbols, so for")
    out.append("those the shared identity rests on the message where there is one and on the")
    out.append("input alone where there is not.")
    out.append("")
    out.append("P2 is the measured counterfactual the brief warned about. E_FAIL is")
    out.append("deliberately NOT in triage.py's INTERNAL_STATUS, because an ordinary syntax")
    out.append("error exits with it too -- see the control-syntaxerr row, which has the SAME")
    out.append("exit status as the repro. So exit status alone reports this still-open 2022")
    out.append("issue as fixed at v1.7.2207 (2022-07), four years early and wrong today.")
    out.append("")
    out.append("P3 and P4 fail in the other direction, inventing regressions where only the")
    out.append("wording changed. P3 misses three releases: v1.4.1907 and v1.5.2010 print")
    out.append("nothing at all, and v1.6.2104 prints a different message. P4 matches only the")
    out.append("three releases that happen to use the phrase from the issue title.")
    out.append("")
    out.append("P5 gets the release history right here, and is still the wrong predicate: it")
    out.append("fires on the syntax-error control, so on any other issue it would invent a")
    out.append("crash from a clean diagnosed failure. Being accidentally right on one issue")
    out.append("is not the same as being right.")
    out.append("")
    out.append("Both halves of is_internal_failure() are load-bearing: the status codes carry")
    out.append("v1.4.1907..v1.6.2112, and the build-agnostic 'cast<...>() argument' marker")
    out.append("carries v1.7.2207..main. Neither alone recovers the true range.")

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "manual-case-predicate-counterfactual.txt"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(text)
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
