#!/usr/bin/env python3
"""Capture the stack at the llvm_unreachable that #4384 hits.

Writes manual-case-unreachable-stack.txt next to this script. The command that is
about to run is printed with subprocess.list2cmdline, so the committed capture is
re-derivable rather than transcribed. cdb is launched directly by Python, with no
shell in between, so nothing re-quotes the -c script.

The dxc under test comes from DXC_EXE, or from the triage compiler registry entry
for main-debug, so nothing here hardcodes one contributor's layout. Paths in the
emitted text are rewritten to <repo>-relative form by anchoring on the repository
directory name, which is machine-independent.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent.parent.parent
REPO_NAME = "DirectXShaderCompiler"
OUT = HERE / "manual-case-unreachable-stack.txt"
CDB = Path(r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe")

FRAME = re.compile(r"^\s*[0-9a-f]{2} [0-9a-f`]{8,}")


def repo_root() -> Path:
    for parent in HERE.resolve().parents:
        if parent.name == REPO_NAME:
            return parent
    raise SystemExit("could not locate the repository root by name")


def dxc_exe() -> str:
    env = os.environ.get("DXC_EXE")
    if env:
        return env
    reg = SKILL / ".cache" / "compilers" / "main-debug.json"
    return json.loads(reg.read_text(encoding="utf-8"))["exe_path"]


def redact(text: str, root: Path) -> str:
    """Replace this checkout's root with <repo>, in both separator spellings."""
    forms = [str(root), str(root).replace("\\", "/"), str(root).replace("\\", "\\\\")]
    for form in sorted(forms, key=len, reverse=True):
        text = text.replace(form, "<repo>")
    return text


def trim(body: str) -> str:
    """Keep the exception banners and the call-stack frames, drop module loads."""
    keep, in_stack = [], False
    for line in body.splitlines():
        line = line.rstrip()
        if "Exception" in line and "ModLoad" not in line:
            keep.append(line)
            continue
        if "Call Site" in line:
            in_stack = True
            keep.append(line)
            continue
        if in_stack:
            if FRAME.match(line):
                keep.append(line)
            elif line.strip() == "":
                in_stack = False
                keep.append("")
    return "\n".join(keep).strip()


def main() -> int:
    root = repo_root()
    if not CDB.is_file():
        raise SystemExit(f"cdb.exe not found at {CDB}")

    argv = [
        str(CDB), "-c",
        'sxe -c "kn 22; gh" e06d7363; g; q',
        dxc_exe(), "-T", "cs_6_0", "-E", "main", "repro.hlsl",
    ]
    shown = subprocess.list2cmdline(argv)
    proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True, timeout=900)

    body = proc.stdout + proc.stderr
    text = trim(body)
    if not text:
        text = ("PARSE-WARNING: 0 stack frames matched; raw cdb output follows\n\n"
                + body)

    header = (
        "# Stack at the llvm_unreachable behind #4384, captured with cdb.\n"
        "# Generated by capture-stack.py; re-run it to re-derive this file.\n"
        "# Command (subprocess.list2cmdline of what was executed, cwd = this dir;\n"
        "# cdb was launched directly by Python, with no shell to re-quote it):\n"
        f"#   {redact(shown, root)}\n"
        f"# cdb exit: {proc.returncode}\n"
        "# Trimmed to exception banners and call-stack frames; module loads dropped.\n"
        "# The compiler's own message and exit status are in out-main-debug.txt.\n"
        "# Checkout root rewritten to <repo>.\n\n"
    )
    OUT.write_text(header + redact(text, root).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
