#!/usr/bin/env python3
"""Show what #4384's internal error throws away, and which conversion kind trips it.

Two observations in one cdb run, both about the moment of the throw:

  * `?? SCS->Second` at the frame that calls llvm_unreachable names the
    ImplicitConversionKind the switch in SemaOverload.cpp does not handle.
  * `gh` ("go handled") steps over the non-continuable C++ throw, so the compile
    carries on and the diagnostics DXC had *already* buffered reach stderr. They
    are absent from an ordinary run (out-main-debug.txt), which is the point.

Writes manual-case-suppressed-diagnostics.txt. The command is printed with
subprocess.list2cmdline, cdb is launched directly by Python with no shell to
re-quote it, and the checkout root is rewritten to <repo>.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent.parent.parent
REPO_NAME = "DirectXShaderCompiler"
OUT = HERE / "manual-case-suppressed-diagnostics.txt"
CDB = Path(r"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe")

# Frame 3 is CheckConvertedConstantConversions, the caller of llvm_unreachable;
# see manual-case-unreachable-stack.txt for the frame numbering this relies on.
SCRIPT = ('sxe -c ".frame 3; ?? SCS->Second; ?? SCS->First; ?? SCS->Third; gh" '
          'e06d7363; g; q')
KEEP = ("ImplicitConversionKind", "error:", "warning:", "enum EE", "E = uint3")


def repo_root() -> Path:
    for parent in HERE.resolve().parents:
        if parent.name == REPO_NAME:
            return parent
    raise SystemExit("could not locate the repository root by name")


def dxc_exe() -> str:
    env = os.environ.get("DXC_EXE")
    if env:
        return env
    reg = SKILL / ".cache" / "compilers" / "main-debug.json"
    return json.loads(reg.read_text(encoding="utf-8"))["exe_path"]


def redact(text: str, root: Path) -> str:
    forms = [str(root), str(root).replace("\\", "/"), str(root).replace("\\", "\\\\")]
    for form in sorted(forms, key=len, reverse=True):
        text = text.replace(form, "<repo>")
    return text


def main() -> int:
    root = repo_root()
    if not CDB.is_file():
        raise SystemExit(f"cdb.exe not found at {CDB}")

    argv = [str(CDB), "-c", SCRIPT, dxc_exe(),
            "-T", "cs_6_0", "-E", "main", "repro.hlsl"]
    shown = subprocess.list2cmdline(argv)
    proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True, timeout=900)

    body = proc.stdout + proc.stderr
    kept = [line.rstrip() for line in body.splitlines()
            if any(marker in line for marker in KEEP)]
    errors = [line for line in kept if "error:" in line]
    if not kept:
        kept = ["PARSE-WARNING: 0 lines matched; raw cdb output follows", "", body]

    header = (
        "# What #4384's internal error suppresses, and the conversion kind behind it.\n"
        "# Generated by capture-suppressed-diagnostics.py; re-run it to re-derive.\n"
        "# Command (subprocess.list2cmdline of what was executed, cwd = this dir;\n"
        "# cdb was launched directly by Python, with no shell to re-quote it):\n"
        f"#   {redact(shown, root)}\n"
        f"# cdb exit: {proc.returncode}\n"
        "# Filtered to the conversion-kind readout and the diagnostic lines.\n"
        "# `gh` steps over the non-continuable C++ throw, so what follows is the\n"
        "# compile continuing under the debugger -- not what an ordinary run does.\n"
        "# An ordinary run prints none of these errors: see out-main-debug.txt.\n"
        f"# SELFTEST: {len(errors)} error line(s) recovered "
        f"({'pass' if errors else 'FAIL -- nothing was recovered'}).\n\n"
    )
    OUT.write_text(header + redact("\n".join(kept), root).rstrip() + "\n",
                   encoding="utf-8")
    print(f"wrote {OUT.name}: {len(errors)} recovered error line(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
