#!/usr/bin/env python3
"""Per-release instrument check for #4384's diagnostic-quality predicate.

`triage.py bisect --match match-diag.json` reports every stable release as an
invalid probe, because every release ICEs on repro.hlsl and a crashed probe
measures nothing. That is the honest result, but on its own it cannot tell
"no release emits the right diagnostic for this input" apart from "the regex in
match-diag.json is dead". This script settles that by holding the predicate fixed
and varying the release, on inputs the releases *can* answer:

  control-uint3-scalar-init.hlsl  same invalid enum base (uint3), scalar enumerator
                                  -> the predicate MUST match on every release
  control-valid-enum.hlsl         a valid `enum : uint` shader
                                  -> self-test: MUST compile clean on every release

Releases are read from the triage catalog, so both physical release roots are
covered via releases.cached_path. Paths are rewritten to <repo>/<cache> form by
anchoring on directory names, so nothing here is machine-specific.
"""

import json
import os
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent.parent.parent
DB = SKILL / ".cache" / "triage.db"
CACHE = SKILL / ".cache"
REPO_NAME = "DirectXShaderCompiler"
OUT = HERE / "manual-case-diag-control-matrix.txt"

ARGS = ["-T", "cs_6_0", "-E", "main"]
DIAG = json.loads((HERE / "match-diag.json").read_text(encoding="utf-8"))["value"]
DIAG_RE = re.compile(DIAG, re.MULTILINE)


def repo_root() -> Path:
    for parent in HERE.resolve().parents:
        if parent.name == REPO_NAME:
            return parent
    raise SystemExit("could not locate the repository root by name")


def display(path: str, root: Path) -> str:
    text = str(path)
    for form, token in ((str(CACHE), "<cache>"), (str(root), "<repo>")):
        for spelling in (form, form.replace("\\", "/")):
            text = text.replace(spelling, token)
    return text.replace("\\", "/")


def ground_truth() -> str:
    env = os.environ.get("DXC_EXE")
    if env:
        return env
    reg = CACHE / "compilers" / "main-debug.json"
    return json.loads(reg.read_text(encoding="utf-8"))["exe_path"]


def builds():
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT tag, build_date, cached_path FROM releases "
        "WHERE prerelease = 0 AND cached_path IS NOT NULL "
        "ORDER BY build_date"
    ).fetchall()
    con.close()
    for row in rows:
        yield row["tag"], row["build_date"], row["cached_path"]
    yield "main-debug", "ground truth", ground_truth()


def run(exe: str, shader: str):
    argv = [exe] + ARGS + [shader]
    proc = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                          timeout=600, errors="replace")
    return subprocess.list2cmdline(argv), proc


def main() -> int:
    root = repo_root()
    lines = [
        "# Per-release instrument check for #4384's match-diag.json predicate.",
        "# Generated by measure-diag-control.py; re-run it to re-derive this file.",
        "# Every command below is printed with subprocess.list2cmdline of the argv",
        "# actually executed, from this directory. Paths shown as <repo>/<cache>.",
        "#",
        "# DIAG regex (read from match-diag.json, not retyped):",
        f"#   {DIAG}",
        "#",
        "# Columns: tag | build | uint3-scalar-init: exit, predicate | valid-enum: exit",
        "",
    ]
    failures = []
    rows = []
    for tag, date, exe in builds():
        shown_a, a = run(exe, "control-uint3-scalar-init.hlsl")
        shown_b, b = run(exe, "control-valid-enum.hlsl")
        text_a = a.stdout + a.stderr
        matched = bool(DIAG_RE.search(text_a))
        rows.append((tag, date, a.returncode, matched, b.returncode))
        lines.append(f"$ {display(shown_a, root)}")
        lines.append(f"  exit=0x{a.returncode & 0xFFFFFFFF:08X}  "
                     f"diag-predicate={'MATCH' if matched else 'no-match'}")
        for line in text_a.strip().splitlines():
            lines.append(f"  | {display(line, root)}")
        lines.append(f"$ {display(shown_b, root)}")
        lines.append(f"  exit=0x{b.returncode & 0xFFFFFFFF:08X}  "
                     f"self-test={'pass' if b.returncode == 0 else 'FAIL'}")
        lines.append("")
        if not matched:
            failures.append(f"{tag}: predicate did not match the scalar-init control")
        if b.returncode != 0:
            failures.append(f"{tag}: valid-enum self-test did not compile clean")

    lines.append("")
    lines.append("=== summary ===")
    lines.append(f"{'tag':<16}{'build':<14}{'uint3-scalar-init':<26}{'valid-enum'}")
    for tag, date, ra, matched, rb in rows:
        lines.append(
            f"{tag:<16}{date:<14}"
            f"{('0x%08X ' % (ra & 0xFFFFFFFF)) + ('MATCH' if matched else 'no-match'):<26}"
            f"{'0x%08X %s' % (rb & 0xFFFFFFFF, 'clean' if rb == 0 else 'NOT-CLEAN')}"
        )
    lines.append("")
    if failures:
        lines.append(f"MATRIX-4384: SELFTEST-WARNING: {len(failures)} problem(s)")
        lines.extend(f"  {f}" for f in failures)
    else:
        lines.append(f"MATRIX-4384: selftest=pass on all {len(rows)} builds: "
                     "the predicate fires on every one of them for a uint3 enum base, "
                     "and every one compiles a valid enum cleanly")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rows)} builds, {len(failures)} problem(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
