#!/usr/bin/env python3
"""Clang-pane controls for #4384.

The published Compiler Explorer link shows `hlsl_clang_trunk` diagnosing the enum
base that DXC crashes on. A cross-compiler difference is not evidence until the
same flags are shown not to fail on unrelated inputs, so this runs two controls
against the same CE compiler and the same arguments the published pane uses:

  control-valid-enum.hlsl        trivial valid shader -> must compile cleanly
  control-uint3-scalar-init.hlsl same subject, scalar enumerator -> must produce
                                 the same base-type error, showing the diagnostic
                                 is about the enum base and not the initialiser

Writes manual-case-clang-control.txt. Only public repro sources from this public
issue are uploaded.
"""

import json
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "manual-case-clang-control.txt"
CE = "https://godbolt.org"
COMPILER = "hlsl_clang_trunk"
ARGS = "-T cs_6_0 -E main"
FILTERS = {"execute": False, "intel": False, "demangle": False, "labels": False,
           "directives": False, "commentOnly": False, "trim": False,
           "binary": False}
CASES = ["control-valid-enum.hlsl", "control-uint3-scalar-init.hlsl"]


def compile_on_ce(source: str):
    payload = json.dumps({
        "source": source, "lang": "hlsl", "compiler": COMPILER,
        "options": {"userArguments": ARGS,
                    "compilerOptions": {"skipAsm": False,
                                        "executorRequest": False},
                    "filters": dict(FILTERS), "tools": [], "libraries": []},
        "allowStoreCodeDebug": True,
    }).encode()
    req = urllib.request.Request(
        f"{CE}/api/compiler/{COMPILER}/compile", data=payload,
        headers={"Content-Type": "application/json", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        res = json.load(resp)
    text = "\n".join(x.get("text", "") for stream in ("stdout", "stderr")
                     for x in res.get(stream, []))
    return res.get("code"), text


def main() -> int:
    lines = [
        f"# Compiler Explorer controls for #4384's {COMPILER} pane.",
        "# Generated by measure-clang-control.py; re-run it to re-derive this file.",
        f"# POST {CE}/api/compiler/{COMPILER}/compile",
        f"# userArguments: {ARGS}",
        "# CE runs Linux Release builds; these corroborate the local evidence.",
        "# Sources are uploaded verbatim, with no prepended banner, so line",
        "# numbers here match the files in this directory.",
        "",
    ]
    problems = []
    for case in CASES:
        source = (HERE / case).read_text(encoding="utf-8")
        code, text = compile_on_ce(source)
        lines.append(f"=== {case} -> exit {code} ===")
        lines.extend(text.rstrip().splitlines() or ["<no output>"])
        lines.append("")
        if case == "control-valid-enum.hlsl" and code != 0:
            problems.append(f"{case}: expected a clean compile, got exit {code}")
        if case == "control-uint3-scalar-init.hlsl" and \
                "invalid underlying type" not in text:
            problems.append(f"{case}: expected the base-type error, not found")
    if problems:
        lines.append(f"CLANG-4384: CONTROL-WARNING: {len(problems)} problem(s)")
        lines.extend(f"  {p}" for p in problems)
    else:
        lines.append("CLANG-4384: controls=pass -- the trivial shader compiles "
                     "clean, so the pane is not failing on everything, and the "
                     "scalar-enumerator case still names the enum base.")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(problems)} problem(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
