#!/usr/bin/env python3
"""Show that #4384's leaked absolute path is printed by dxc, not by triage.py.

Seven captures in this directory once failed `check_paths.py`. The hit was always
the same token: LLVM's `llvm_unreachable` prints

    UNREACHABLE executed at <__FILE__>:<line>!

and `__FILE__` is the absolute source path recorded when this dxc was built, so
for a local build it is the operator's checkout root.

This script is what located the generator, and the answer decided the fix:

  * The generator is the compiler. This runs dxc directly, with no triage.py and
    no shell, and the path is still there -- so hand-editing a capture would have
    been falsifying compiler output, not tidying a harness artifact.
  * Therefore the fix belonged in the harness that records that output.
    `triage.py` now has `redact_paths()`, applied to stdout and stderr in
    `_run_command_list` before the capture is written *and* before it is scored,
    so a predicate matches exactly what a reader sees. The seven captures were
    regenerated with `run --force`; no verdict moved.

The alternative -- an allowlist entry per capture -- was rejected: it would have
committed one machine's checkout layout, which is what the gate exists to
prevent, and the informative part of the path is which file asserted, which
`<repo>\\tools\\clang\\lib\\Sema\\SemaOverload.cpp:5154` still says.

This file redacts the root itself, and says so, so it is safe to commit.

Re-run:  python prove-path-is-compiler-output.py
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# .../<repo>/.github/skills/dxc-issue-triage/data/issues/4384 -- six levels up.
REPO = os.path.abspath(os.path.join(HERE, *[os.pardir] * 6))
DXC = os.path.join(REPO, "build", "Debug", "bin", "dxc.exe")
OUT = os.path.join(HERE, "manual-case-path-provenance.txt")

# The tail is the part that carries information: which file, which line.
UNREACHABLE = re.compile(
    r"UNREACHABLE executed at (?P<path>.+?tools[\\/]clang[\\/]lib[\\/]Sema[\\/]"
    r"SemaOverload\.cpp):(?P<line>\d+)!")


def redact(text):
    return text.replace(REPO, "<repo>").replace(REPO.replace("\\", "/"),
                                                "<repo>")


def main():
    if not os.path.isfile(DXC):
        sys.exit(f"no compiler at {redact(DXC)}")
    argv = [DXC, "-T", "cs_6_0", "-E", "main", "repro.hlsl"]
    p = subprocess.run(argv, cwd=HERE, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    err = p.stderr
    m = UNREACHABLE.search(err)

    checks = [
        ("dxc was run directly, with no triage.py and no shell", True),
        ("stderr carries an UNREACHABLE line", m is not None),
        ("its path is absolute", bool(m) and os.path.isabs(m.group("path"))),
        ("its path starts with this checkout's root",
         bool(m) and os.path.normcase(m.group("path")).startswith(
             os.path.normcase(REPO))),
        ("it names SemaOverload.cpp:5154", bool(m) and m.group("line") == "5154"),
    ]
    passed = all(ok for _, ok in checks)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Where #4384's leaked absolute path comes from.\n")
        f.write("# Generated by prove-path-is-compiler-output.py; re-run it to"
                " re-derive.\n")
        f.write("# Command (subprocess.list2cmdline, cwd = this directory):\n")
        f.write(f"#   {redact(subprocess.list2cmdline(argv))}\n")
        f.write(f"# exit: {p.returncode} (0x{p.returncode & 0xFFFFFFFF:08X})\n")
        f.write("# Checkout root rewritten to <repo> BELOW ONLY, by this"
                " script, so it can be committed.\n")
        f.write("# The triage.py captures this file is about now carry the same"
                " token because\n")
        f.write("# triage.py redacts stdout/stderr before writing AND before"
                " scoring them.\n")
        f.write(f"# SELFTEST: {'pass' if passed else 'FAIL'}\n\n")
        for label, ok in checks:
            f.write(f"{'PASS' if ok else 'FAIL'}  {label}\n")
        f.write("\n--- stderr, checkout root redacted ---\n")
        f.write(redact(err))
        if m:
            f.write("\n--- the exact token the gate matches, in this run ---\n")
            f.write(f"raw length {len(m.group('path'))} chars; redacted form:\n")
            f.write(redact(m.group("path")) + "\n")
    print(f"wrote {os.path.basename(OUT)}: selftest"
          f" {'pass' if passed else 'FAIL'}")
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
