"""Per-release feature-presence matrix for #3902.

SKILL.md step 6 requires the feature-presence control to be run on *every* probed release,
not only on ground truth: a release can reject the repro for a reason that has nothing to do
with the issue, and a release can accept it while being unable to show the symptom at all.
`triage.py run --shader` only retargets the registered ground-truth compiler, so the
per-release arm needs an issue-local matrix.

For each catalogued release (stable and prerelease, so the excluded prereleases are visible
rather than merely asserted) this runs, with that release's own dxc.exe:

  repro.hlsl         the unused RayQuery                       -- expect the issue's error
  control-used.hlsl  the same RayQuery, actually used          -- expect a clean compile
  control-hello.hlsl no ray tracing at all, same profile/args  -- expect a clean compile

control-used is the feature-presence control: if it fails too, that release cannot express
DXR 1.1 and its repro result is not evidence.  control-hello separates that from "cannot
compile cs_6_5 at all".

Every command is printed with subprocess.list2cmdline, so the transcript cannot claim a
command that was not run.  Regenerate with:

    python measure-release-matrix.py
"""

import json
import os
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
SKILL = HERE.parents[2]
REPO = HERE.parents[5]
TRIAGE = SKILL / "scripts" / "triage.py"
OUT = HERE / "manual-case-release-matrix.txt"

CASES = [
    ("repro", ["-T", "cs_6_5", "-E", "computeRTAO", "repro.hlsl"]),
    ("control-used", ["-T", "cs_6_5", "-E", "computeRTAO", "control-used.hlsl"]),
    ("control-hello", ["-T", "cs_6_5", "-E", "computeRTAO", "control-hello.hlsl"]),
]

SYMPTOM_SOURCE = HERE / "match.json"


def symptom_regexes():
    """Read the clauses out of match.json rather than restating them here.  A matrix that
    carries its own copy of the predicate can silently disagree with the one triage.py scores,
    and then the two halves of the evidence are answering different questions."""
    spec = json.loads(SYMPTOM_SOURCE.read_text(encoding="utf-8"))
    assert spec["kind"] == "all_of", "this matrix only understands all_of"
    out = []
    for clause in spec["value"]:
        if clause["kind"] == "regex":
            out.append(re.compile(clause["value"], re.MULTILINE))
        elif clause["kind"] == "contains":
            out.append(re.compile(re.escape(clause["value"]), re.MULTILINE))
        else:
            raise AssertionError("unhandled clause kind %r" % clause["kind"])
    return out


SYMPTOM = symptom_regexes()


def display(p):
    s = str(p)
    for root, tag in ((str(SKILL / ".cache"), "<cache>"), (str(REPO), "<repo>")):
        s = s.replace(root, tag)
    return s.replace("\\", "/")


def releases():
    q = "SELECT tag, build_date, prerelease, cached_path FROM releases ORDER BY build_date"
    out = subprocess.run([sys.executable, str(TRIAGE), "sql", q],
                         capture_output=True, text=True, check=True).stdout
    return [r for r in json.loads(out) if r["cached_path"]]


def scored(text):
    return "MATCH" if all(rx.search(text) for rx in SYMPTOM) else "no-match"


def diagnostics(text, limit=12):
    """Every diagnostic line, not just the first: on the oldest releases the line that says
    why the build could not run the case is several lines down."""
    keep = [ln.rstrip() for ln in text.splitlines()
            if ln.strip() and not ln.lstrip().startswith((";", "^", "target ", "%dx"))]
    return keep[:limit]


def identity(exe):
    """`--version` postdates the oldest releases ("dxc failed : Unknown argument"), so record
    the shipped dxcompiler.dll's ProductVersion as well -- that answer is always available."""
    dll = exe.parent / "dxcompiler.dll"
    if not dll.exists():
        return "dxcompiler.dll not beside dxc.exe"
    ps = ["powershell", "-NoProfile", "-Command",
          "(Get-Item '%s').VersionInfo.ProductVersion" % dll]
    return subprocess.run(ps, capture_output=True, text=True).stdout.strip()


def main():
    lines = [
        "#3902 per-release matrix: repro + feature-presence control + trivial control.",
        "Generated by measure-release-matrix.py; every command below was executed as printed.",
        "MATCH means every clause of match.json was found in the combined output; the clauses",
        "are read from match.json at run time, not restated here.",
        "",
    ]
    summary = []
    for rel in releases():
        exe = pathlib.Path(rel["cached_path"])
        if not exe.exists():
            lines.append("## %s -- cached_path missing on this machine: %s\n"
                         % (rel["tag"], display(exe)))
            continue
        kind = "prerelease" if rel["prerelease"] else "stable"
        lines.append("## %s  (%s, %s)" % (rel["tag"], rel["build_date"], kind))
        ver = subprocess.run([str(exe), "--version"], capture_output=True, text=True)
        lines.append("$ " + subprocess.list2cmdline([display(exe), "--version"]))
        lines.append((ver.stdout + ver.stderr).strip())
        lines.append("[dxcompiler.dll ProductVersion] " + identity(exe))
        row = {"tag": rel["tag"], "kind": kind}
        for name, args in CASES:
            p = subprocess.run([str(exe)] + args, cwd=HERE, capture_output=True, text=True)
            combined = p.stdout + p.stderr
            row[name] = scored(combined)
            lines.append("$ " + subprocess.list2cmdline([display(exe)] + args))
            lines.append("[exit] %d (0x%08X)  -> %s"
                         % (p.returncode, p.returncode & 0xFFFFFFFF, row[name]))
            if p.returncode != 0:
                lines.extend("    " + ln for ln in diagnostics(combined))
        summary.append(row)
        lines.append("")

    lines.append("## summary")
    lines.append("%-16s %-11s %-9s %-13s %s" % ("tag", "kind", "repro", "control-used",
                                                "control-hello"))
    for r in summary:
        lines.append("%-16s %-11s %-9s %-13s %s"
                     % (r["tag"], r["kind"], r["repro"], r["control-used"], r["control-hello"]))
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for stray in HERE.glob("*.cso"):
        stray.unlink()
    print(OUT)


if __name__ == "__main__":
    sys.exit(main())
