#!/usr/bin/env python3
"""Release matrix for #4096, driven by each release's own dxc.exe.

Two questions `triage.py bisect` cannot answer on its own:

1. **Feature presence.** Four releases score `invalid-probe` on the repro. On
   its own that is ambiguous between "this release predates HLSL 2021" and
   "something unrelated in the repro was rejected". `control-hlsl2021-presence`
   is the smallest shader that still asks for `-HV 2021`, so if a release
   rejects it too, the rejection is about the language mode.

2. **Was the operator body ever used?** The reporter's shader cannot say: with
   `Foo A = {1}` the operator (`x < 5`) and HLSL's flat conversion (`bool(x)`)
   agree, and nothing is stored. `case-cstyle-cast.hlsl` makes them disagree and
   writes the answer to a buffer -- 222 if the operator ran, 111 if the flat
   conversion did.

Every command is echoed with subprocess.list2cmdline, so the transcript is what
actually ran rather than a transcription of it. Run from this directory:

    python measure-history.py > manual-case-release-matrix.txt
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))
TRIAGE = os.path.join(SKILL, "scripts", "triage.py")
CACHE = os.environ.get("DXC_TRIAGE_CACHE", os.path.join(SKILL, ".cache"))

ARGS = ["-T", "cs_6_0", "-E", "main", "-HV", "2021"]
SHADERS = ["control-hlsl2021-presence.hlsl", "case-cstyle-cast.hlsl"]


def display(path):
    """Machine-independent rendering, anchored on the repo name not a layout."""
    parts = path.replace("\\", "/").split("/")
    for i, p in enumerate(parts):
        if p.lower() == "directxshadercompiler":
            return "<repo>/" + "/".join(parts[i + 1:])
    return path


def builds():
    out = subprocess.run(
        [sys.executable, TRIAGE, "sql",
         "SELECT tag, build_date, prerelease, cached_path FROM releases "
         "WHERE cached_path IS NOT NULL AND prerelease = 0 "
         "ORDER BY build_date"],
        capture_output=True, text=True, check=True).stdout
    rows = [(r["tag"], r["build_date"], r["cached_path"])
            for r in json.loads(out)]
    reg = os.path.join(CACHE, "compilers", "main-debug.json")
    with open(reg) as f:
        gt = json.load(f)
    rows.append(("main-debug", gt.get("git_commit", "")[:9], gt["exe_path"]))
    return rows


def run(exe, shader):
    argv = [exe] + ARGS + [shader]
    print("$ " + subprocess.list2cmdline([display(exe)] + ARGS + [shader]))
    p = subprocess.run(argv, capture_output=True, text=True, cwd=HERE)
    text = (p.stdout or "") + (p.stderr or "")
    print("[exit] %d (0x%08X)" % (p.returncode, p.returncode & 0xFFFFFFFF))
    return p.returncode, text


def summarise(shader, rc, text):
    """One-line reading of the run, plus a self-test so silence is loud."""
    errs = [ln.strip() for ln in text.splitlines() if ": error:" in ln
            or ln.startswith("dxc failed")]
    if shader == "control-hlsl2021-presence.hlsl":
        if rc == 0:
            return "HLSL-2021 ACCEPTED"
        return "HLSL-2021 REJECTED :: " + (errs[0] if errs else "(no message)")
    stored = [v for v in ("111", "222") if ("i32 %s," % v) in text]
    if errs:
        return "REJECTED :: " + errs[0]
    if len(stored) != 1:
        return ("MATRIX-4096: PARSE-WARNING: expected exactly one of 111/222 "
                "in the DXIL, found %r -- read the raw output" % stored)
    if stored[0] == "111":
        return "stored 111 -> FLAT CONVERSION used, operator body NOT invoked"
    return "stored 222 -> operator body invoked"


def main():
    print("# #4096 release matrix -- each release driven by its own dxc.exe")
    print("# generated by measure-history.py; every command below is echoed "
          "from the argv that ran")
    print("# stable releases only; prereleases are outside the search by "
          "policy")
    print()
    verdicts = []
    for tag, date, exe in builds():
        print("=" * 72)
        print("### %s  (%s)" % (tag, date))
        print("=" * 72)
        row = [tag, date]
        for shader in SHADERS:
            rc, text = run(exe, shader)
            note = summarise(shader, rc, text)
            print("[read] " + note)
            print()
            row.append(note)
        verdicts.append(row)
    print("=" * 72)
    print("### SUMMARY")
    print("=" * 72)
    print("%-14s %-12s %-24s %s" % ("build", "date", "presence control",
                                    "case-cstyle-cast.hlsl"))
    for tag, date, presence, cast in verdicts:
        print("%-14s %-12s %-24s %s" % (tag, date, presence.split(" ::")[0],
                                        cast))


if __name__ == "__main__":
    main()
